### ISSUE TITLE
How to test a method that result in changing objects in other class

### ISSUE THREAD

**Issue by Rachelcoll** [nus-cs2103-AY2425S1/forum#113]
For example my command object leads to manipulating taskList object, but i cannot check inside the taskList object as its field is private.

**Comment by lithops-zty** [comment]
Personally I would add getters to the properties to be checked.

**Comment by Rachelcoll** [comment]
> Personally I would add getters to the properties to be checked.

Will this affects encapsulation of the class?
Also I tried using stubs but it seems quite weird to reimplement a lot of same classes in each class

**Comment by lithops-zty** [comment]
> Will this affects encapsulation of the class?

This is a actually good point I did not consider.

Searching online, there is a highly upvoted stackoverflow question that discusses this problem, here:
https://stackoverflow.com/questions/34571/how-do-i-test-a-class-that-has-private-methods-fields-or-inner-classes

I found one comment by Colin M which I found convincing, that says
> By testing private methods you are testing the implementation. This defeats the purpose of unit testing, which is to test the inputs/outputs of a class' contract.

So I guess in your specific situation, instead of trying to test directly on private fields of TaskList, you may test through its exposed interfaces (there should be some public method like getTask()). 

That said, it is just my immature idea. If anyone has a different opinion or approach, please feel free to comment below!

**Comment by itsme-zeix** [comment]
> Will this affects encapsulation of the class? Also I tried using stubs but it seems quite weird to reimplement a lot of same classes in each class

Hmm, my train of thought was also to use mocks/stubs. You could extend the original class and override existing methods/write new methods that you need to control/inspect so I don't think there should be that much reimplementation.

Maybe you could try something like this?
```java
public class TaskListStub extends TaskList {
    private List<Task> tasksStub = new ArrayList<>();
    
    // Override some existing method to modify behaviour for testing
    @Override
    public void addTask(Task task) {
        tasksStub.add(task);
    }
    
    // Additional method to check for the modified behaviour without
    // implementing a getter in TaskList to access private fields.
    public boolean wasTaskAdded(Task task) { 
        return tasksStub.contains(task);
    }
}
```
The added method `wasTaskAdded()` avoids the use of a getter in the original `TaskList`. You could probably add similar methods to handle logic related to the private fields. Not sure if this is what you are looking for but hope this helps!

**Comment by tohhengxing** [comment]
> > Will this affects encapsulation of the class?
> 
> This is a actually good point I did not consider.
> 
> Searching online, there is a highly upvoted stackoverflow question that discusses this problem, here: https://stackoverflow.com/questions/34571/how-do-i-test-a-class-that-has-private-methods-fields-or-inner-classes
> 
> I found one comment by Colin M which I found convincing, that says
> 
> > By testing private methods you are testing the implementation. This defeats the purpose of unit testing, which is to test the inputs/outputs of a class' contract.
> 
> So I guess in your specific situation, instead of trying to test directly on private fields of TaskList, you may test through its exposed interfaces (there should be some public method like getTask()).
> 
> That said, it is just my immature idea. If anyone has a different opinion or approach, please feel free to comment below!

This should be correct. What's the point of testing implementation? A significant point of writing tests is to ensure that when code changes, behaviour doesn't. Testing the contract makes more sense.

**Comment by yadobler** [comment]
> > By testing private methods you are testing the implementation. This defeats the purpose of unit testing, which is to test the inputs/outputs of a class' contract.
> 
> So I guess in your specific situation, instead of trying to test directly on private fields of TaskList, you may test through its exposed interfaces (there should be some public method like getTask()).


If  InputState ---Command--> OutputState is deterministic, think about how we'd do it for another input/output:

```java
// testing function "int square(int)"
int input = 3;
int expected = 9;
int output = square(input);
assertEqual(expected, output);
```

So for your command you're testing,

```java
// testing function "oogaBooga(TaskList t)"
TaskList list = new TaskList(Task a, Task b);
int expected = new TaskList(Task x, Task y);
oogaBooga(list);
assertEqual(expected, list);
```

If you do this you **will fail** because by default, all Object subclasses'  `.equals(Object other)` will compare the pointer address in the heap. What you need to do is to Override `.equals(Object other)` like we did in CS2040S. so you can compare if the new state of `list` is exactly what you expected in `expected`.

This will let you:
1. Test the command function
2. Not touch the `TaskList` private functions
