### ISSUE TITLE
When is it okay to make methods static?

### ISSUE THREAD

**Issue by yizhong187** [nus-cs2103-AY2425S1/forum#114]
```
public Duke(String filePath) {
     ui = new Ui();
     storage = new Storage(filePath);
     try {
         tasks = new TaskList(storage.load());
     } catch (DukeException e) {
         ui.showLoadingError();
         tasks = new TaskList();
     }
 }
```

When attempting the MoreOOP Increment, I notice this example, where a new Ui object is instantiated, and the `showLoadingError` method was called from that object. However, assuming the `showLoadingError` method does not require any instance variable from the object, is it acceptable to set it as a static method that can be used without the instantiation of an object?

Consequently, is it okay for me to have a PrintUtils class in a utils package that contains only static methods that are used for outputting message to the user?

**Comment by Incogdino** [comment]
My opinion on this issue is that if the static method does not have to work with a shared state/field, then yes it is suitable for it to be static.

If the behavior of the method is predictable with or without an instance of the class, then a static method is more suitable. 

> Consequently, is it okay for me to have a PrintUtils class in a utils package that contains only static methods that are used for outputting message to the user?

I agree with this design as it makes the code more in line with the "Single Responsibility Principle", making it cleaner and easier to understand.

This is just my opinion though, don't take it too seriously 🙃

**Comment by yizhong187** [comment]
@Incogdino thats what I thought too, but referring to the `showLoadingError` method call seems to break that expectation.

**Comment by lithops-zty** [comment]
To add on,

> Consequently, is it okay for me to have a PrintUtils class in a utils package that contains only static methods that are used for outputting message to the user?

It is probably okay if the project size is small. However, if the project gets more complicated with many packages, then it might not be wise to extract all message printing methods into the same place as it violates the modulization principle.

**Comment by Incogdino** [comment]
> @Incogdino thats what I thought too, but referring to the `showLoadingError` method call seems to break that expectation.

Sorry I do not quite get what you mean by this? Do you mean that `showLoadingError` is meant to display a custom error message depending on the type of exception thrown?

**Comment by yizhong187** [comment]
@Incogdino `showLoadingError` would not display a custom error depending on the type of exception thrown, and is stateless (I assume, based on the fact that nothing was passed/done to the Ui object). However, it is made an instance method, instead of a static one, and that is breaking my expectation of:

> If the behavior of the method is predictable with or without an instance of the class, then a static method is more suitable.

**Comment by Incogdino** [comment]
Sorry I think you might have misunderstood what I meant or I might have phrased it wrongly. 

What I meant was that if the method produces a behavior/output that is the same and does not change regardless of any changes to instance fields, then I think it can be declared as a static method. 

In this case I do think `showLoadingError` should be declared as static since it prints an error message to the console (I assume) that does not change (stateless) 

Hopefully this is clearer 😄

**Comment by yizhong187** [comment]
@Incogdino LOL (can I say that in the forum 🤣 ) I think we understand each other, I am just pointing out the fact that `showLoadingError` does not correspond with **our common understanding**  that stateless methods should be declared as static. Anyways thanks for your help and discussion :)
