### ISSUE TITLE
Issue with List<String> in IntelliJ IDEA

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#130]
### Issue with `List<String>` in IntelliJ IDEA

**Environment:**
- IntelliJ IDEA version: 23
- Java version: 17

**Problem:**

I'm encountering an issue in IntelliJ IDEA where it red-underlines `List<String>` and prompts me to use the raw type `List` instead. The code snippet where this occurs is:

```java
List<String> strings = Files.readAllLines(Paths.get("data/rapgod.txt"));  //error prompted
```

To resolve this, the only thing that works is using the fully qualified class name:

```java
java.util.List<String> strings = Files.readAllLines(Paths.get("data/rapgod.txt"));
```

I already have the following import statement in my code:

```java
import java.util.List;
```

**Expected Behavior:**

I expect IntelliJ to recognize the `List<String>` type without needing to use the fully qualified class name, given that the import statement is already in place.

**Steps Taken:**

- Verified the import statement is correct.
- Restarted IntelliJ.

**Request:**

Could someone help me understand why this issue is occurring and how to resolve it? TIA!

**Comment by adipanda2002** [comment]
Could you share a screenshot of the error message? Might help to identify.

In any case, I'd recommend switching to ArrayList for what I think this part of your code is trying to do.

**Comment by damithc** [comment]
> Could you share a screenshot of the error message? Might help to identify.

Yup, that will be helpful. Although using the fully-qualified class name made the error go away, it could have been triggered by something else. Seeing the full error can help diagnose it better.

**Comment by emmannyyy** [comment]
I believe this may have occured because of 2 possible scenarios: 

1. Intellij may have been configured to use fully qualified class names. 
To remove this, ensure that your configuration has unchecked "Use fully qualified class names"
-> Settings -> codestyle -> java -> imports
![image](https://github.com/user-attachments/assets/d3a63b39-fedd-415e-9933-ec5527a999c9)
Make sure that it is unchecked. 

2. There may have been multiple imports that has the List interface
In this scenario, Intellij may find it ambiguous on which type you are declaring, hence prompting the use of fully qualified names. If this is the case, troubleshoot to see if there are multiple imports that have this interface, and removing/deconflicting if unnecessary. 


Personally, as per what @adipanda2002 said, it may also be wise to just use  `ArrayList` instead. I did this, and hence did not encounter this error

Hope this helps :)

**Comment by kimxw** [comment]
Hello everyone, I appreciate all the detailed and quick replies. 

When I was going back to take a screenshot to attatch to this issue, I realised the problem. I had created my own 'List.java' to abstract the task list in the chatbot without realising that the name clashes with java's List.java (my bad)

I will change the class name to TaskList

So sorry about this careless mistake. Thanks again everyone!

**Comment by damithc** [comment]
Thanks for everyone who pitched in ...

>it may also be wise to just use ArrayList instead. I did this, and hence did not encounter this error

On this, in general, it is better to use the interface `List` rather that the concrete implementation i.e., `ArryaList` as the type, where possible. This makes the code less fragile, as this makes (some parts) of the code to be reusable with any concrete class that implements the `List` interface, rather than being tied to one such class.
