### ISSUE TITLE
Style checking script

### ISSUE THREAD

**Issue by FYL2003** [nus-cs2103-AY2425S1/forum#133]
Does anyone find any type of style check for this course?

**Comment by damithc** [comment]
@FYL2003 Did you mean something like the `A-CheckStyle` iP increment in [week 4](https://nus-cs2103-ay2425s1.github.io/website/schedule/week4/project.html) ?

**Comment by yadobler** [comment]
I used `java-check.xml` from online, but I tweaked some parameters. Of the top of my head, changing the indent from 2->4, `case` indent to 0, and playing with the [customImportOrderRule](https://checkstyle.sourceforge.io/checks/imports/customimportorder.html) so that it matches whatever said [here](https://se-education.org/guides/conventions/java/intermediate.html#package-and-import-statements) and the respective Intellij IDEA style [here](https://se-education.org/guides/conventions/java/index.html)

**Comment by muller317** [comment]
> I used `java-check.xml` from online, but I tweaked some parameters. Of the top of my head, changing the indent from 2->4, `case` indent to 0, and playing with the [customImportOrderRule](https://checkstyle.sourceforge.io/checks/imports/customimportorder.html) so that it matches whatever said [here](https://se-education.org/guides/conventions/java/intermediate.html#package-and-import-statements) and the respective Intellij IDEA style [here](https://se-education.org/guides/conventions/java/index.html)

Hi, may you share the XML file? Appreciated it

**Comment by damithc** [comment]
@muller317 This tutorial (given under A-Checkstyle) already provides the necessary config files https://se-education.org/guides/tutorials/checkstyle.html

> Hi, may you share the XML file? Appreciated it

If the file is version controlled, you should be able to see it in his iP repo, and also in [the iP code dashboard](https://nus-cs2103-ay2425s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt).

**Comment by yadobler** [comment]
Yup it's in my [repo](https://github.com/yadobler/ip/blob/57d59395cc79f96c885bbf6cf566c2a9f6d3eb9d/config/checkstyle/checkstyle.xml)
