### ISSUE TITLE
JUnit Test Issue

### ISSUE THREAD

**Issue by SherChew27** [nus-cs2103-AY2425S1/forum#135]
When I click on the green play button for my JUnit tests, i get the following error:
Execution failed for task ':test'.
> No tests found for given includes: [Bellroy.TodoTest.testMarkDone](--tests filter)

However, I am able to run the test cases in my terminal by using ./gradlew test. 

Whats the issue here and how do I fix it?

**Comment by damithc** [comment]
While waiting for inputs from others, try these 'common remedies' one-at-a-time in this order:
  * Choose `File` -> `Invalidate caches`
  * Close Intellij -> Delete the `.idea` folder -> Re open the project in Intellij
  * Clone the fork to a different location and open the project in Intellij again to get a fresh start without losing changes you did so far.

**Comment by ty-3401** [comment]
Hi, I also encountered a similar issue. However, my test cases were not able to be run even through the terminal. I fixed it by using gradle to clean the previous build, and building it again.

As stated by the error, I believe gradle was unable to find the test cases. When I only ran the specific test case, ToDoTest in this case, which is under the Tasks package, the following error pops up.
```
Execution failed for task ':test'.
> No tests found for given includes: [tasks.ToDoTest](--tests filter)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```
I then ran it using the following gradle test command
![image](https://github.com/user-attachments/assets/8a025bd5-0fca-49c4-8836-ac3af6ed8b89)

This gave me the following error:
```
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test FAILED
CookTest > dummyTest() PASSED
ParserTest > dummyTest() PASSED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///C:/Users/lm-44/Downloads/ip/build/reports/tests/test/index.html
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 733ms
3 actionable tasks: 1 executed, 2 up-to-date
```

Opening the report allowed me to see this page, which I then clicked on the failed test.
![image](https://github.com/user-attachments/assets/131ec10a-1831-4841-a652-b5fb76de6f24)

One of the lines informed me that gradle was expecting my test to be under the "Tasks" folder instead of "tasks" folder.
```
Caused by: java.lang.NoClassDefFoundError: tasks/ToDoTest (wrong name: Tasks/ToDoTest)
```
This was likely because I renamed my "Tasks" package to "tasks" instead to follow package name conventions. Having already built the project before this change, I am guessing that gradle was expecting a different name based on the built project, which led to the error.

If rebuilding your project doesn't fix your error, maybe your report may tell you more to help fix it.

**Comment by travisim** [comment]
@SherChew27 i faced the same issue as you. 
I could not click the small play button but  ```./gradlew test``` works.

The fix i found was that package names should be in lower case 
**So refactor Bellroy to bellroy with intellij to fix it.**

credits: https://github.com/nus-cs2103-AY2324S1/forum/issues/67
