### ISSUE TITLE
Forum dashboard shows symbols incorrectly

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#147]
The forum leaderboard shows the posts display the symbols incorrectly - in this example curly braces `{}` as well as the more than inequality `>`.

On the forum (GitHub):
![image](https://github.com/user-attachments/assets/5df6f67c-452d-4428-838a-03a609616ae5)

On the forum leaderboard (on 2103T website):
![image](https://github.com/user-attachments/assets/c0849bcf-4077-45e6-9fe0-1d7d62422937)

This is probably from Markdown encoding, but there should be a way to decode it back.

**Comment by damithc** [comment]
@zaidansani Thanks for reporting this 💯 
Yes, the forum dashboard sometimes get the formatting wrong, but we let it be (unless it messes up the page entirely), as the purpose of the dashboard is to give some sense of the level of contribution only (reading and understanding the post contents is usually not needed as posts don't even appear in their original thread).
The reason is, it is hard to embed forum posts (written in GFMD) inside panels written using [MarkBind](https://markbind.org/) (the tool we use for course websites) as there are many different languages involved and sometimes there are syntax clashes between them. So, we do just a crude sanitization to escape any special chars in the forum post (rather than a full-blown parsing).
