### ISSUE TITLE
Do Objects have to be immutable?

### ISSUE THREAD

**Issue by zzzlou** [nus-cs2103-AY2425S1/forum#15]
Hi, do objects have to be immutable?

In CS2030, we have to make every object immutable, and every attribute needs to be declared as "final." Is that the case in this course too?

Thanks!

**Comment by damithc** [comment]
@zzzlou There is no such requirement from the course side. But you all are welcome to discuss here pros, cons, best practices of this aspect, and proceed with what you think is the best approach.

**Comment by tohhengxing** [comment]
What's the benefit of making every object immutable at this stage of the project?

**Comment by Wxy2003-xy** [comment]
I think in 2030 you only need to make objects immutable in the context of doing functional style coding. Otherwise its fine having mutable objects

**Comment by flyingsalsa** [comment]
Immutability is for safe sharing of object internals between classes (keeps them safe from any changes), idt there's any need for that at this stage of the project however as the mostly likely implementation of duke is using switch statements.

**Comment by matthewyip1511** [comment]
In CS2030 (the version taught by Prof Henry Chia) he advocates for all objects to be made immutable. For eg. if you want to change a `Task` object from being not-done to done, you should return a `new Task` rather than by modifying the boolean attribute tracking the "doneness" of the task. This makes the coding "safer" as there's no risk of accidentally changing the state / value of objects during runtime, but also makes it harder to program as the object changes after each state change (and the new object needs to slot into the place of the old one).

**Comment by WinstonJin** [comment]
I think for the future when we add more stuff to the code, if we make it immutable its gonna take a really long time to load it. So I personally jsut did a mutable one

**Comment by joeltio** [comment]
I would like to share my thoughts as well. My opinion is to make things that are supposed to _always_ be immutable, immutable and things that are not immutable not immutable. Things should not be immutable by default unless enforced by the programming language (e.g. you are using a functional programming language).

When you create a class that is final, it should be a _final_ commitment. Every other piece of code that will interact with your class will try to make a copy just to make modifications. Some pieces of concurrent code may also assume that it will never change and treat it as safe for [repeatable reads](https://en.wikipedia.org/wiki/Read%E2%80%93write_conflict).

When a new requirement comes and forces us to change our class to not be final, then we are breaking all these assumptions we initially had. We may have to analyse every usage, which is very time consuming.

That being said:
- The stakes are much lower for `private` and unexposed (i.e. no getters) fields since it is only visible to the current class. So don't worry so much about it
- I don't see much difference in making a class `final`...but these people seem to have quite a bit to say: https://stackoverflow.com/questions/218744/good-reasons-to-prohibit-inheritance-in-java

---

On a separate note,

> I think for the future when we add more stuff to the code, if we make it immutable its gonna take a really long time to load it. So I personally jsut did a mutable one

There is a way to make immutable objects "faster" but at the cost of code complexity (since Java does not support it natively). Can take a look at [persistent data structures](https://en.wikipedia.org/wiki/Persistent_data_structure). Clojure is an example of a language that supports it natively.

**Comment by shotnothing** [comment]
> In CS2030 (the version taught by Prof Henry Chia) he advocates for all objects to be made immutable. For eg. if you want to change a `Task` object from being not-done to done, you should return a `new Task` rather than by modifying the boolean attribute tracking the "doneness" of the task. This makes the coding "safer" as there's no risk of accidentally changing the state / value of objects during runtime, but also makes it harder to program as the object changes after each state change (and the new object needs to slot into the place of the old one).

Prof Chia himself says that the extremely strict immutability is only a requirement for teaching purposes, and that in many real-life scenarios complete and absolute immutability is unergonomic, unperformant and possibly even unattainable at the systems level.

**Comment by LimKaiWei** [comment]
Quick question, are we allowed to use code not written by us, specifically I am looking at using `ImList` class from cs2030

**Comment by damithc** [comment]
> Quick question, are we allowed to use code not written by us, specifically I am looking at using `ImList` class from cs2030

@LimKaiWei Yes, provided you follow our reuse policy https://nus-cs2103-ay2425s1.github.io/website/admin/appendixB-policies.html#policy-on-reuse

**Comment by damithc** [comment]
Good discussion everyone.
@zzzlou If you don't have further queries, you can close this issue.
