### ISSUE TITLE
Canvas week 1 quiz: Enumerations

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2103-AY2425S1/forum#17]
why is this false?

My understanding of enumerations is that the values need to be discrete and finite. Though 10000 is a large number, aren't the values discrete and finite?

![image](https://github.com/user-attachments/assets/3fd16ad6-613b-40fa-a59c-a7bb43e6371a)

**Comment by damithc** [comment]
Good topic for discussion @somethingfishyfishy
Let's wait to see if others have opinions on this.

**Comment by ITLimJiaWei** [comment]
@somethingfishyfishy I could be wrong but my understanding of enums is that while they are used for discrete and finite values, the range should be relatively small(e.g. days of the week) as well else one has to define an enumerated name for every integer(0-10000) which isn't very practical.

**Comment by MAOXIONGKAI** [comment]
@somethingfishyfishy My reasonings when answering this question are like these:

1. Even though score of the team is discrete and finite, we may want to perform arithmetic operations on it, such as adding a score when the team wins a game or subtracting the score when the team receives a penalty, which is not supported by the enum type, (and just to add on, enum types are usually used for comparison, switch statements and other non-arithmetic operations) hence representing the team score using enum type variable is not appropriate.

2. Just like what @ITLimJiaWei has mentioned above but I would like to just add on. One of the key reason why we use enum types in our program is to ensure that our users don't enter garbage values into the system which can potentially cause a lot of errors and issues, and it is one of the way that strongly typed languages like java used to limit user input to a finite set of possible options while still ensuring type safety in the system. However, in this case you are just working with very large range of int values where you just need to check about the values and not the types. Therefore, instead of exhaustively declare each int value as a enum type value which greatly compromise the readability and performance of the program, it is better to just use conditional statement to check whether the team's score is within the acceptable range.

Hope that helps.

**Comment by TheRareFox** [comment]
@somethingfishyfishy I think another concern would be performance and memory. Creating an enumeration with 10001 values (0 to 10000) would be extremely inefficient in terms of both memory usage and performance as compared as an if statement that checks if value between 0 and 10000. The extra memory is also not needed because each value from 0 to 10000 serves no other meaning besides representing the integer value, whilst enumeration is best used when each value has a distinct semantic meaning.

**Comment by somethingfishyfishy** [comment]
> 1. Even though score of the team is discrete and finite, we may want to perform arithmetic operations on it, such as adding a score when the team wins a game or subtracting the score when the team receives a penalty, which is not supported by the enum type, (and just to add on, enum types are usually used for comparison, switch statements and other non-arithmetic operations) hence representing the team score using enum type variable is not appropriate.

Good point thanks.

Appreciate all the other responses as well, albeit some are not convincing answers. {10000 can be considered small / inefficiency is not a concern / 10000 distinct values could each have a meaningful significance}
