### ISSUE TITLE
Scanner is unable to scan for user input when run on Gradle

### ISSUE THREAD

**Issue by Arren11111** [nus-cs2103-AY2425S1/forum#172]
Hi, when I run my code through the normal terminal, my code runs without issue, however when executing the run task on Gradle, the scanner used to scan for user input in my code seems unable to scan for the user input. 
<img width="355" alt="Screenshot 2024-09-02 at 8 14 04 AM" src="https://github.com/user-attachments/assets/ba0c30db-1623-45e2-bbea-b5c817c26ca6">
<img width="344" alt="Screenshot 2024-09-02 at 8 14 48 AM" src="https://github.com/user-attachments/assets/2b1d6bb0-5adc-409f-a1fa-2444b3b5b125">

**Comment by damithc** [comment]
@Arren11111 While waiting for others' inputs, you may want to push the latest code to your fork so that others can take a look at the exact code causing this issue.

**Comment by damithc** [comment]
@Arren11111 Let us know when the relevant code is in your fork (also indicate which branch).

**Comment by Dinoman44** [comment]
@Arren11111 You might want to try printing the stack trace upon error using `e.printStackTrace()`. That might help you find the error.

Of the top of my head, it could be because you're missing this line in your `gradle.build` file:
```gradle
run {
    standardInput = System.in
}
```
This makes sure that the standard input is set to the console when using `gradlew run`

Edit: Seems like you do have it. I downloaded your code and it seems to work fine. Is the issue resolved?

**Comment by Arren11111** [comment]
I realise that the code works when I run the "run" task through the CLI, however it does not seem to be able to work by running the "run" task through the GUI. The code can be found in the branch-A-Gradle branch in my fork. Nontheless, since my code works through the CLI, and I am not editing my code using IntelliJ IDE, I will be closing the issue and sticking to the CLI to run gradle tasks. Thank you all for your help!
