### ISSUE TITLE
Edge cases for object diagrams that match class diagrams with no multiplicity indicated

### ISSUE THREAD

**Issue by Ma-Xizi** [nus-cs2103-AY2425S1/forum#174]
Hi! As multiplicity is only optional for class diagrams, I sometimes have qualms determining whether an object diagram matches a class diagram with no multiplicity. To exemplify, I have drawn three diagrams as follows:
![diagram](https://github.com/user-attachments/assets/32f94a6e-9d30-4b70-8a19-9eb67cf51151)

**Q1**While object diagram(c) matches class diagram (b), can we say that the object diagram(c) is compliant with the class diagram (a)?

Also I wish to clarify the meaning of "1..*". **Q2**. Does it mean that every person would have one main, and every main can have any number of persons(including none).
<img width="578" alt="Screenshot 2024-09-02 at 12 16 58 AM" src="https://github.com/user-attachments/assets/0da62e3e-bbc8-40a0-868b-2e6e91d3791b">

**Comment by damithc** [comment]
Good questions @Ma-Xizi 
Let's wait a while to see what others think of this.

**Comment by Ma-Xizi** [comment]
To add on, I have found other multiplicity notations like '2..*'. So I assume for Q2, the answer is that an main object can be linked to 1 or any number(more than 1) of person objects.

**Comment by Ma-Xizi** [comment]
> Good questions @Ma-Xizi Let's wait a while to see what others think of this.

It seems that no one replies to this post 😢

**Comment by Domokunx** [comment]
Hi. Please correct me if I get this wrong :p
Q1) I would say yes? No specific rules are broken from (a) due to the lack of information.

Q2) n...m notation you can think of it as a range from n to m (inclusive). So for the given example:

- Every Main object can have 1 to * (any number) of Person objects. Since the minimum is 1, you can also read this as "1 or more".
- For Person object its not specified, so I don't know if you can just assume it be 1 by default, because you should consider the possibility of setting references to `null`.

**Comment by damithc** [comment]
> Q1) I would say yes? No specific rules are broken from (a) due to the lack of information.

To add, in a question of this nature, we provide enough information so that you _can_ decide the compliance. This example question doesn't have enough information to decide on an answer.

**Comment by Ma-Xizi** [comment]
Thanks everyone!
