### ISSUE TITLE
Clarification on Object diagrams

### ISSUE THREAD

**Issue by Ponharish** [nus-cs2103-AY2425S1/forum#180]
Hi, I would like to clarify my understanding of UML object diagrams.

Is the following object diagram valid? 
The multiplicity of Point class is 4. In the object diagram, i have omitted 2 fields in the diagram.

<img width="295" alt="Screenshot 2024-09-02 at 8 11 44 PM" src="https://github.com/user-attachments/assets/6b5a0204-0166-4141-a228-a5c6b255cadc">

**Comment by Feng1231** [comment]
Not valid.
Square must have 4 points

**Comment by Ponharish** [comment]
But in a different context, would it be fine if I omitted drawing an instance of a field having multiplicity as `* `or `0 ... n` in an object diagram?

And also with respect to the previous example, what if `Square` class had various other fields and we were only interested in 2 specific points, would that make having 2 out of 4 points in the diagram valid?

**Comment by Feng1231** [comment]
Hi, sorry for the late response.

> But in a different context, would it be fine if I omitted drawing an instance of a field having multiplicity as `* `or `0 ... n` in an object diagram?

Yes, thats because * and 0 ... n both includes the case of object A being linked to 0 object B


> And also with respect to the previous example, what if `Square` class had various other fields and we were only interested in 2 specific points, would that make having 2 out of 4 points in the diagram valid?

![image](https://github.com/user-attachments/assets/805306e1-9caf-480f-909d-6e77b8988a1d)
Based on the notes in this week's topic, they only stated that attributes and name of the object can be omitted. 

![image](https://github.com/user-attachments/assets/db511ab0-2a31-46f0-9bf4-8dc826861c2f)
The part on multiplicity also state that if your multiplicity of point is 4, then 1 square must link to 4 points at all times.

**Comment by Ponharish** [comment]
I see. Thank you for explaining

**Comment by damithc** [comment]
@Feng1231 Good answers.
To add, you @Ponharish it also depends on context and purpose. For example, can show only two points if it is made clear that it is only a partial diagram showing only the objects of interest.

**Comment by Ponharish** [comment]
Thank you prof
