### ISSUE TITLE
Canvas Quiz 3: qn on wrapping

### ISSUE THREAD

**Issue by somethingfishyfishy** [nus-cs2103-AY2425S1/forum#186]
Isn't the 2 code blocks the same? Is my understanding of this question incorrect? I dont understand why the answer is false. please explain
`totalSum = a + b + c
        + d + e;`

![image](https://github.com/user-attachments/assets/a9ad9f66-e652-4206-9a03-53fd7c955710)
![image](https://github.com/user-attachments/assets/66343ac3-e9db-43d3-9af4-28bc931f9675)

**Comment by Gra7ityIC3** [comment]
It should be **8 spaces** instead of the usual **4 spaces**, as stated [here](https://se-education.org/guides/conventions/java/index.html#layout):

> **Indentation for wrapped lines should be 8 spaces** (i.e. twice the normal indentation of 4 spaces) more than the parent line.

**Comment by Dinoman44** [comment]
The questions uses tabs for indentation, but you are supposed to use spaces.

**Comment by yadobler** [comment]
Such a trick question!

But to be honest, the question itself looks like 4-space tabs are being used. I think that's the confusion. 

---
Also sure if you're using checkstyle from Google or ide defaults, to change:
1. Indentation tab from 2 -> 4
2. No indentation for "case" statements

Because Google standards, and ~~"nulls are a billion dollar mistake" mod~~ CS2030S use 2-space tabs and indented case statements.

Import statement order is also a bit different. Make sure it's static > java > javafx > org > com > samepackage

**Comment by somethingfishyfishy** [comment]
> The questions uses tabs for indentation, but you are supposed to use spaces.

> It should be **8 spaces** instead of the usual **4 spaces**, as stated [here](https://se-education.org/guides/conventions/java/index.html#layout):
> 
> > **Indentation for wrapped lines should be 8 spaces** (i.e. twice the normal indentation of 4 spaces) more than the parent line.


If you highlight the code there, it is using spaces. Go to Canvas and try for yourself

I completely understand that its not the **'\t'** char but **' '** char that is the standard, that which I agree with. Would like to highlight that it is possible by configuration of your IDE / editor, that the tab key's output can be changed to 4-spaces, hence easily misunderstood to be equivalent. I think the semantics of this question ought to be clearer.

**Comment by damithc** [comment]
> Such a trick question!

Yup, it's meant to be a trick question, so that it sticks in memory :-)

The statement says something like 'one should choose X over Y' (as if only one of them is correct) when the expected correct reaction is "wait, isn't both X and Y are wrong?". So there is a bit of a misdirection.

> But to be honest, the question itself looks like 4-space tabs are being used. I think that's the confusion.

The code example is given to illustrate what _line wrapping_ is, as the reader might not know the meaning of the term. The question doesn't ask if the code example is following the coding standard (as it is impossible to tell whether tabs or spaces have been used by looking at this code anyway).


**A key point is, tabs and 4-spaces may look the same in one one tool but the exact same thing will look different in another tool.** For example, a tab is shown a 4-spaces in Intellij (giving the impression that they are the same) but a tab is shown as 8 spaces in GitHub UI. So, if you mix tabs and spaces, things will look aligned in Intellij, but misaligned when viewed in GitHub UI.
So, it is important that one wraps lines using spaces or tabs but not a mix. As per our coding standard, it should be spaces. If you still wish to type tabs (after all, it requires fewer key strokes compared to 4 spaces), you can simply configure Intellij to auto-convert tabs to 4 spaces (or whichever number of spaces you want it to be).
