### ISSUE TITLE
Is it absolutely necessary to do parallel branches for W3 step 5?

### ISSUE THREAD

**Issue by weiseng18** [nus-cs2103-AY2425S1/forum#191]
![image](https://github.com/user-attachments/assets/acc3e2f2-2f02-421a-b6d6-1e4b6dd2cc5d)

I understand that working with parallel branches can lead to merge conflicts, and I see the value in practicing how to resolve them.

However, I have dealt with merge conflicts before, so if possible I would not like to purposely introduce merge conflicts for practice, so I'm asking if I can do these branches one by one in sequential order.

**Comment by damithc** [comment]
> ... so if possible I would not like to purposely introduce merge conflicts for practice, ...

@weiseng18 With more practice, you can become less averse to dealing with them 😁 
Not to worry, parallel branches don't always cause merge conflicts, and most merge conflicts are not hard to resolve.

> I'm asking if I can do these branches one by one in sequential order

It's best if you do parallel branches here, and as much as possible in the team project later. It's something we want all students to be able to do comfortably by the end of the semester -- this is just the start. 

That said, you _can_ do some of the A-Javadoc and A-CodingStandard work before you start the parallel branches so that the amount of changes in each parallel branch is less, and the resulting merge conflicts are fewer/milder.

**Comment by weiseng18** [comment]
Hi Prof, thanks for the quick reply!

Fair point! More practice does build confidence...

I'll opt to start some of the Javadoc and coding standard work before the parallel branches in that case. Thank you!
