### ISSUE TITLE
GUI works when using ./gradlew run but not using IntelliJ's play button

### ISSUE THREAD

**Issue by marchjlim** [nus-cs2103-AY2425S1/forum#206]
Hi, I was able to set up my GUI a few days ago and run it just fine on IntelliJ.

However, I did some commits which added JavaDocs to my codebase and now it doesn't work when I run my Main class on IntelliJ. It only works I do ./gradlew run on the terminal. 

I have reverted my local copy to the commit in which it was previously working before, and I am still encountering the same issue. I'm puzzled because I did not edit anything in my codebase and my dependencies are the same, so I can't understand why it gives me the error that my JavaFX components are missing since the code is exactly the same and no dependencies have been changed.

Below is an attached screenshot of running my Main class with --stacktrace. 

![image](https://github.com/user-attachments/assets/ba19c51c-7d8a-4175-995d-4bf11af08d21)

Below is the output when I do ./gradlew run. I am getting a warning but otherwise my GUI works perfectly fine.

![image](https://github.com/user-attachments/assets/ec8fc49d-0a42-4885-8a7a-b8a8c13a9d7a)

**Comment by rahula1008** [comment]
Hi @marchjlim 

This problem could be related to how IntelliJ is handling the project configuration as opposed to the code. 

1. Try `./gradlew clean build run`. And additionally try restarting your IDE for good measure. 
2. Try resetting Intellij's cache: **File** -> **Invalidate Caches / Restart**
3. Go to your settings, go to **Build, Execution, and Deployment** -> **Build tools** -> **Gradle** and make sure that the build and run, and run tests are set to Gradle, and have not accidentally changed when you changed your commit. 

Another thing, when you say, 'run it on intellij', can I just confirm that you are using one of the methods mentioned [here?](https://www.youtube.com/watch?v=6V6G3RyxEMk#t=13m44s) (i.e using the gradle window). 
Because if you are using the standard green run button, you might need to edit your Run configurations, by going to the drop down menu besides the run button, clicking **Edit configurations ... **, and look for the run configuration for the Main class. Click on it, and make sure that it points to the correct class. 

EDIT: Just a small note for point 3, in the same **Build tools** window, also just check that your Gradle JVM is set to the same version that you are using in terminal. (I got this tip from Issue #189, as recommended by @damithc in the subsequent comment)

**Comment by damithc** [comment]
Good pointers @rahula1008 
@marchjlim Possibly similar issue https://github.com/nus-cs2103-AY2425S1/forum/issues/189

**Comment by marchjlim** [comment]
I have figured out the problem was that I was using the Main.java file to run the program instead of Launcher.java.

Thank you @rahula1008 and prof @damithc for the inputs and helpful advice!
