### ISSUE TITLE
my branch-Level-10 is not detected but Level-10 tag in the branch is detected, I can also find the branch on my github

### ISSUE THREAD

**Issue by lancehaha** [nus-cs2103-AY2425S1/forum#214]
I pushed my Level-10 tag commit and the branch-Level-10 at the same time but on the dashboard seems like the branch-Level-10 is not detected even though I can find that on my own github
<img width="765" alt="image" src="https://github.com/user-attachments/assets/d901b4f0-a777-4ee8-b28c-ca7ddcfa696a">
<img width="864" alt="image" src="https://github.com/user-attachments/assets/e5893afc-f922-4177-8550-a72c93926d96">

**Comment by damithc** [comment]
@lancehaha Ping me again if it still doesn't appear after the next dashboard update.

**Comment by charlenetcy** [comment]
@damithc I also pushed my branch, commit and tag for JavaDoc but the tag was not detected on the dashboard.
<img width="616" alt="Screenshot 2024-09-11 at 9 17 24 PM" src="https://github.com/user-attachments/assets/96d52afd-f804-4260-8a1f-f3912190d9c0">
<img width="808" alt="Screenshot 2024-09-11 at 9 18 36 PM" src="https://github.com/user-attachments/assets/42b8966a-a6d9-427e-b0dd-daa2139f379f">

**Comment by damithc** [comment]
@charlenetcy Not to worry. We should be able to figure this out and rectify in due course.

At the top of the [iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html), there are a couple of tips about troubleshooting when an increment related to a tag or a branch is not green as expected. See if those help you locate the problem.

If the problem remains unresolved even after trying the above, let us know.

BTW, it is best to open a new issue for each problem rather than hijack existing thread started by someone else (so that the thread can be closed once the issue is solved).

**Comment by estellelim** [comment]
I am also facing the same problem; my branch-Level-10 is not detected.

<img width="771" alt="image" src="https://github.com/user-attachments/assets/a3905947-91c6-44d7-a459-34b4fb645a65">
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/915a7337-bdae-4f0c-abb2-32ffb038bcf1">

**Comment by damithc** [comment]
> I am also facing the same problem; my branch-Level-10 is not detected.

@estellelim Last time we pulled from your fork, your `master` branch was not updated (most likely you pushed the `master` branch after the last dashboard update). You can check again after the next dashboard update.



> BTW, it is best to open a new issue for each problem rather than hijack existing thread started by someone else (so that the thread can be closed once the issue is solved).

This applies here as well.
