### ISSUE TITLE
Possible ways to use Enum

### ISSUE THREAD

**Issue by matchastack** [nus-cs2103-AY2425S1/forum#22]
Hi, I am currently doing week 2's ip tasks and have completed up to Level-6 but is struggling to see where Enums can be utilised. Would greatly appreciate any tips and advice!

**Comment by damithc** [comment]
@liauzhanyi Good point for discussion. Let's see if others have any thoughts on this.

**Comment by anselmlong** [comment]
Hello! I was thinking to use enums for the commands that will be used for the chatbot, since they are constants? With these enums, I can put them in my switch-case statement instead of the plain text.

**Comment by itsme-zeix** [comment]
My first thought was to use enums as a way to manage logic flow for commands (`mark`, `unmark`, `todo`, etc.) and to handle the corresponding message for the Exception class. The use of switch-case rather than a huge chunk of if-else statements is a lot more readable imo!

**Comment by cth06-Github** [comment]
Same here, I was thinking to use enum for the commands but Iater on I disagreed or something is missing because the command we type into the input is in String type, and there may be additional steps to check for correspondence between the enum type and String type?  We can do switch-case statement with string commands and have a default case to throw an exception, something like:

```
case "list":
    // whatever code logic
case "todo":
  // whatever code logic
default:
  // throw exception to show that command has been keyed in wrongly
```
which seems simpler than involving enum.
(so based on that thinking, I am also not sure how we can use enums as well)

**Comment by anselmlong** [comment]
I tried something like:
`
String command = split[0].toUpperCase(); // Convert input to uppercase to match enum
Commands cmd;
                try {
                    cmd = Commands.valueOf(command); // Convert to Commands enum`

Then, having a switch on cmd allows you to have different cases based on the value of command.

**Comment by MAOXIONGKAI** [comment]
I agree with @cth06-Github 's opinion that using enum for recognizing command type introduces redundant logics within the program. I am also a bit confused about the possible use of enums within the current scope of the project, but if more customization is allowed at this stage of project development, I believe we can use enum to specify status of the task(just like all these other task management outside, we can have more status than just done & not done, such as cancelled) and the priority of the task(low, medium, high etc.), because they both represents finite and discrete sets of values which we want the user to choose from.

**Comment by matchastack** [comment]
Thanks everyone for your inputs! 

My initial thoughts was similar to what @cth06-Github had mentioned, to use Enums for commands however, it seemed unnecessary and makes the code more convoluted (at least in my opinion). Hence, I was wondering if the fact that I had difficulty seeing how Enums can be incorporated is due to bad code design on my part. 

@MAOXIONGKAI I think what you suggested makes a lot of sense, especially the part about statuses which might be relevant even for increments up till week 2. Thanks a lot!

**Comment by damithc** [comment]
Good to see you all pitching into this discussion @liauzhanyi @MAOXIONGKAI @anselmlong @cth06-Github @itsme-zeix 
To add to the discussion, being able to use enums is useful but knowing when to use them is even more useful. So, this discussion is a very valuable training, irrespective of whether you end up using enums in the iP.
Also, don't be afraid to just try in your code any of the alternatives you think is worth a try. You can always change it later if it didn't turn out as well as you thought. That way, yet gain more experience, and your knowledge becomes more concrete (rather than based only on speculation or others' opinions).

**Comment by damithc** [comment]
> but if more customization is allowed at this stage of project development, I believe we can use enum to specify status of the task(just like all these other task management outside, we can have more status than just done & not done, such as cancelled) and the priority of the task(low, medium, high etc.), because they both represents finite and discrete sets of values which we want the user to choose from.

@MAOXIONGKAI You are welcome to add more features to the iP, beyond the given requirements.

**Comment by WinstonJin** [comment]
enum Commands {
        TODO, DEADLINE, EVENT, LIST, DELETE, BYE, MARK, UNMARK, UNKNOWN
}

This is what I did for enums

**Comment by joeltio** [comment]
I think that enums offer two main possible benefits:
1. Slight speed increase (as we will learn/have learned in CS2100)
2. Type checking for constants

I agree with @cth06-Github that currently there is no need to use enums for the commands. Currently, there is only one usage of such an enum. For example, if we had an enum like WinstonJin has mentioned:

```java
enum Commands {
    TODO("todo"),
    DEADLINE("deadline"),
    // ...
}
```

The rest of our codebase will only use this enum once: when we are parsing the first word from the user's input and checking what to do:
```java
switch (Commands.valueOf(input)) {
    case Commands.TODO:
        // run todo
        break;
    // ...
}
```

Since it is only used once, there is no point in separating it into another enum. We should make an enum only if there is somewhere else in our code where we need to use the `Commands` enum. This way, we can leverage on the type checking the compiler does to ensure both values are the same.

**Comment by yadobler** [comment]
If you want to use `Commands` as enum, then use a hashmap `string -> Commands`. If it's static final, then it's allocated once and O(1) effectively. Your switch case can take the value returned by the hashmap.

I am pretty sure that the efficiency of switch cases are in that the input is directly used to jump to an offset on the table (that's why we need to break out of the table at end of each case), through `tableswitch` JVM opcode. Whereas with strings it will just run a `tablelookup` JVM opcode to run a optimised `.equals()` for every case until hit. 

I argue that: 

> String -> Hash -> Hashmap<String, Commands> -> Commands -> switch(Commands) -> jump to case

is faster and more efficient than

> String -> `tablelookup` of O(n) -> jump to case

---

I also argue that it is easier to maintain because you can simply edit the text the user needs to input to run the command:

```java
// Commands is enum
HashMap<String, Commands> commandsMap = new HashMap<>();
commandsMap.put("list", Commands.LIST);
commandsMap.put("delete", Commands.DELETE);

...
// input is String
switch(commandsMap.get(input.lowerCase())) {
case Commands.LIST:
   < Many lines of logic >
   ....
   ....
case Commands.DELETE:
  < More more LoC>
   ....
   ....
}
```

Suppose tomorrow we gonna **i18n** to worldwide.
We will not want to *manually edit each and every single switch case*!!!

we can simply do this:

```java
// Commands is enum
HashMap<String, Commands> commandsMap = new HashMap<>();

// english
commandsMap.put("list", Commands.LIST);
commandsMap.put("delete", Commands.DELETE);
// tamil
commandsMap.put("பட்டியலிடுகவும்", Commands.LIST);
commandsMap.put("அழிக்கவும்", Commands.DELETE);
// mandarin
commandsMap.put("列印", Commands.LIST);
commandsMap.put("删除", Commands.DELETE);
```

and you never need to touch the switch case ever again.

**Comment by damithc** [comment]
Good discussion, everyone.
@liauzhanyi If you don't have any further queries, we can close this issue now.
