### ISSUE TITLE
Week 4 Notes vs Webinar Content: UML Diagrams model structure and/or behaviour of solution

### ISSUE THREAD

**Issue by kimxw** [nus-cs2103-AY2425S1/forum#222]
### Notes and Webinar content seems different
Notes say that UML class diagrams describe the structure (but not the behavior) of an OOP solution.
![image](https://github.com/user-attachments/assets/66e176f4-0e9c-49b8-b2ba-32a5e95158f6)

Webinar says that "UML diagrams can model both structure and behaviour of the project" at 00:35:08
![image](https://github.com/user-attachments/assets/d905ec6b-2a0f-43f4-84d1-357d819d7d4d)

Am I misunderstanding?

**Comment by MAOXIONGKAI** [comment]
Sorry if I misinterpret this, but I believe that the notes and the webinar is talking about different things. You can refer to the diagram included in the textbook as part of my reasoning:
![image](https://github.com/user-attachments/assets/71c1a844-6326-4da7-a9f0-94fb5121c42f)

Note mentions **UML class diagram** which is only about the class diagram and it is true that it shows shows the structure and not the behavior because the diagram only shows the associations between the classes and nothing else.

Webinar, on the other hand, mentions **UML diagram** which can consists of may different kinds of diagram and some of them such as state machine diagram and user case diagram can be used to model behaviors of the program.

Hence, in my opinion, there's no discrepancy between the above contents. Hope that helps with the issue, some please correct me if I am wrong thank you

**Comment by damithc** [comment]
@MAOXIONGKAI thanks for the clarification. Yes, you are correct.
