### ISSUE TITLE
TEAMMATES Submission Enquiries

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#230]
![image](https://github.com/user-attachments/assets/74f162dd-26c8-4c36-b403-de364696bc35)

Dear Professor and Course Mates,
I would like to ask where can I find the link to submit.

I have not received any link from TEAMMATES.

Your help is greatly appreciated. Thanks, Brendan

**Comment by damithc** [comment]
@Brendan8899 you can go to https://teammatesv4.appspot.com/web/front/help/session-links-recovery and enter your NUSNET email address to get TEAMMATES to resent the submission link.

**Comment by chenle228** [comment]
Morning prof @damithc ! I have asked TEAMMATES to resend my submission link, but the resent link seems to be related to Product Concept rather than Peer Evaluation.
<img width="752" alt="031410772094e2ef0c0d4260fa5daeb" src="https://github.com/user-attachments/assets/3e26626a-0e75-4e1d-abb1-2cafd457b2d6">
Is there an alternative way to get the submission link for Peer Evaluation from TEAMMATES?

**Comment by damithc** [comment]
@chenle228 Sorry, I created the session just now. You should receive the submission link within the next hour. You should also be able to retrieve it now using the above method.

**Comment by Brendan8899** [comment]
Okay will proceed to close issue!
