### ISSUE TITLE
Are magic literals like these acceptable?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#235]
I have some magic literals in the subclasses of `Task`. For example, this are the two String methods in my `Deadline` class.

```java
/**
     * Returns a string representation of the task in a format suitable for file storage.
     * The format is "D | [TaskFormat] | yyyy-MM-dd HHmm".
     *
     * @return A string representation of the task in file format.
     */
    @Override
    public String toFileFormat() {
        return "D | " + super.toFileFormat() + " | " + getFileDateString(by);
    }

    /**
     * Returns a string representation of the task in a user-friendly format.
     * The format is "[D][TaskStatus](by: MMM dd yyyy HH:mm)".
     *
     * @return A string representation of the task.
     */
    @Override
    public String toString() {
        return "[D]" + super.toString()
                + "(by: " + getDisplayDateString(by) + ")";
    }
```

Are magic literals acceptable here? I really don't find the meaning of defining constants here. Or could someone enlighten me how defining constants here could be useful in the future.

**Comment by Quasant** [comment]
There is a similar discussion linked [here](https://github.com/nus-cs2103-AY2425S1/forum/issues/208). 

For the IP, I also believe that there is no point to defining a static variable for the task type, especially when it is used in 2 isolated methods and nowhere else. Perhaps within the javadocs remark that D is the short-form for Deadline so that people who are not familiar with this IP can understand what it means. 

On the flip-side, suppose that you want to change the format from "D" to "Deadline", you have to replace these 2 instances of the magic literal, which is doable. However, if we scale up the project more and have multiple instances of the task type utilized across the code-base, having a constant declared lets you change all these instances from one place.

**Comment by Feng1231** [comment]
> There is a similar discussion linked https://github.com/nus-cs2103-AY2425S1/forum/issues/208

Thanks, I did not catch that at first

> Perhaps within the javadocs remark that D is the short-form for Deadline so that people who are not familiar with this IP can understand what it means.

That is a good point, thanks!

**Comment by Jianwen0451** [comment]
The main problem i think with magical literal is poor readabilily.
So I think it is ok if the literals are self-explanatory.
Here is part of my code
```java
public String execute() {
        if (taskList.size() < index || index <= 0) {
            return printMessages("Sorry~ Can not delete this task as such task does not exist.");
        } else {
            Task task = taskList.remove(modify(index));
            storage.updateFile(taskList);
            return printMessages(new String[]{"OK~. I've deleted this task:", task.toString(),
                    String.format("Now you have %s tasks in the list", taskList.size())});
        }
    }
```
Although some strings may seem magical. But I think it is ok to leave it like that since readers are able to understand the meaning of these codes.

**Comment by Feng1231** [comment]
Thanks all!
