### ISSUE TITLE
git error

### ISSUE THREAD

**Issue by obrona** [nus-cs2103-AY2425S1/forum#241]
sometimes when I do git push origin master I get 
```
error: src refspec master does not match any
error: failed to push some refs to 'https://github.com/obrona/<repo_name>.git'
```
How do I resolve this error ?. Checking online says that the most likely cause is that the remote repo does not have branch you are pushing too, in this case master, but I can confirm that my repo has branch master.

**Comment by obrona** [comment]
I have solved the problem. It was because my local branch name is main and not master

**Comment by obrona** [comment]
Now, I get
```
Your branch is based on 'origin/main', but the upstream is gone.
  (use "git branch --unset-upstream" to fixup)
```
What does this mean ?

**Comment by ChinSekYi** [comment]
I think it's because your current branch is set to track origin/main, but origin/main has been removed or is no longer available on the remote.
Hence, if you would like to reset the tracking, git is suggesting you to `git branch --unset-upstream`.

One hint is to check the branches that exist on the remote first:
`
git branch -r
`

**Comment by damithc** [comment]
@obrona Was the issue resolved?

**Comment by obrona** [comment]
Yes thank you all
