### ISSUE TITLE
Want to rewrite my codebase

### ISSUE THREAD

**Issue by weiseng18** [nus-cs2103-AY2425S1/forum#244]
After understanding what I need to interface with the GUI, I've come to the conclusion that my current codebase needs quite a bit of refactoring.

I could definitely do smaller refactoring tasks that slowly bring my codebase to an ideal state, but now that I know what I want exactly, I think a rewrite is much faster.

Am I allowed to rewrite the codebase from scratch?

**Comment by yadobler** [comment]
> After understanding what I need to interface with the GUI, I've come to the conclusion that my current codebase needs quite a bit of refactoring.

If it's to do with the main loop depending on `Scanner` blocking until input is available, you can get around with:

<details> <summary> what i did basically </summary>

1. extracting that `hasNext()` into an abstract method in `Ui` interface
2. have 2 different classes implement `Ui`, with the *cli* version's `hasNext` `running scanner.hasNext()`
3. **Cry** for awhile realising you need to implement some concurrency stream implementation for GUI (**This is important** because you know you should not exert too much effort into this but you can't help it)
4. Make your UiGui implementation of `Ui` hold a buffer of input and outputs. Basically instead of `System.out.println` going to `STDOUT` and scanner reading from `STDIN`, implement a _blocking_ function to busy wait until the input buffer / output buffer is not empty anymore and return true (or return false when your bot has ended, indicating a _closed stream_)
5. Run your bot in a new `Thread` so that it will concurrently pull from `UiGui`-IN and push to `UiGui`-OUT
6. Run another loop in your `MainWindow` (probably in the init method) class to run a new `Thread` to repeatably check if the Output buffer is not empty, and then _print_ it out as the bot's dialogbox

</details>

**tl;dr**
1. encapsulate Ui to be an interface doing the STDIN/OUT/ERR. Cli implementation can use normal System.out and System.in
2. Run your bot in a new thread so that it can _busy wait_ for _Input_
3. Run a seperate thread in your GUI application to _busy wait_ for _Output_ and **signal the main app to add new `DialogBox`s when output availabe (ie bot replies)**

Some caveats:
- <details> <summary> JavaFX updates must happen on the JavaFX line. </summary> Use `Platform.runLater(updateMethod)` to run a `updateMethod()` that does the `Ui.StdOut->DialogBox->Add to scene` </details>
- <details> <summary> I had to use a flag to add a guard clause in my update method. </summary> Idk why even though I only execute the `runLater` when the busyloop continues, it still gets stuck afterwards. _I think `Platform.runLater` might be executed once, so the new thread only needs to update the flag and not call it again. I will need to try this._ </details>
- Your program will be a bit slower on startup.

Why I did it this way:
- My bot says hello before the user inputs, so I don't want to have edge cases to handle with beginning and replying only when user inputs. Very messy.
- I am programmer. of course I will waste hours automating something that can be hacked away in minutes
- My CLI still works. [Run my .jar](https://github.com/yadobler/ip/releases/tag/Level-10) with `-c` flag to use CLI instead of GUI. This means my `Text-ui-test` still works, so **regression testing still works**
- I dont have to touch my main bot class anymore. All logic remains same. If tomorrow @damithc says the bot needs to run on brain with the input coming from my thought and output injected to my eyes, i just need a new `UiBrain implements Ui` class and add a new method to my `Launcher` static class to create the appropriate Objects for the bot.

---

- [My `UpdateMethod` method](https://github.com/yadobler/ip/blob/38cc4e82b0e247d5e5db9a2c44d369cb5299718f/src/main/java/yappingbot/ui/gui/MainWindow.java#L63C3-L76C1)
- [The new thread inside the GUI application](https://github.com/yadobler/ip/blob/38cc4e82b0e247d5e5db9a2c44d369cb5299718f/src/main/java/yappingbot/ui/gui/MainWindow.java#L44-L49)
- [The new thread running my bot, including disabling the GUI once the bot exits and returns](https://github.com/yadobler/ip/blob/38cc4e82b0e247d5e5db9a2c44d369cb5299718f/src/main/java/yappingbot/ui/gui/MainGuiApplication.java#L45-L50)

---

**If it is not, then ignore this.**

**Comment by damithc** [comment]
> Am I allowed to rewrite the codebase from scratch?

@weiseng18 In the iP, this is allowed (but not in the tP).

**Comment by weiseng18** [comment]
thanks prof!
