### ISSUE TITLE
RepoSense Not Tracking my Progress

### ISSUE THREAD

**Issue by Brendan8899** [nus-cs2103-AY2425S1/forum#25]
![image](https://github.com/user-attachments/assets/c8f8226a-a6e5-4c15-9b92-4cc3dc0dbf1e)
Hi Prof and Fellow Coursemates,

I have dutifully tagged my commits with the appropriate tags to indicate the Task Level but the Progress Tracker on CS2103 is not working.

![image](https://github.com/user-attachments/assets/7a6d521f-9b59-4d77-b97c-1055aa4b5abc)

Has anyone faced similar issue?

**Comment by damithc** [comment]
@Brendan8899 There are some troubleshooting tips at the top of https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html

In your case, I suspect your tags were created _after_ the last update to the dashboard. So, you can wait till the next update and check again.

**Comment by tohhengxing** [comment]
> @Brendan8899 There are some troubleshooting tips at the top of https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html
> 
> In your case, I suspect your tags were created _after_ the last update to the dashboard. So, you can wait till the next update and check again.

@damithc Could you share what is the frequency of the job? Would there be any additional considerations to running the job more frequently?

Edit: I read some the [reposense](https://reposense.org/index.html) documentation, seems like this is a program looks at all the public forks to generate a report and the dashboard repo triggers a job that runs this report generator and deploys it to the webpage. Is there rate limiting going on that prevents more frequent deploys?

**Comment by damithc** [comment]
> @damithc Could you share what is the frequency of the job? Would there be any additional considerations to running the job more frequently?
> 
> Edit: I read some the [reposense](https://reposense.org/index.html) documentation, seems like this is a program looks at all the public forks to generate a report and the dashboard repo triggers a job that runs this report generator and deploys it to the webpage. Is there rate limiting going on that prevents more frequent deploys?

@tohhengxing 
[iP progress dashboard](https://nus-cs2103-ay2425s1.github.io/dashboards/contents/ip-progress.html) is not using RepoSense. It is generated by a whole lot of custom code, pulling in data from various sources, some of which are access-restricted data sources.  It is currently generated in my computer. So, I run it about once a day during times I'm not doing other work on my computer.
[iP code dashboard](https://nus-cs2103-ay2425s1.github.io/ip-dashboard/?search=&sort=groupTitle&sortWithin=title&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=true&checkedFileTypes=java~md~fxml~sh~bat~gradle~txt) is generated using RepoSense and the generation happens on GitHub Actions. You are right that its frequency can be increased but we only update it a couple of times a day because there is a monthly limit to how many GitHub Actions minutes we can use.

**Comment by Brendan8899** [comment]
Thank you prof
