### ISSUE TITLE
Accidentally created a branch off another branch instead of master

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#251]
While doing this week's iP task. I seem to have accidentally created another branch off another branch. This led to this outcome which does not seem to match the ones shown in the project task:
<img width="527" alt="image" src="https://github.com/user-attachments/assets/cdc965ca-4d7a-4991-bf1e-b5fa8f5ba67b">

Based on the picture it seems like I created branch-A-Assertions off of branch-A-CodeQuality but checking my git bash history, it seems to be the other way round:
<img width="253" alt="image" src="https://github.com/user-attachments/assets/acb06e1c-0a81-491b-9bc9-bdb6393539f3">

(ignore branch-A-Streams because I deleted it)
What is the appropriate way to fix this issue given that I have already pushed some of the branches into my remote repo?

**Comment by damithc** [comment]
@vinceg4 You are encouraged to try to fix it but it's not _required_. Just be more careful in future, as this is a common branching mistake.

**Comment by GabrielCWT** [comment]
Normally I would not recommend trying to fix it since it is pushed upstream. (Other people might be working on it)
But since this repo is just for you. 
1. Reset `branch-A-CodeQuality`'s `HEAD` by 1 (Undo merge of `master`)
2. Reset `master`'s `HEAD` by 2 (Undo merge of `branch-A-CodeQuality` and `branch-A-Assertions` into `master`)
3. Rebase `branch-A-Assertions` to the commit with tag `A-Checkstyle` (Makes the 2 branches parallel)
4. Merge the 2 branches into `master` 
5. Force push
