### ISSUE TITLE
Warnings when running GitHub workflow

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#256]
Hello, I followed the instructions for this week's [A-CI increment](https://nus-cs2103-ay2425s1.github.io/website/schedule/week5/project.html#a-ci) by downloading [this .yml file](https://github.com/se-edu/duke/blob/full-template/.github/workflows/gradle.yml) into my repo.

When I checked my Actions tab after pushing some commits to my master branch, I realised that warnings are thrown. Do I need to fix these?
![image](https://github.com/user-attachments/assets/9e63dc34-bc7f-4cdc-9499-afd65b9a2e23)

**Comment by damithc** [comment]
@Feng1231 For now, you can let it be (no need to fix), while we wait to hear what others think about it.

**Comment by itsme-zeix** [comment]
It seems that the warnings are due to the runners using outdated Node.js versions, rather than an issue with your code itself. Since the workflows are working fine, I'm pretty sure the warnings can be ignored.

However, if the warnings bothers you, you can avoid them by upgrading the versions in the `.yml` file:
1) [Upgrade gradle/wrapper-validation-action  to gradle/actions/wrapper-validation@v4](https://github.com/gradle/wrapper-validation-action?tab=readme-ov-file)
2) [Upgrade setup-java to v2](https://github.com/actions/setup-java/blob/main/docs/switching-to-v2.md)

It should look something like this? (Copy at your own risk, untested)
```diff
 - name: Validate Gradle Wrapper
-  uses: gradle/wrapper-validation-action@v3
+  uses: gradle/actions/wrapper-validation@v4

 - name: Setup JDK 17
-  uses: actions/setup-java@v1
+  uses: actions/setup-java@v2
   with:
+    distribution: 'zulu'
     java-version: '17'
     java-package: jdk+fx
```

**Comment by Feng1231** [comment]
I see! Thanks for helping. :)
