### ISSUE TITLE
Clarification about Magical literal

### ISSUE THREAD

**Issue by Jianwen0451** [nus-cs2103-AY2425S1/forum#260]
```java
@Override
    public String execute() {
        list.sort();
        storage.updateFile(list);
        return Ui.printListWithMessages(list,
                "I have sorted the list for you~ ^_^\nThis is your new task list.");
    }
}
```
This is part of my code. Does the string of "I have sorted the list for you~ ^_^\nThis is your new task list." considering a magical literal or is fine to leave it like that since it is self-explainary?

**Comment by matthewyip1511** [comment]
I would consider this a magical literal as it is not too clear what context in which this message is sent. Especially since the method is `execute` and not `sort`, is it not _too_ self-explanatory that this method should sort and print out a corresponding message. 

The way I would think of it is this - if I were to write this in a company and later leave the company, the next person working on the codebase should understand what to put there and change the message if necessary should the `execute` function change in its output / functionality later 🙂 

Though, happy to hear what others might think of this!

**Comment by Jianwen0451** [comment]
Your argument is reasonable. A bit more context here. Actually, the class name is called "SortCommand" and it extends from an abstract class called "Command". The execute would be to execute the command. This execute function should always do only sort the list and tell the user that the list is sorted. If I want to do other actions, I will creat a new command class. So I think it is self-explanatory.

**Comment by RadieonAjax** [comment]
I think you can leave it as it is, as I won't consider that to be a magic literal. Magic literals (or strings) are defined as those whose meaning could not be understood without any additional context. 

In this case, the string: `I have sorted the list for you~ ^_^\nThis is your new task list.` is quite self-explanatory as an output string, and anyone reading it will understand without prior context. Nonetheless, it doesn't hurt to declare it as a constant, and passing the constant as the parameter. 😄

**Comment by zaidansani** [comment]
Agreed with my favourite homie above @RadieonAjax, but perhaps a benefit that could be had by having it as a constant is if you can put all your constants with regards to UI messages together, you can easily change them in the future, since all of them are in one place, and it's easy to find where the message is.

**Comment by Jianwen0451** [comment]
Thanks for your advice. I think I will change these if there are necessary changes in the future.
