### ISSUE TITLE
data stored in list disappears after some time?

### ISSUE THREAD

**Issue by miuna9890** [nus-cs2103-AY2425S1/forum#270]
Im not sure why but when i run my app a few times, i am able to view all the tasks in my list even after i close it. 
But when i try sometime later, there is nothing in my task list. Not sure why the loading of tasks only works sometimes.

**Comment by damithc** [comment]
@miuna9890 while waiting for inputs from others, something you can do is to create a JAR file of your project, put it in a separate folder outside of the project folder, and see if you can replicate the problem using that JAR file. This will help you determine if the problem is caused by something in the dev environment (e.g., affected by a Gradle task that you run sometimes) or caused by something in the code itself.

**Comment by verakohh** [comment]
I think you can try checking if you have multiple data files in your directory that might store two different task lists. As in the image below, the correct data file should be under the `ip/data` folder and not `ip/src/main/java/cleo/data`. I'm not sure how i got he second data folder before but this could be a possibility!

<img width="277" alt="image" src="https://github.com/user-attachments/assets/6ae5d7a2-8d95-4431-a8e7-fc058f7c5ad1">

**Comment by MAOXIONGKAI** [comment]
Hi, would it be ok if you share some detail about how you implemented the save/load task feature in your program, since the issues may lie within its implementation. Also, would appreciate if there can be more detailed description on what are the exact steps to take to replicate this issue, thank you.

**Comment by Domokunx** [comment]
@miuna9890 
![image](https://github.com/user-attachments/assets/0791c918-fc46-4b77-bd69-bbfb01768997)
I noticed in your Storage class you have this "return empty list on failure" when trying to load tasks. 
It might be possible that "corrupted/invalid" files end up getting wiped completely. Maybe tinker around that part of the logic to see if anything gets better?

**Comment by miuna9890** [comment]
I am unable to replicate the issue again and not sure why it occurred the last time:(( So i am not sure if it has been rectified, but I will keep the suggestions @Domokunx @verakohh @MAOXIONGKAI in mind if I happen to face the issue again. Thank youuu.

**Comment by yadobler** [comment]
Like what @verakohh said, probably if you run using Gradle your relative path `./data/flash.txt`will be from the root, while running via IntelliJ will retrieve the file from **current working directory**

Notoriously, if you're using `java -jar` from inside the `build/libs` folder then it will not find the file `build/libs/data/flash.txt`
