### ISSUE TITLE
Editing previous commit messages

### ISSUE THREAD

**Issue by niclammm** [nus-cs2103-AY2425S1/forum#276]
Hi guys, does anybody know how to edit previous commit messages on Sourcetree?

**Comment by yadobler** [comment]
Is CLI ok?

You can use
1. For last commit you can use: `git commit --ammend`
2. Add `-m` if you want to directly input the message in the command, **with quotes**, instead of having git open your text editor (Eg `git commit ammend -m "Fix stuff"`) 
3. If it's few commits down, add `-c <commit id>` where commit id can be found in your `git log`
4. If the commit was already pushed to github, push again with the force tag: `git push -f`

There's also interactive rebase (`git rebase -i`) which is more powerful, but this should suffice.

**Comment by JoanneHing** [comment]
Other than that you might use source tree to edit your commit message too

can refer to the website [here](https://community.atlassian.com/t5/Sourcetree-questions/How-to-edit-commit-message-in-Sourcetree-to-attach-a-Jira-issue/qaq-p/1000538)
