### ISSUE TITLE
Varargs Disadvantage? ("Possible heap pollution via varargs parameter")

### ISSUE THREAD

**Issue by yadobler** [nus-cs2103-AY2425S1/forum#280]
Currently I have a method that uses a signature like `method(Pair<String, String> ... argValues)` where `Pair<K,V>` is a convenience class I have to pair Argument switches and their respective Values

IntelliJ warns `Possible heap pollution via varargs parameter`. I presume this means that when `Pair<K,V>` is compiled, it loses its generic and is a raw `Pair`. But `ArrayList<Pair<String, String>>` also reduces to `ArrayList` during runtime, but the compiler is able to check at compile time if all method calls obey the correct parameter.

Why is varargs unable to determine if a call is passing correct type parameters? And if under the hood varargs `T ... values` are shorthand for `T[] values`, then is there not much advantage over just passing a new array that the compiler would inserted in compiletime, with the benefit of not dealing with unchecked exceptions?

**Comment by Feng1231** [comment]
> Why is varargs unable to determine if a call is passing correct type parameters?

Because varargs are arrays, and you are trying to pass in an Array of generics. They don't go well together.

This was mentioned in cs2030s [here](https://nus-cs2030s.github.io/2324-s2/24-erasure.html#generics-and-arrays-cant-mix)

> But ArrayList<Pair<String, String>> also reduces to ArrayList during runtime, but the compiler is able to check at compile time if all method calls obey the correct parameter.

Likewise, mentioned [here](https://nus-cs2030s.github.io/2324-s2/25-unchecked.html)

I feel that the cs2030s notes explained it quite concisely so I won't provide a TLDR ☹  

> then is there not much advantage over just passing a new array that the compiler would inserted in compiletime, with the benefit of not dealing with unchecked exceptions?

The benefit of varargs is that it accepts a variable number of arguments, so we don't have to overload the methods. You can't have an array parameter with variable size.

**Comment by yadobler** [comment]
@Feng1231 wow that's a great site. I wish we had this when I did 2030S! <s>Not another reminder of why nulls are a billion dollar mistake</s>

Gosh now I know why Rust does borrow checking. It's so dumb having the generic array casted up to a superclass, and then still be accessible as a subclass.

ok thanks!
