### ISSUE TITLE
Usage of factory classes 

### ISSUE THREAD

**Issue by seah-minlong** [nus-cs2103-AY2425S1/forum#288]
![image](https://github.com/user-attachments/assets/76537ffb-6e8b-4c0b-94fb-bff3c38f1070)

Hi all 😄, I moved task creation logic from the task classes (Todo, Deadline, Event) to dedicated factory classes to reduce complexity. While this simplifies task classes, it means creating new factory classes for each new task type. Is this approach sustainable, or could it introduce unnecessary complexity as the project scales?

**Comment by RezwanAhmed123** [comment]
From what I observed in your java files, I think its certainly an interesting approach to this project. 

However, I guess it would not be sustainable as the project scales as you are effectively creating 2 classes to be able to deal with a new type of task each time which in turn makes it a hassle to create a new type each time.

If you are interested, the way I reduced complexity was to keep the creation methods into the class itself and then add a single dedicated check method for the main initialization method (creation from user) so something like:


```java
    // for creation from user input
    public Deadline(String description) throws MortalReminderException {
        super(description);
        String[] descriptionString = description.split("/by");
        checkInitialisationDetails(descriptionString);
        this.description = descriptionString[0].trim();
        this.deadline = getTime(descriptionString[1].trim());
        this.type = "D"; // short for Deadline
    }

    // for creation from file input
    public Deadline(String description, String deadline, boolean isDone) throws MortalReminderException {
        super(description);
        this.type = "D";
        this.description = description;
        this.deadline = LocalDateTime.parse(deadline);
        this.isDone = isDone;
    }

    public void checkInitialisationDetails(String[] descriptionString)
            throws MortalReminderException {
        if (descriptionString.length != 2) {
            throw new MortalReminderException(MortalReminderException.getInvalidDeadlineDescriptionErrorMessage());
        }

        try {
            getTime(descriptionString[1].trim());
        } catch (DateTimeParseException e) {
            throw new MortalReminderException(MortalReminderException.getInvalidDateFormatErrorMessage());
        }
    }
```
The reason why there is no check for the file input is because we assume it has been saved correctly by the program as it has already gone through numerous checks beforehand.

**Comment by seah-minlong** [comment]
Ah, I initially took a similar approach, validating both user inputs and file inputs directly within the task subclasses. However, I found that this caused the subclasses to become quite lengthy, as I was checking and parsing both file and user input within each class. In my case, I didn't have a shared parser method across all subclasses—each class had its own method for validation and parsing, which might have been the core issue. Did you encounter something similar? How did you handle it and overcome this problem?

**Comment by yadobler** [comment]
I assume you're having a factory method so that `Storage` components and `Command` components can create tasks without conflicting each other?

---

Might also help to have it `abstract`ed in the `Task` base class and then have each subclass override the factory method by:
1. calling super
2. taking the _new Task_ and then casting into an instance of the subclass
3. adding additional details like deadline via private setters
4. returning the new SubclassTask

you can also skip (2) by:
1. declaring your `Task` as a `abstract class Task<T extends Task>`
2. Make the factory method return a new `T`
3. Make your subclasses extend `Task` like `class Deadline extends Task<Deadline>`
4. Override factory method in subclass to run `super.FactoryMethod( stuff )` and set a local var to it
5. then add additonal stuff like (3) and (4) above

---

That's how i kinda did mine.
My "factory method" is more of a Command object.

I have a base command class, which takes in the string slices and pushes them into hashmaps. Then each subclass that extends this class has a `runCommand` method that will look into the hashmap for required arguments. This also frees up the argument order, since the parsing method sees the command as:

```VERB [first argument] [/flag1 [flag1 arguments]] ... [/flagN [flagN arguments]]```

<details> 

<summary> I also did something more complicated </summary>

Because I didnt like the nature of only being able to check runtime for ensuring what each argument flag is called. I had the abstract class define a generic `<A extends Enum<A> & ArgEnum<A>>`, and in interface `ArgEnum` i define the methods I want each subclass enums to abide to (ie they must hold a string that defines the flag keyword and a boolean isRequired like `START_DATE('/from', true)`, and then my parser is able to check if all arguments are satisfied, else throw an exception to be caught.

</details>

So. 

1. I have a `CommandBase` class
2. I have a `CreateTaskCommandBase<T extends Task> extends CommandBase` class, which has a `protected T newTask` field for the newly created `Task` object, and code to fetch `Args.TASK_NAME` and `Args.IS_TASK_DONE` from the hashmap 
3. I have a `CreateXXXTaskCommand extends CreateTaskCommandBase<XXX>` which calls `super.run()`, then takes the `newTask` and does things like `newTask.setDeadline(map.get(Args.DEADLINE))` taking the data from the hashmap
4. Then return the task (I use a separate getter so that my `run` commands all can `return this` and i can chain them like stream)

**Comment by RezwanAhmed123** [comment]
> Ah, I initially took a similar approach, validating both user inputs and file inputs directly within the task subclasses. However, I found that this caused the subclasses to become quite lengthy, as I was checking and parsing both file and user input within each class. In my case, I didn't have a shared parser method across all subclasses—each class had its own method for validation and parsing, which might have been the core issue. Did you encounter something similar? How did you handle it and overcome this problem?

Hi, for me I solved it by abstracting common methods as much as possible. I kept the responsibility of parsing details from both user and storage through a shared parser. The moment the input could not be parsed correctly from file an error was thrown. Type specific checks were done at the initialisation anyways which made the entire class more compact. Overall, my longest class was about 120 lines (inclusive of javadocs), which I felt was a reasonable length.

**Comment by seah-minlong** [comment]
Thanks for all your inputs guys, I think it has given me a better idea of how to do things better next time. 😄
