### ISSUE TITLE
Need help with proper indentation of swithc case blocks

### ISSUE THREAD

**Issue by mongj** [nus-cs2103-AY2425S1/forum#291]
I understand that based on the [SE_EDU coding standard](https://se-education.org/guides/conventions/java/basic.html), there is not supposed to be any indentation for `case` clauses.

I have made the relevant changes in intellij (see below)

<img width="427" alt="Screenshot 2024-09-15 at 3 19 48 PM" src="https://github.com/user-attachments/assets/821715fb-5992-4d11-905f-c6e483eb3809">

It formats as intended when `switch` is the first keyword in the line, but still force indent otherwise. Is there any way to get around this in intellij?

![telegram-cloud-photo-size-5-6283070867084789868-y](https://github.com/user-attachments/assets/46f44184-8b96-4572-9c05-31e71ee1e228)

**Comment by yadobler** [comment]
Have a look at #184, there is discussion regarding whether arrowhead-switch statements should be indented or not, since SE-EDU guidelines predate this feature.

Your issue is related to the fact that the SE-EDU guideline, as well as checkstyle, was never designed with _switch expressions_ (ie switch blocks that evaluates to a value) in mind. So consequently it was not designed for `switch` to be pushed in from its statement's indentation level.

So the question here is, do you want the `case` statements to align the level of the statement that has `switch`, or do you want it to be _1 level left_ from the `switch` line's indentation level? 

#184 prefers the latter (what your ide is doing now), but checkstyle will disagree. It's very whishy-woshy. 

You can use and abuse the checkstyle-suppression and intellij-suppression comments to disable checking this block in the meantime, and manually adjust the spacing.

**Comment by emmannyyy** [comment]
I used the same configuration as #132 

In that configuration, I ticked the option 

- [x] Each 'case' on a separate line
