### ISSUE TITLE
Fail to push the branch to remote branch

### ISSUE THREAD

**Issue by Elinengu** [nus-cs2103-AY2425S1/forum#295]
Hello, I just realised I didn't push the merged commit to the remote branch for my A-OOP branch. Now I'm trying to push it to the remote branch but it shows this error message below:
```
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks push -v --tags origin heads/A-MoreOOP:A-MoreOOP
Pushing to https://github.com/Elinengu/ip.git
error: dst refspec A-MoreOOP matches more than one
error: failed to push some refs to 'https://github.com/Elinengu/ip.git'

Completed with errors, see above.
```
![image](https://github.com/user-attachments/assets/c82350da-86ed-47bc-9923-bbe6de8df92b)
![image](https://github.com/user-attachments/assets/ef2bd99d-0ea9-4c1d-a6cd-392ddb292770)

**Comment by Elinengu** [comment]
I think it's because perhaps I tag the wrong stuff in the past. Should I delete the orginal tag that shows below here and then push the merge commit to the remote origin or just simply leave it there?
![image](https://github.com/user-attachments/assets/7909015c-8151-4632-b079-bcc6c78f99cf)

**Comment by emmannyyy** [comment]
I think this is occuring because you already have the tag (A-MoreOOP) on your remote repository, as shown here https://github.com/Elinengu/ip/tags

I had this same problem in week 1, so what I did was delete the tag in the remote repo, and then re-push from my local repo to the remote repo. However, when I did this, it was within the same week/ same day so I don't think it would affect the scripts that were running. 

Not too sure if this will affect the IP dashboard tracking. Prof @damithc, please advise if this will cause the submission in previous weeks to be 'late' 

One alternate solution could be to:
- delete the tag on your local repo
- Merge local and remote 
- shift tag up to appropriate position in SourceTree.

**Comment by damithc** [comment]
@Elinengu Another possible reason (just speculation) is that you gave both the branch and the tag same name, and Git is unable to decide which of the two you are trying to push.
On a related note, our requirement for branch names is `branch-[increment ID]` e.g., `branch-A-MoreOOP`

> Not too sure if this will affect the IP dashboard tracking. Prof @damithc, please advise if this will cause the submission in previous weeks to be 'late'

@emmannyyy It is fine to delete/add tags later. We don't check the timestamp of tags (but we do check the timestamp of commits).
