### ISSUE TITLE
Clarification for junit requirement for iP submission

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#311]
Hi, after changing to GUI, my text-based junit tests no longer work. Do they need to be working for the final iP submission? If so, how do I test a GUI?

**Comment by damithc** [comment]
@tayxuenye Yes, the final submission should have JUnit tests. However, this doesn't mean you need to use JUnit to test the GUI; You can use JUnit to test other parts of the code. After all, JUnit is primarily a unit testing tool, which means it is mostly used to test small units such as individual methods and classes.

**Comment by Domokunx** [comment]
Personally, I feel that GUI testing is best done by sharing it with others and letting them give feedback (how it feels, intuitive or not, etc..)

That’s because I believe that GUI is meant to enhance user experience, and should not hinder the main app functionality, so human user feedback would be best.

JUnit mainly tests functionality such as methods, so it’ll be difficult to write “useful/worth-it” tests for GUI, since for GUI it’s easier to just eyeball and test it yourself. Maybe looking at relevant apps to seeing how they did their GUI, and implementing what you find good might be more useful :p

Also interested in hearing what others think about GUI testing though!

**Comment by yadobler** [comment]
Quite hard to test GUI in jUnit if you plan on using CI testing (gh actions), since the worker vms don't have a display, so javafx will throw an error. 

(yes I tried to smoke test my GUI with gh actions 🥲)

**Comment by tayxuenye** [comment]
Hi, thank you for your inputs. My jUnit tests were based on the text UI so they don't work anymore since I cannot asset equals text. Must I make them work for the GUI? I think it was mentioned in week 4 that they do not have be updated for the GUI anymore.

**Comment by tayxuenye** [comment]
> Quite hard to test GUI in jUnit if you plan on using CI testing (gh actions), since the worker vms don't have a display, so javafx will throw an error.
> 
> (yes I tried to smoke test my GUI with gh actions 🥲)

Sorry I'm not sure what is a smoke test could you please explain?

**Comment by damithc** [comment]
> Sorry I'm not sure what is a smoke test could you please explain?

@tayxuenye It's mentioned in iP details of this week (see below). I guess you haven't reached that point yet.:
![image](https://github.com/user-attachments/assets/28b153da-07d1-4314-958a-1ca41e0bbfc2)

**Comment by damithc** [comment]
> Hi, thank you for your inputs. My jUnit tests were based on the text UI so they don't work anymore since I cannot asset equals text. Must I make them work for the GUI? I think it was mentioned in week 4 that they do not have be updated for the GUI anymore.

@tayxuenye The text UI and the I/O redirection tests (i.e., from `A-TextUiTesting`) can be discarded. But JUnit tests need to remain and adapted to test the logic part (not the GUI) of the chatbot. In fact, that's what (i.e., testing the logic, such as the correctness of command parsing) they should have been used for in the first place -- because even in the Text UI, the text output was already being tested by `A-TextUiTesting` method.
