### ISSUE TITLE
Help for Git commit msgs not satisfying guideline

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#312]
![Screenshot 2024-09-17 212420](https://github.com/user-attachments/assets/8448b122-b9f8-470f-b003-458c37f67270)
![Screenshot 2024-09-17 212435](https://github.com/user-attachments/assets/bcb74ee5-c728-4c2c-9b92-5f53e75c421a)
Hi, may I know why my git commit msgs not follow the standard?

**Comment by Domokunx** [comment]
![IMG_3729](https://github.com/user-attachments/assets/1c71b3d3-79d8-43bf-8f05-c2e9bc57bc38)

hi, I think your 3rd last commit is just slightly too long.

**Comment by rayray39** [comment]
i usually make mistakes in the git body message being too long (over 72 chars), perhaps you could keep a lookout on that

**Comment by yadobler** [comment]
If prof closes one eye, you can do some minor **minor** changes and push the commits, ensuring they follow standard. (Capital first-letter imperative verb at start, no punctuation at end)

_message bodies are optional_

**Comment by emmannyyy** [comment]
I think for one of the commits (491f192), the git commit message does not start with a verb in the imperative tense. 

"Parser and Tasklist ..." 

Perhaps, you can start with "Add assertion ...". 

Apart from that, I think the length of the commit message should also be scrutinised, to ensure it is less than 72 characters long.

**Comment by JoanneHing** [comment]
I think the error is because of the commit message is too long on one line
Can refer to #304 to set a column guide at 72 character to avoid the commit message to be too long or refer to the screenshot from the SE-EDU/guides
<img width="965" alt="Screenshot 2024-09-18 at 9 36 03 AM" src="https://github.com/user-attachments/assets/c5186c07-1a61-4d95-93d5-2f1e3c0a8b4d">

Besides that, for your last commit, you might want to consider following format for the specific scope change commit message
<img width="634" alt="Screenshot 2024-09-18 at 9 35 34 AM" src="https://github.com/user-attachments/assets/7ed00b0e-a0eb-4309-a4a6-7fa7fa2d3b91">
 Not sure is your way of writing violates the convention.

**Comment by damithc** [comment]
> If prof closes one eye, you can do some minor **minor** changes and push the commits, ensuring they follow standard. (Capital first-letter imperative verb at start, no punctuation at end)

This is fine. In fact we will insist on this if this item remains red at the end of the iP, so that ensure all students are able to follow this convention.

> Not sure is your way of writing violates the convention.

If the subject has a `:`, we don't check the text that comes before it. So, you can have anything before `:`, but the text that follows it should be in imperative mood, and the total length of the subject should still be no more than 72 chars.

@tayxuenye Most likely it is due to the subject length exceeding 72 chars.

Furthermore, having a commit message body is optional but if you do have one, it should follow the conventions we have for the body e.g., each line must be no longer than 72 char.
