### ISSUE TITLE
Requesting for others to test JAR file

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#324]
Hi everyone, I have released my JAR file [here](https://github.com/vinceg4/ip/releases/tag/A-Release) with the user guide [here](https://vinceg4.github.io/ip/). I have not tested the program on Mac OS yet (but windows users are welcome to help too!).

I'd really appreciate it if anyone can help to test and report any bugs. Thank you!

**Comment by tata32000** [comment]
Hi @vinceg4, I have tested on MacOS and it seems to be working very well. I have a suggestion to show the task name as it's being added (e.g. I've added read book to the task list). 

![Screenshot 2024-09-18 at 15 36 18](https://github.com/user-attachments/assets/abe7ce48-4053-461b-8583-19b1cd6060c3)

**Comment by hanscau** [comment]
Works on Linux! Just a few nits: 
- Greet message? for a friendlier butler!
- List of valid commands on command error. If I don't know any valid commands, there is no way to find out...

**Comment by vinceg4** [comment]
@tata32000 @hanscau Thank you for testing! Will be sure to keep the suggestions in mind!

**Comment by SwaminathanViswa** [comment]
Hello! It works fine on windows too! Just a few comments:
![image](https://github.com/user-attachments/assets/1bc3b7ac-bdab-45b7-a837-11f979052f5c)

- A welcome message would be good so that I know that the application has started and is running!
- There is a typo in the user guide: "create a deadline task ... /by TASK_NAME DATE" there should not be the `TASK_NAME` after `/by`. 
- And you mentioned according to the user guide that find needs to contain the full word. However, when I input `list ce` it returns me the correct tasks as shown in the screenshot below. So maybe you might need to change the user guide as well!

![image](https://github.com/user-attachments/assets/88f0d571-593d-46f1-8bbf-21c3a26dcf45)

Apart from these comments, your application runs fine and well! 😄

**Comment by Siddardar** [comment]
Works fine for me on MacOS 👍

**Comment by lithops-zty** [comment]
Hi, Windows user here! It works well for me. Just some minor edge case issues:
- The `list` message when the tasklist is empty contains a typo (Sire -> Sir)
- The program crashes on `deadline` and `event` commands with empty description or date

You might want to make your parser more robust and display error messages in such situations. 

Apart from these, great job! 👍  The archive feature is really helpful when the task list becomes messy.

**Comment by yxshrk** [comment]
Hi, windows user here! Looks mostly good to me, just a few suggestions:

1. Allow the user to enter timings in addition to just dates for deadlines and events, as this enhances the functionality of your bot. 
2. A welcome message would be good when the user enters the app. 
3. There can be a check to see if a user is marking/unmarking a task that has already been marked or unmarked respectively - reminding the user that they have already marked/unmarked the task. 
4. There can also be a check to see if the event start time is later than or equal to the event end time when adding a new event task.
![2103testing](https://github.com/user-attachments/assets/56d3036d-176b-4a02-9155-d92b7954931a)

**Comment by vinceg4** [comment]
@SwaminathanViswa @Siddardar @lithops-zty @yxshrk Thank you for testing it out, I will be sure to look into the various bugs and suggestions!
