### ISSUE TITLE
Requesting for testing my chatbot application 

### ISSUE THREAD

**Issue by SKarthikeyan28** [nus-cs2103-AY2425S1/forum#352]
Hi, I would like my chatbot application to be smoke tested. Please give comments on bugs detected and possible areas of improvement. Windows and Linux users testing would be helpful as this application was developed on mac. 

[Tars .jar file](https://github.com/SKarthikeyan28/ip/releases/tag/A-BetterGui
)

[Tars User Guide](https://SKarthikeyan28.github.io/ip/)

**Comment by DesSnowy** [comment]
Hi, I'm on windows and it runs fine for me. Here are some bugs that i think can be improved relatively quickly:

- Calling delete on outOfBound Indexes (such as `delete -5`) will cause error messages to show on the terminal but nothing is shown on the GUI itself. 

- As shown in the image of the user guide, I think there is a typo here as it should be `t` to add ToDos instead of `d`.

![image](https://github.com/user-attachments/assets/3d287ea3-53d0-4bbd-b048-184296cd2057)

**Comment by SwaminathanViswa** [comment]
Hello! I am using Windows and it is working fine! However, I do have some comments that you could take a look at as well:

- According to the GUI, the date must be keyed in `yyyy-dd-MM` for creating new events. However, when I did so, I got this error in my terminal saying that the range of 20 is out of bounds from 1-12. It likely means that the input format is `yyyy-MM-dd` instead. Do take a look at the screenshot attached below!
- There are a few formatting errors as well as shown in the second screenshot below.

![image](https://github.com/user-attachments/assets/489cb1b0-138b-49c6-bb55-4a009f3d887b)
![image](https://github.com/user-attachments/assets/dfe20570-25b8-48c6-bf7b-9c7b68361f4c)


Apart from some small corrections that can be done easily, the rest of your application is very nice and it works well too. So good job 😄
