### ISSUE TITLE
Requesting help to smoke test my jar file

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#356]
Hello everyone! I am a Windows user.
Please do help me smoke test my jar file!

[Jar file](https://github.com/Incogdino/ip/releases/tag/v0.2)
[User guide](https://incogdino.github.io/ip/)

Thank you so much for your help!

**Comment by emmannyyy** [comment]
Looks good to me! 
![image](https://github.com/user-attachments/assets/0ed648b5-7056-4a7d-b418-5853eb1a4cf7)

Your documentation is super neat! Great job!

**Comment by MAOXIONGKAI** [comment]
<img src="https://github.com/user-attachments/assets/4aac6b11-5e86-4042-a590-cab50dc8b703" width="400"/>

Works well on my machine! Good job!

**Some issues that you may want to take it seriously**:
1. Program is not responding me with any error message when I input `delete -1`, while it shows error message when I input `mark -1` and `unmark -1`
2. It seems like your `mark` and `delete` commands are giving out similar but differently phrased error message, I am not sure why is that the case and maybe this is the cause of issue 1? Just be sure that you handle this kind of error through a single method so that everything can behave as expected in a consistent manner.
3. When I mess up the task file and enter the application again, tasks with invalid save data becomes null on the list(and in some other cases jar file can't be opened any more due to `ArrayIndexOutOfBoundsException`). As a result, I can't even close the application either because the code that handles saving feature can't handle null objects properly. Not sure if this is serious or not...But I believe it is better to address situations when the file is corrupted when user opens the application, just like how we did for the CLI version.

Just to add on, your user guide is super amazing and impressive, I can see that you are really putting in a lot of effort to craft  it! Good job!

**Comment by Incogdino** [comment]
> <img alt="" width="400" src="https://private-user-images.githubusercontent.com/40223039/369076919-4aac6b11-5e86-4042-a590-cab50dc8b703.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDA5OTYsIm5iZiI6MTcyNjgwMDY5NiwicGF0aCI6Ii80MDIyMzAzOS8zNjkwNzY5MTktNGFhYzZiMTEtNWU4Ni00MDQyLWE1OTAtY2FiNTBkYzhiNzAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIwVDAyNTEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMmQ4YzJhNmY0NjYxYzdjZDNmNDAzNzI0NzFmMzRhNGM3NjAzYzJjM2UwMTRmZjJiYmM0NTIxNjQ4ZmQ0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bFmjcoGOdLtVZerCltAkoN0Kq_4W_Ub5swGGYQKyZ50">
> Works well on my machine! Good job!
> 
> **Some issues that you may want to take it seriously**:
> 
> 1. Program is not responding me with any error message when I input `delete -1`, while it shows error message when I input `mark -1` and `unmark -1`
> 2. It seems like your `mark` and `delete` commands are giving out similar but differently phrased error message, I am not sure why is that the case and maybe this is the cause of issue 1? Just be sure that you handle this kind of error through a single method so that everything can behave as expected in a consistent manner.
> 3. When I mess up the task file and enter the application again, tasks with invalid save data becomes null on the list(and in some other cases jar file can't be opened any more due to `ArrayIndexOutOfBoundsException`). As a result, I can't even close the application either because the code that handles saving feature can't handle null objects properly. Not sure if this is serious or not...But I believe it is better to address situations when the file is corrupted when user opens the application, just like how we did for the CLI version.
> 
> Just to add on, your user guide is super amazing and impressive, I can see that you are really putting in a lot of effort to craft it! Good job!

Thanks you for the in depth testing. I think you brought up some really good testing points especially the last one with the corrupted file.

I have (hopefully) fixed them in the updated [jar file](https://github.com/Incogdino/ip/releases/tag/v0.2). Thanks a lot!
