### ISSUE TITLE
Requesting to smoke test my chatbot application

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#359]
Hi guys, I am a Windows user.
Please help me smoke test my jar file here, thank you very much!
[Jar File](https://github.com/MAOXIONGKAI/ip/releases/tag/A-Release)
[User Guide](https://maoxiongkai.github.io/ip/)

**Comment by lavanyagarg112** [comment]
Hi, I am a mac user, and I tested it. It looks really pretty, and all the features work really well!

**Comment by Incogdino** [comment]
Hi I'm using windows and the application works great! 

However, 
1. I think you forgot to add the list command into this error message
![image](https://github.com/user-attachments/assets/86d76046-e49e-4f78-9c20-2001fc0d24b5)

2. When I input "list " (with extra whitespace), it returns the error message instead of displaying the list of tasks

**Comment by wes-w-z-h** [comment]
lgtm 👍Nice ui

**Comment by MAOXIONGKAI** [comment]
@lavanyagarg112 @Incogdino Thanks you guys so much for the testing!!! Glad that you all like the UI.
@Incogdino Thank you very much for the testing of edge cases! I have fixed these issues and updated my release, everything should work just fine now!
