### ISSUE TITLE
Jar file too small

### ISSUE THREAD

**Issue by jinnsuke** [nus-cs2103-AY2425S1/forum#376]
Hi! 

My teammates pointed out that my Jar file size is only 1.3mb but based on the previous weeks, it should be 5mb++. I followed the steps given multiple times but the Jar file size still remains at 1.3Mb. The Jar file works completely fine other than that. Is this something I should fix and what might be causing this issue?

Thanks!

**Comment by Tkaixiang** [comment]
Hi, could I check that the images are loaded correctly and this includes the GUI version too? JavaFX by itself should be quite big already

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://bit.ly/3TzaAQd

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by uniqly** [comment]
When I try to run your jar file using `java -jar xxx.jar`, the following output is shown :
```
Error: Could not find or load main class shoai.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

I think your `gradle.build` file might not be properly configured. I also tried building your project on my local machine, but it seems that you put emoji literals into Java strings which causes Java to scream at me since this is not supported on windows.

**Comment by jinnsuke** [comment]
@uniqly 

Nice catch! Will settle the emoji issue :)
