### ISSUE TITLE
Requesting help for smoke test

### ISSUE THREAD

**Issue by matchastack** [nus-cs2103-AY2425S1/forum#385]
I have a M1 Mac device. Would appreciate if anyone could help me test my app on other OS.

Here is the link to my [.jar](https://github.com/liauzhanyi/ip/releases/tag/v1.0) and [user guide](https://liauzhanyi.github.io/ip/)

**Comment by ghos7ie** [comment]
hi, i tried it out on Win11. works fine!

I did notice a bug? since you are delimiting your tasks in the text file by `,`.

![image](https://github.com/user-attachments/assets/1f1eda57-0665-4ab2-88f5-cddb75027cb3)

If task description has trailing commas, it will result in whatever after not being read if you reopen the application.

![image](https://github.com/user-attachments/assets/6abfff17-6ecd-4796-a02b-20593c7851c0)


Your user guide was easy to read as well!

Do you mind helping me try mine as well, as I am on Windows :)
Here's my [jar](https://github.com/ghos7ie/ip/releases/tag/v0.4) and [ug](https://ghos7ie.github.io/ip/)

**Comment by myrilla12** [comment]
I tested on M2 Apple Silicon. It LGTM, runs well. I noticed that it will still try to list the tasks even if there are none in list yet though. I don't think it's important but just in case you want to handle that

**Comment by matchastack** [comment]
@ghos7ie thanks for the help and spotting the bug on my storage!

I have tested your app on my device and there is no issue launching the app can carrying out the examples as stated in the user guide. however I noticed that the app will throw an invalid command message for task description that is a single word 

<img width="405" alt="Screenshot 2024-09-20 at 10 29 44 PM" src="https://github.com/user-attachments/assets/5488a901-aaee-400f-a709-59bd045d8476">

**Comment by ghos7ie** [comment]
@liauzhanyi thanks so much for helping me out too :)

will check out what's causing the 1 word issue, didn't catch it during my testings!
