### ISSUE TITLE
Request help for smoke test

### ISSUE THREAD

**Issue by travisim** [nus-cs2103-AY2425S1/forum#387]
I use a m2 pro macbook on macos Sequoia 15.1, i need a windows or linux user's help to test
[user guide](https://travisim.github.io/ip/) and [.jar file](https://github.com/travisim/ip/releases/tag/v0.4)

**Comment by Incogdino** [comment]
Hi, I am using Windows 11 and the jar file works fine!

![image](https://github.com/user-attachments/assets/58f8210f-1b25-49fc-8723-03dfaab8f56d)

**Comment by gohsl99** [comment]
Able to run on Windows 11.
Some suggestions:
1. You may consider to catch the error `... could not be parsed at index 4` and print `OOPS!!! ...` instead.
![image](https://github.com/user-attachments/assets/4704650d-64cf-49c8-bff6-aa086bba1b24)
2. You may consider to catch index out of bounds error and print some message.
![image](https://github.com/user-attachments/assets/b1e4ce7a-b553-4cc2-b386-701c3af6443a)

**Comment by MAOXIONGKAI** [comment]
![image](https://github.com/user-attachments/assets/7937d3f1-d210-4021-9b97-a9dbb6f01a9b)
It works well, good job! No serious issues found, but maybe somethings to take note:
1. For the submission of Ui.png, I remember one of the requirements is to show the product name in the screenshot and preferably at the title of the application window, so you may want to fix on that.
2. The cmd window keeps on showing messages as I inputting commands, especially when I open the application, it feels a bit weird that the welcome message shows in the cmd instead of on the application window.
3. As according to the requirement and prof's reply to other people's clarification(see #309), it would be better if you can include logic that will warn user about corrupted save file when they open the application. Currently if I mess up the local save file, the tasks are simply not created on the application which I believe is not major bugs, but it is still better if you can fix it.
