### ISSUE TITLE
Request help for smoketest

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#392]
Hello, I'm using Mac Intel, and would appreciate if you could help me test my Jar file on any other OS!

Jar file for my chatbot can be found here:
[Link to Jar file](https://github.com/annabellekk/ip/releases/tag/A-Release)

User guide can be found here:
[Link to User Guide](https://annabellekk.github.io/ip/)

Thanks in advance!

**Comment by MAOXIONGKAI** [comment]
<img src="https://github.com/user-attachments/assets/52ea6a7e-c81c-40c4-bfbd-b0a7176e85a8" width="400" />

Hi I am using Windows 11, it works well on my machine.
I think there may be something that you may want to look into and fix?:
1. I think this is a trivial one because normal user wouldn't do something like this, but it seems like you are storing time as string for your task? and as a result I can input something like 25pm or 100pm without the program complaining about anything...Also, I believe it is possible for a user to accidentally typed some other things when inputting time and causes unexpected behaviour of your program. Even though user can delete and add in the correct one(provided he/she realized about the typo), it may fail the iP requirement of handling error gracefully, but whether to fix it is up to you. Personally I as a user think this is acceptable, but you may not want to handle things in this way again during the tP.
2. The user guide says that the command `remind` will remind user of the upcoming deadlines and events but the program only shows me events that happened on that day and not the deadlines, so you may want to either fix your program if this is not the intended behaviour or fix the user guide if it shows the wrong instruction
3. Currently the program does not show any error message if the file is corrupted

**Comment by winstonlimjy** [comment]
Using windows machine here too:

The bot did not respond when i typed in an invalid date. But at least it didn't crash, that's great.
![image](https://github.com/user-attachments/assets/c73dc0a2-0ac5-49e5-a2af-4e14d0acb775)

Just maybe can handle if the date is before the current date, don't allow it maybe 🤔
![image](https://github.com/user-attachments/assets/aa9b4b0d-c205-42cd-9b58-04a2d555f39a)

or if the end date is < than the start date:
![image](https://github.com/user-attachments/assets/096d040a-5f20-4c19-981e-b31ea104d94c)

But overall no crashes! Well done!
