### ISSUE TITLE
I am unable to find the issue in my GitHub readme of markdown syntax present but it is seen in the other link.  

### ISSUE THREAD

**Issue by miuna9890** [nus-cs2103-AY2425S1/forum#394]
https://github.com/miuna9890/ip/blob/master/docs/README.md

Just to let you know, the following problems were noted with respect to your iP final submission:

An automatic check found that your iP user guide (as shown [here](https://miuna9890.github.io/ip)) might not be rendered correctly e.g., markdown syntax such as ##, --|-- or HTML tags such as <br/> are visible in the page.
Please check the page carefully to confirm it shows what it supposed to. If no problem found, you can ignore this email. If you located a problem, please fix soon (no penalty).

**Comment by JoanneHing** [comment]
I think the problem that the `## Guide` is having an extra whitespace before the `##` as shown below (highlighted part). By removing it should render the markdown correctly.
<img width="115" alt="Screenshot 2024-09-21 at 2 08 57 PM" src="https://github.com/user-attachments/assets/b53da6ed-25fe-49b9-b205-9f46e41c0c91">

### Some Suggestions
Besides here are some suggestion for the GFMD for your UG

1. Format can be shown in inline code
<img width="380" alt="Screenshot 2024-09-21 at 2 11 10 PM" src="https://github.com/user-attachments/assets/6540ab76-b46c-479d-a07e-af19c5884cf9">

- With inline code
<img width="409" alt="Screenshot 2024-09-21 at 2 12 02 PM" src="https://github.com/user-attachments/assets/230ee1f7-16db-4522-b3e3-073e0be21bd6">

----

2. Consider using `$_num$` for the subscript
<img width="184" alt="Screenshot 2024-09-21 at 2 12 32 PM" src="https://github.com/user-attachments/assets/f9b61d35-57d2-489d-b5e1-cd63cc7c93dc">

- After using the markdown
<img width="161" alt="Screenshot 2024-09-21 at 2 13 15 PM" src="https://github.com/user-attachments/assets/b4def439-3bcb-4879-bcaa-4494d90122e0">

---

3. Consider setting first characters of word in headings as capital letters
<img width="383" alt="Screenshot 2024-09-21 at 2 15 30 PM" src="https://github.com/user-attachments/assets/73712728-fceb-4455-b810-ca3406790591">

---

4. Bold the first line or important keywords of the paragraph instead of the whole paragraph
<img width="413" alt="Screenshot 2024-09-21 at 2 15 53 PM" src="https://github.com/user-attachments/assets/a086c579-c4ba-4df1-bbfc-00b8eb89e475">

---

Just some minor suggestions that you can consider! Its very nice of you include the sample GUI for each of the features outcome too! Good job! Hope it helps!

**Comment by miuna9890** [comment]
Thanks alottt @JoanneHing ! I will implement the suggestions too. thx

**Comment by JoanneHing** [comment]
Welcome!
