### ISSUE TITLE
Requesting help from Windows/Linux to smoke test jar file

### ISSUE THREAD

**Issue by Quasant** [nus-cs2103-AY2425S1/forum#412]
Looking for help in smoke-testing my IP, UG linked [here](https://quasant.github.io/ip/) and you can find the release jar [here](https://github.com/Quasant/ip/releases) (v0.5 now). 

Thank you and appreciate the help!

**Comment by starbucksventi** [comment]
Hi, 2 possibly minor issues were found.
Firstly, doing archive with extra text works instead of notifying the user of an errant command. If this is a feature, then feel free to ignore it:
![image](https://github.com/user-attachments/assets/fdaa46ff-c51f-4ee5-becc-2f684b5e95d4)

Secondly, when I archive my task list, proceed to add further tasks and archive again, it overwrites the previously archived tasks. 2 ways to fix this would be to either changing from writing to appending when you save to archive.txt, or a while loop to increment the archive(n).txt for each new archived file.
![image](https://github.com/user-attachments/assets/ace20796-a5bd-41ea-af46-d3e455295fb7)

Cheers!

**Comment by Quasant** [comment]
Thank you! The first one is intended for simpler commands, whilst others are more strict with the format. 

I believe I have fixed the second one in v0.5 already, hopefully that version is the final one.
