### ISSUE TITLE
can any body do a smoke test for my code?

### ISSUE THREAD

**Issue by lancehaha** [nus-cs2103-AY2425S1/forum#419]
here is my [release page](https://github.com/lancehaha/ip/releases/tag/A-Release)
and here is my[ readme](https://github.com/lancehaha/ip/blob/master/docs/README.md)

**Comment by Feng1231** [comment]
Hello! I am using windows.
`java -jar Main.jar` throws me an error:
![image](https://github.com/user-attachments/assets/834c1dd9-8853-4bdb-94a6-18910d63bbb8)

I am able to run jar files of other course mates, so I don't think the issue is coming from my computer.

I have checked your `build.gradle` file

```java
application {
    mainClass.set("Main") // this should be mainClass.set("Launcher")
}
```

**Comment by damithc** [comment]
> Hello! I am using windows.
> `java -jar Main.jar` throws me an error:
> ![image](https://private-user-images.githubusercontent.com/128298170/369750263-834c1dd9-8853-4bdb-94a6-18910d63bbb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNjgxNDQsIm5iZiI6MTcyNzA2Nzg0NCwicGF0aCI6Ii8xMjgyOTgxNzAvMzY5NzUwMjYzLTgzNGMxZGQ5LTg4NTMtNGJkYi05NGE2LTE4OTEwZDYzYmJiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyM1QwNTA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDFiN2M0YzAwNjNjOWI4NDE0N2NlNzYyNjRhMTUyNDJlM2Q0ZTQ1ZDNiY2Y4MTFhNjI3ODczZjBiNDgyMjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9aWvF6LRFhti_jWXuUfPHjt_tlLbAsR6KIPPvqV3HdA)

@Feng1231 Not related specifically to this issue but you it is best to put the jar file in an empty folder, navigate to the location of the jar file file, and only then run the `java -jar` command. This is because the data files are created relative to the location in which the command is run, and data files created by other jar files can interfere with the running of the current jar file.

**Comment by Feng1231** [comment]
> @Feng1231 Not related specifically to this issue but you it is best to put the jar file in an empty folder, navigate to the location of the jar file file, and only then run the `java -jar` command. This is because the data files are created relative to the location in which the command is run, and data files created by other jar files can interfere with the running of the current jar file.

Will do that in the future, thank you prof for pointing that out!

**Comment by lancehaha** [comment]
@Feng1231
thank you for telling me this issue, some how on mac this problem is not kicking in, so I missed it.
