### ISSUE TITLE
Requesting smoke test on MacOS or linux

### ISSUE THREAD

**Issue by keithxun** [nus-cs2103-AY2425S1/forum#436]
This is my release page: https://github.com/keithxun/ip/releases/tag/A-Release-2.1
This is my user guide: https://keithxun.github.io/ip/

Need help testing on linux since it did not pass the smoke test the first time round.

```
keithong@KeithOngcom:~$ java -jar bopes.jar
Sep 25, 2024 12:07:00 AM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @1ee8f3b8'
MESA: error: ZINK: failed to choose pdev
glx: failed to create drisw screen
```

On a side note, I am getting this error when I attempt to run the file on ubuntu. This seems like an issue with my linux environment, not the jar file and will appreciate any advice.

Thanks in advance!

**Comment by LowXiSi** [comment]
I ran your jar file on macOS Ventura 13.5.2 and didn't encounter any errors. 
I played around a little bit and didn't encounter any crashes but here are some minor things you might want to take note of:

- error message formatting starts with `error: error: ` not sure if this is intended?

- Trying to delete a bad task number results in `an unexpected error occurred` but `task index out of range` may be a more useful error message

- input: `event NAME /to TODATE /from FROMDATE`
output: `... (from: TODATE to: FROMDATE)` which flips the two dates

<img width="403" alt="Screenshot 2024-09-25 at 2 54 44 AM" src="https://github.com/user-attachments/assets/8a9bd257-4f42-47e5-b743-ad05df4bbe24">


otherwise the program looks great :)

**Comment by yyihaoc** [comment]
Hi! I ran your jar file on macOS Sonoma 14.2 and no error is encountered. Same observations as @LowXiSi. One more thing is that the GUI can be shifted left and right, not sure if its intended that way. 
Overall, it looks great to me, good job on having the error messages appear in a different colour!

**Comment by yockcheng** [comment]
<img width="451" alt="Screenshot 2024-09-25 at 1 24 59 PM" src="https://github.com/user-attachments/assets/359e52e0-5a39-4f23-9be2-f94bd8511e8e">
<img width="488" alt="Screenshot 2024-09-25 at 1 28 12 PM" src="https://github.com/user-attachments/assets/78fa2687-af99-441a-8361-cb5c27e1746d">

Hello, I ran your jar file on my mac and everything looks good, just have a few comments:

-  Maybe could have a more useful message when the list is empty so that it doesn't seem like the app is malfunctioning?
- I think your current code dumps the whole data file when 1 input is faulty instead of just discarding that particular data input, not sure if its your intended behaviour
- Can consider trimming whitespaces from inputs also so that people cannot insert empty descriptions for the tasks
- Maybe can make find non caps-sensitive so that "read" and "Read" are basically the same word 

Other that that, I think its great!

**Comment by Jollybomber** [comment]
<img width="651" alt="Screenshot 2024-09-26 at 5 41 57 PM" src="https://github.com/user-attachments/assets/6a069178-be2b-4c09-b7d7-9f407e61e673">

Hi, ran your jar file on my mac and everything looks good, just some small comments:
- Perhaps a help message could be included to list all possible commands.
- The positioning of text changes if the message is too long.
- There is an unknown error when the event /to date is after the /from date, perhaps an error message like "to date must be after from date" would be better?

Good job!
