### ISSUE TITLE
Problem involved running runtest.sh for A-TextUiTesting

### ISSUE THREAD

**Issue by blackpanther9229** [nus-cs2103-AY2425S1/forum#44]
While editing the configuration for runtest.sh, I don't know what to put in the "interpreter path". I try leave that blank and run the program, my computer only opened another software to show me the code of runtest.sh. How I can fix this problem. Thank you.
My OS is Window and I am using Intellij.
This is a screen shot of the configurations edit window
![image](https://github.com/user-attachments/assets/76342c06-98be-43fd-bd5b-cb5f13724c4d)

**Comment by damithc** [comment]
@blackpanther9229 while waiting for peer inputs, it'll help if you give more info e.g., your OS, IDE, screenshots

**Comment by zaidansani** [comment]
Hi. I didn't use IntelliJ to run the .sh file, and instead used the terminal! Upon checking my IntelliJ however, my interpreter options are just BASH - options: `BASH`, path: `/usr/bin/env`.

This particular UI looks like you're also using MacOS, so this should apply to you aswell!

**Comment by blackpanther9229** [comment]
> Hi. I didn't use IntelliJ to run the .sh file, and instead used the terminal! Upon checking my IntelliJ however, my interpreter options are just BASH - options: `BASH`, path: `/usr/bin/env`.
> 
> This particular UI looks like you're also using MacOS, so this should apply to you aswell!

Well it doesn't work because somehow, the app doesn't recognise the interpreter
![image](https://github.com/user-attachments/assets/01b93af6-c178-4aa0-a0d1-b1a19a3579aa)

**Comment by damithc** [comment]
> This particular UI looks like you're also using MacOS, so this should apply to you aswell!

@blackpanther9229 said  the OS is Windows

**Comment by zaidansani** [comment]
> > This particular UI looks like you're also using MacOS, so this should apply to you aswell!
> 
> @blackpanther9229 said the OS is Windows

Ah. That's my bad then.

If you're using Windows, that means you most likely don't have BASH installed. There are two ways you can test now:

1. The easier way (at least, in my opinion): Using the .bat file
The .sh file requires a Unix shell - (Windows terminal is DOS) - so using a [.bat](https://en.wikipedia.org/wiki/Batch_file) file would be easier, as it runs natively on Windows.

2. Using the .sh file
There are a lot of ways to access BASH in Windows - one way would be to use [Git's BASH](https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt) since that should be installed, or install another tool, or another (long-winded way, but you might find it useful for later) is to install [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install), and move your programming environment there (which you might find helpful in the future.)

**Comment by blackpanther9229** [comment]
> > > This particular UI looks like you're also using MacOS, so this should apply to you aswell!
> > 
> > 
> > @blackpanther9229 said the OS is Windows
> 
> Ah. That's my bad then.
> 
> If you're using Windows, that means you most likely don't have BASH installed. There are two ways you can test now:
> 
> 1. The easier way (at least, in my opinion): Using the .bat file
>    The .sh file requires a Unix shell - (Windows terminal is DOS) - so using a [.bat](https://en.wikipedia.org/wiki/Batch_file) file would be easier, as it runs natively on Windows.
> 2. Using the .sh file
>    There are a lot of ways to access BASH in Windows - one way would be to use [Git's BASH](https://stackoverflow.com/questions/26522789/how-to-run-sh-on-windows-command-prompt) since that should be installed, or install another tool, or another (long-winded way, but you might find it useful for later) is to install [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install), and move your programming environment there (which you might find helpful in the future.)

Thanks bro, it seems to run, but now this problem appear
![image](https://github.com/user-attachments/assets/98b16a95-11f8-4923-b3c2-c72ae9629e3f)

**Comment by zaidansani** [comment]
If `javac` is not recognised, that generally means either Java is not installed (highly unlikely since you should have used it to run this) or it's not in your PATH.

Here's [Oracle's documentation on setting JAVA_HOME](https://docs.oracle.com/cd/E19182-01/821-0917/inst_jdk_javahome_t/index.html). If you're not sure where your Java installation is, you can go into your Project Structure in IntelliJ, and look at Platform Settings > look at your installation and see your JDK home path there.
![image](https://github.com/user-attachments/assets/40b3d2a5-d9ec-4055-9a4c-ad780c8c024d).

Hope this helps!

**Comment by blackpanther9229** [comment]
> If `javac` is not recognised, that generally means either Java is not installed (highly unlikely since you should have used it to run this) or it's not in your PATH.
> 
> Here's [Oracle's documentation on setting JAVA_HOME](https://docs.oracle.com/cd/E19182-01/821-0917/inst_jdk_javahome_t/index.html). If you're not sure where your Java installation is, you can go into your Project Structure in IntelliJ, and look at Platform Settings > look at your installation and see your JDK home path there. ![image](https://private-user-images.githubusercontent.com/53702072/361161868-40b3d2a5-d9ec-4055-9a4c-ad780c8c024d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NTMwMDcsIm5iZiI6MTcyNDU1MjcwNywicGF0aCI6Ii81MzcwMjA3Mi8zNjExNjE4NjgtNDBiM2QyYTUtZDllYy00MDU1LTlhNGMtYWQ3ODBjOGMwMjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDAyMjUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ODlkMWNhNzI4OGE4YzQ0NjQ1YmRhZTI3NzZlZDUwYjgwYjFmM2JiN2QwNDc5ZjUzOGRmOTg4ODY1NjVkNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l25gFtO27t7zFvgfHMni4s5PjRXeX40gYmstuXYrLfw).
> 
> Hope this helps!

Thank you! I found out that I haven't download jdk 17. Now it works as intended.
