### ISSUE TITLE
Failing smoke tests for my iP

### ISSUE THREAD

**Issue by WuJinhan1** [nus-cs2103-AY2425S1/forum#448]
For my iP, I have downloaded the azul jdk version specified for mac users on the 2103 website for step 10 of the iP. For my final jar file, I did the smoke test on my groupmate's computer and it works so then I just left my jar file be on my github page. However, I have just gotten an email saying that it fails smoke tests on other systems, and the error message is "JavaFX runtime components are missing, and are required to run this application". How would I fix this issue?

**Comment by damithc** [comment]
@WuJinhan1 Perhaps you can give the link to your jar here so that other non-Mac users can easily try it to see if it works?

**Comment by WuJinhan1** [comment]
Here is the link to my jar
https://github.com/WuJinhan1/ip/releases/tag/A-Release
also I the java version I installed is from this page
![Uploading Screenshot 2024-09-27 at 10.56.52 PM.png…]()

**Comment by WuJinhan1** [comment]
https://se-education.org/guides/tutorials/javaInstallationMac.html

**Comment by yastsc** [comment]
![ss](https://github.com/user-attachments/assets/29c685a2-aec7-4a30-82a7-ceda1db562e7)
I tried it on a Windows computer and it is giving the same error you mentioned. From your code, I think the issue might be that you don't have a Launcher class?

**Comment by yastsc** [comment]
I think this commit from AB3 might help: https://github.com/se-edu/addressbook-level3/commit/12bb91903e71ea1109e04f7369c2169f1c7be39a

**Comment by WuJinhan1** [comment]
Hello I have just made the fix from the guide to change the entry point and have just made a new release. It works on my groupmate's computer but could any of you guys test it again to make sure?
https://github.com/WuJinhan1/ip/releases/tag/A-Gradle
Also I have it tagged under a different tag since the original A-Release tag was taken, is that fine?

**Comment by damithc** [comment]
> Also I have it tagged under a different tag since the original A-Release tag was taken, is that fine?

Yes, that is fine @WuJinhan1

**Comment by RyanWarwick** [comment]
Tested Release with tag A-Gradle

Host Machine OS -
Windows 10 ver 22H2 (build 19045.4894)

- using Powershell

![Screenshot (41)](https://github.com/user-attachments/assets/1bee2433-9338-4f7a-a1b9-ce842047cbda)

![Screenshot (42)](https://github.com/user-attachments/assets/4c2dc2a1-f78a-4cd1-8565-5a875f5f0a4f)

![Screenshot (43)](https://github.com/user-attachments/assets/611c7380-d1c1-47dc-b8dc-d97002ef8e3e)

LGTM

(P.S. Tried to run it on Ubuntu 22.04.3 LTS (WSL 2) with openjdk-17, which complains that it is missing JavaFX components as well. This is behavior similar to Mac OS jdk releases; needing to install these components via FX Azul etc. Will not test further due to it possibly not being in-scope)

Thanks for summoning me :)

**Comment by chongtzezhao** [comment]
Tested Release with tag A-Gradle

Host Machine OS -
Windows 11 Home ver 23H2 (build 22631.4169)

Using Command Prompt

![image](https://github.com/user-attachments/assets/f7c223b4-0d4f-4dc9-8f5c-213a2c89afb6)

LGTM!

WSL2 with Oracle Java 17:

![image](https://github.com/user-attachments/assets/8dd88b24-a23a-4ac3-b208-6072409e6ae4)

Also LGTM!

**Comment by WuJinhan1** [comment]
ok thank you guys so much!
