### ISSUE TITLE
Unable to run AB3 using IntelliJ UI

### ISSUE THREAD

**Issue by rynlwhh** [nus-cs2103-AY2425S1/forum#453]
Hi, I am running into issues with running AB3 using the IntelliJ UI, but I have ensured that the JDK used is JDK17 as shown in the images. It runs perfectly fine with gradle but not with the UI, can anyone suggest what I could do with the error I got?

<img width="988" alt="Screenshot 2024-09-30 at 6 23 40 PM" src="https://github.com/user-attachments/assets/5f58749c-5d5b-40d8-8133-a1ff7eb24bd0">

<img width="1024" alt="Screenshot 2024-09-30 at 6 30 09 PM" src="https://github.com/user-attachments/assets/83c8a569-e936-4ceb-bcb9-be1ade0c6f28">

<img width="1416" alt="Screenshot 2024-09-30 at 6 29 59 PM" src="https://github.com/user-attachments/assets/b21a472c-754d-428e-acc5-13a77043d881">

**Comment by Javiery3889** [comment]
Hi @rynlwhh, just dropping in from your senior batch. Based on the screenshots, it appears you are running IntelliJ on MacOS.

If so, perhaps this issue is related to this JDK distribution issue highlighted in the [course website](https://nus-cs2103-ay2425s1.github.io/website/admin/programmingLanguages.html#programming-language)? 
<img width="751" alt="Screenshot 2024-09-30 at 23 40 40" src="https://github.com/user-attachments/assets/ab17333c-1926-4781-b115-52710d314aa2">

It might be because the JDK distributions are different on your IntelliJ configuration and gradle.

**Comment by rynlwhh** [comment]
Okay thank you!
