### ISSUE TITLE
tP: merging PR that doesn't pass test cases

### ISSUE THREAD

**Issue by btbrandon** [nus-cs2103-AY2425S1/forum#468]
My team and I decided on splitting the workload for week 8 tP by components as there is much to change regarding the removal/addition of new fields and functions to each component of the tP since this is our first time actually working on the tP. 

However, after updating the "model" component of the tP, we realised that sending a PR to the team repo would mean that the PR would fail the test cases (since it is the updated version with new fields & functions and different argument orders for the already existing functions). 

Since we were taught to not merge PRs that fail test cases, what are the potential work arounds for this? Should one person edit all files required to remove/update all the new and unused classes and fields?

**Comment by damithc** [comment]
> My team and I decided on splitting the workload for week 8 tP by components as there is much to change regarding the removal/addition of new fields and functions to each component of the tP since this is our first time actually working on the tP.

@btbrandon It's one of the teething problems teams encounter around this time. What you are encountering is one of the problems (there are others)  of splitting work by components. Hence, we advise against splitting work by components (see screenshot appended below; also mentioned during the lecture briefing y'day).  

* So, it is best if you redistribute work so that each person removes/adds a field throughout the entire system, rather than one component.
* You can refer to [AB3 tutorial: Removing a Field](https://se-education.org/guides/tutorials/ab3RemovingFields.html) for removing a field.

![image](https://github.com/user-attachments/assets/165bb348-75a3-4ca8-b35d-0745175473fa)
