### ISSUE TITLE
Clarification on Forking Workflow for v1.2

### ISSUE THREAD

**Issue by curtischang2510** [nus-cs2103-AY2425S1/forum#470]
Hello Professors,

I would like to seek clarification regarding the forking workflow for our project in v1.2.

Our team has been divided into two sub-teams, one focusing on the UI and the other on the logic. To prevent potential conflicts, we are considering creating two separate branches from the master branch in our upstream repository—one for the UI team and another for the logic team. Each sub-team would then make their pull requests to their respective branches. This would allow us to isolate changes in each domain, and the master branch would remain untouched until we are ready to merge the two branches at the end of the cycle.

I wanted to confirm if this approach is allowed or recommended for our project as I have yet to see anything relating to branching from the upstream repo.

Thank you for your guidance!

**Comment by damithc** [comment]
> Our team has been divided into two sub-teams, one focusing on the UI and the other on the logic.

@curtischang2510 We advise against dividing work by component See #468 

> This would allow us to isolate changes in each domain, and the master branch would remain untouched until we are ready to merge the two branches at the end of the cycle.

If each branch focuses on a separate component, you are heading for a [big-bang integration](https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/chapters/integration.html#big-bang-vs-incremental-integration), the worst option among integration choices. So, we advise against this too. Creating small PRs against the `master` branch is more aligned with the continuous integration approach, which is also the safest. In the spirit of breadth-first iterative approach, try to move the entire code base forward in small steps, not evolve components separately.

> I wanted to confirm if this approach is allowed or recommended for our project as I have yet to see anything relating to branching from the upstream repo.

As far as grading goes, code merged into other branches will only be recognized when that branch is merged to the master branch. So, those code/branches/PRs will eventually be recognized. 
However, as mentioned above, this approach is not recommended. 

Note that in some case implementing a specific feature (not a component) might need multiple steps (and multiple PRs), and it may be better to keep that code away from the master branch until all the steps are completed. In that case, it is fine to do that work in a separate branch (a so-called _feature branch_) and PR against that branch for a while, until that feature is ready to go into the master branch. Even then, it is better to keep merging that feature branch to the master branch as often as possible, at each point the feature's current state become suitable to be released.

**Comment by charlesliyifeng** [comment]
Hi prof, 

I have a follow-up question on grading.
For milestone v1.2, we are expected to merge some code.
Is it ok to merge to a feature branch instead of the master branch in v1.2 as long as we merge the feature branch in v1.3?
Or will we be penalised because the grading script does not recognise other branches?

Thank you!

**Comment by damithc** [comment]
@charlesliyifeng The v1.2 needs to to take the _entire_ codebase forward in a meaningful way, without breaking other code, which means the cumulative code change of v1.2 needs to happen in the master branch, not in separate feature branches. So, if you do the changes in feature branches (which is allowed), each feature branch needs to be merged to the master branch at the end of v1.2, not delay till in v1.3. Otherwise v1.2 is not an iteration on its own but just a part of v1.3. 
Figuring out which small incremental changes are suitable for an iteration is one of the important learning outcomes we are aiming for -- even more important than the mechanics of following the workflow correctly.
