### ISSUE TITLE
Week 8: UML Diagram questions on example

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#471]
For the given example, it states that ActionFactory adds ActionX to a History object hence we know there History has a reference to ActionX. But why do we omit this association in the class diagram? Shouldn't we draw it as well or is this already implied by the dependency of ActionFactory to History?

<img width="408" alt="image" src="https://github.com/user-attachments/assets/e6fb291a-d2d3-4627-9b0c-c5bd91153fd6">

Also in another example, if we put composition relationship that an email HAS-A body, why is 0 allowed? I thought composition referred to a strong ownership where if an email is created, it must have a body. Here, if email can live without body, won't it be similar to aggregation instead?
<img width="383" alt="image" src="https://github.com/user-attachments/assets/8d5dc7d2-b344-42fa-93a7-5cdbb946d9c2">

**Comment by damithc** [comment]
Good questions @vinceg4 
Let's wait for a bit to see if others have any thoughts on this.

**Comment by MAOXIONGKAI** [comment]
I think the association line between History and ActionX/Y are not necessary because this can be inferred from the class diagram itself. Since History object tracks references of Repeatable Interface Object(which is implemented by Action abstract class and eventually inherited by ActionX/Y classes), this implies that History would have references to ActionX and ActionY objects(as history, as indicated by the association role between History and Repeatable objects).

For the email body part, I think composition only implies that child's existence must depend on parent's existence and not the other way around. In some cases, you may initialize a parent object with some of its parts being undefined and only assign them afterwards, then this would actually imply a multiplicity of 0 for the child object. One possible case I can think of maybe is like other than Email class, I want to create a Draft Class that contains the information that I want to send but haven't finished yet, then in case when I try to save an email as a draft, I may create a Draft object in which the body is null. Hence, even though in this case body is part of the Draft, I can still have its multiplicity as 0, and the fact that Draft has-a body only implies that when I delete this draft, its body also gets deleted as well and not the other way around.


Hope these helps.

**Comment by emmannyyy** [comment]
I think the reason why there is no association line drawn between History and ActionX/Y lines is because Action X/Y are stored as Repeatable objects.  History class thus only depends directly on the Repeatable class, given the method signature of add(Repeatable). This makes the UML diagram less cluttered, and more generalised, as any Repeatable object can be added to the History object. 

Regarding the email and body, since a "body" cannot exist without an email, the composition makes sense. However, the multiplicity of 0..1 indicates that an email can have no body. (e.g: imagine sending an email with just the title and no body, it would still work). Composition still makes sense, its just that the parts (i.e: body) cannot exist without the whole (email).

**Comment by flyingsalsa** [comment]
Task can only navigate to the Repeatable class not the Action class as seen from the method signature of in the Class diagram being Task(Repeatable Task), what the actual type of the Task is isn't reflected since it is taken in as a Repeatable. This is different from an object diagram where we just directly show what object is being put inside since clarifying it is identified as a Repeatable in the :Task would be extremely messy and confusing as it might be interpreted as a new object rather than the same one but identified as a different a Type

Composition allows 0 since it's only a one-way thing. The parent Class may or may not have it's children-Class(es) but the child classes Cannot exist without the parent class

**Comment by damithc** [comment]
> Composition allows 0 since it's only a one-way thing. The parent Class may or may not have it's children-Class(es) but the child classes Cannot exist without the parent class

@flyingsalsa Slightly rephrased, to avoid confusion with inheritance:

The _whole_ class objects may or may not have it's _part_-class(es) objects but the _part_ class objects cannot exist without the _whole_ class object
