### ISSUE TITLE
Failed test cases from the iP repo for iP evaluation

### ISSUE THREAD

**Issue by MAOXIONGKAI** [nus-cs2103-AY2425S1/forum#475]
Hi prof, I am currently going through the code of iP project that I was assigned through the email, but I have stuck at the part of checking **test & exceptions** because the situation is bit complicated and I would need advice on how to evaluate the work...

Basically, the test case files are not inside a package called test and instead they are under the respective package of the files that they test against(like TaskListTest.java is together with TaskList.java in the same package). As a result, when gradle runs, the tests are not triggered because gradle couldn't find the source to run the test. (As you can see, the test task is not run at all and gradle indicate the reason as no source)
![image](https://github.com/user-attachments/assets/908ea321-c3db-4ff1-b3a2-10b5966618c4)

I am not sure if the above issue is a big deal, but when I try to clone this repo and run the test cases locally, I realized there are actually test cases that failed. 
![image](https://github.com/user-attachments/assets/5b23483d-88ea-4233-842c-1cb7d7e7f392)

I feel like if everything is like this then the test cases are not properly written and no longer serves the purpose. I have tested the product and it works fine but I think the test is implemented very poorly. In this case how should I grade this project? Should I give 0 because the test cases do not serve the desired purposed, or should I give 1 since there are at least 1 or 2 methods tested for each class? Thank you prof for your time!

**Comment by damithc** [comment]
> Should I give 0 because the test cases do not serve the desired purposed, or should I give 1 since there are at least 1 or 2 methods tested for each class? 

@MAOXIONGKAI Thanks for checking so diligently. Yes, it seems the author didn't quite 'get' how to use tests, so you may give 0. Later, we'll give the author another chance to rectify this and get full marks -- so don't worry about affecting their marks.

To clarify, it is common practice (and we recommend) to put the Test class and the SUT class in the same package (so that the test class has better access to members of the SUT class). In addition, Gradle conventions require test classes to be in separate `test` folder (so, different folder, but same package). More info https://se-education.org/guides/tutorials/junit.html#conventions-to-follow

**Comment by MAOXIONGKAI** [comment]
@damithc Thank you prof for the help and the clarification on the test conventions! 😄
