### ISSUE TITLE
UML Class diagram: Is it compulsory to show parent methods in subclasses?

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#478]
I am following through the videos for week 8's topic, and I have a question.

When drawing the UML, it is compulsory to draw the read() function for all the subclasses(email, textMsg, FBMsg)? Since Message class already defined read() method and the three classes extends from it, must the read() method be written down for each of the subclasses?
![image](https://github.com/user-attachments/assets/3a51c599-73d8-44d8-abcd-188d6f30505f)

**Comment by MAOXIONGKAI** [comment]
Hi, sorry if I misunderstand the question or just mentioning the obvious parts which you may have already take into considerations, but from prof's explanation in the video(at 06:47), the read() methods are repeated in the child classes because they are implemented differently from the parent class(overriding parent implementation instead of just inheriting from the parent class). On the other hand, if the read() method is just inherited then we should not include them. 

You can also refer to diagrams that are included in the course material under the inheritance UML class diagram section to check this out. For example,
![image](https://github.com/user-attachments/assets/32a60119-b1bc-4b22-9d4c-00bf9b4f2bb9)

In this case, the Car class does not need to include the fields and methods inherited from Vehicle, assuming that Car does not override them.

**Comment by Feng1231** [comment]
Oops seems like I missed out on that part. Thank you so much 😃

Would we be penalized if we included the fields and methods inherited, when they are not overridden?

**Comment by damithc** [comment]
> Would we be penalized if we included the fields and methods inherited, when they are not overridden?

@Feng1231 Yes, that will be considered incorrect. Include a method only when it is override/implemented in that class.

**Comment by Feng1231** [comment]
Noted. Thank you for the quick clarification!
