### ISSUE TITLE
Working on the same feature in a pair

### ISSUE THREAD

**Issue by adipanda2002** [nus-cs2103-AY2425S1/forum#479]
I am working with one of my teammates for one of the features our team has decided to add to AB3 this week.

We're slightly unsure about how to go about the tp workflow in this context.

My initial thought was to a create a branch called 'add-said-feature', commit a small bit of code that doesn't break the 
team repo, and create a PR. There would then hopefully be a way for my teammate to track this branch and make his changes to it and update the same PR. Then we could simultaneously communicate to incrementaly integrate the feature bit by bit. Is there a way to do this? Is this even aligning with the required workflow for the tp right now?

Another thought was to create branches for these bits and pieces of each feature. For instance, I would create a branch called 'add-said-feature-step1', commit and get it merged. Then my teammate would push the branch 'add-said-feature-step2' and get it merged, and so on. All these branches would have to make sure they don't break the code in the main repo.

**Comment by damithc** [comment]
> I am working with one of my teammates for one of the features our team has decided to add to AB3 this week.

@adipanda2002 Ideally, each person should work on a separate feature. Members working on closely related features can collaborate more (e.g., review each other's PRs) without working on the same feature at the same time. If MVP features are fewer than team members, you can add more features to the MVP so that there is enough features to be divided among members meaningfully.

The other option is the 'feature branch' approach. That is, create a separate branch for the feature -> members working on this feature will branch off from this branch, and create PRs against this branch -> when the feature is ready to be merged to the master branch, you create a PR from the feature branch to the master branch. 
However, this option strays towards the depth-first iterative approach, so not ideal (but allowed) for the tP. Use in moderation if you must.

**Comment by adipanda2002** [comment]
Thanks Prof, we've added features to work on so there aren't fewer MVP features than members.
