### ISSUE TITLE
Code conventions for the switch case.

### ISSUE THREAD

**Issue by zaidansani** [nus-cs2103-AY2425S1/forum#49]
Hi, the following is shown on the coding conventions site.

![image](https://github.com/user-attachments/assets/a30d8512-2311-4bd6-9168-6db1f54d70a0)

Is it then to be assumed that we should not use the arrow-case notation for our projects? Would like to clarify this!

---

> The notation is new to Java 17, and thus postdates the style-guide. 

From the discussion below, the agreed conventions are as follows:

Using the arrow-notation:
```Java
TaskType taskType = switch (data.charAt(0)) {
    case 'T' -> TaskType.TODO;
    case 'E' -> TaskType.EVENT;
    case 'D' -> TaskType.DEADLINE;
    default -> TaskType.UNKNOWN;
}; 
```

(without an assignment)
```Java
switch (data.charAt(0)) {
case 'T' -> functionT();
case 'E' -> functionE();
case 'D' -> functionD();
default -> functionDef();
}; 
```

**Comment by WeiHanWong** [comment]
The arrow-hand case notation is a shorthand notation. If you indent the cases right, it still conforms to as mentioned coding standard.

**Comment by michaelyql** [comment]
I'm using switch expressions in my code - in this case, what would be the correct way to indent the case statements? 

Example:

```java
TaskType taskType = switch (data.charAt(0)) {
                    case 'T' -> TaskType.TODO;
                    case 'E' -> TaskType.EVENT;
                    case 'D' -> TaskType.DEADLINE;
                    default -> TaskType.UNKNOWN;
}; // how should this closing curly brace be indented?
```

or 

```java
TaskType taskType = 
    switch (data.charAt(0)) {
    case 'T' -> TaskType.TODO;
    case 'E' -> TaskType.EVENT;
    case 'D' -> TaskType.DEADLINE;
    default -> TaskType.UNKNOWN;
};
```

Or are both acceptable?

**Comment by damithc** [comment]
@zaidansani thanks for raising this. Thanks others for the inputs so far.

Our coding style guide predates this new switch-case syntax. Our recommended fall back is the [Google's Java style guide](https://google.github.io/styleguide/javaguide.html) which doesn't seem to mention it either.
So, you all can discuss and decide on a suitable style for this that is reasonably aligned with the rest of the style guide.

**Comment by zaidansani** [comment]
@damithc Interesting. Thanks.

In my opinion, I feel both styles should be allowed. Particularly, I personally feel the shorthand notation is extremely readable when the switch case is responsible for calculating a value for a certain variable.
 The `case` indentation should remain the same regardless.

Personally, I find that the following format is the most readable (using @michaelyql's example), where the switch case follows right after, with everything inside the code block having an extra indent (because it's technically a continuation of the statement above).
Having the case being at the exact same indentation as the actual `switch` statement will cause issues with too much characters per line if the variable being assigned has a long name for example.

```java
TaskType taskType = switch (data.charAt(0)) {
    case 'T' -> TaskType.TODO;
    case 'E' -> TaskType.EVENT;
    case 'D' -> TaskType.DEADLINE;
    default -> TaskType.UNKNOWN;
};
```

Would like to hear input on this as well!

**Comment by michaelyql** [comment]
@zaidansani 

I think your indentation example makes a lot of sense, and I think any regular JS/TS/React users (including myself) would  appreciate the familiarity of the indentation style (it looks just like any other arrow function). So I agree with your idea on this one. 

I would recommend anyone pondering about this issue to stay away from the first example that I showed. As Zaidan mentioned, if the variable name we are assigning to is very long, the case statements that have to align to the start of the switch statement will have a lot of leading whitespace, which I find only adds more mental load to the reader.

Furthermore, it would mean that different switch expressions would have different levels of indentation for their case statements, since the start of the switch statement depends on the length of the variable we're assigning to. It would be very difficult to align the case statement indentation across multiple switch expressions, let alone just two.

**Comment by zaidansani** [comment]
@damithc Prof, should I close this issue? It seems like there is a consensus found so far.

**Comment by damithc** [comment]
> @damithc Prof, should I close this issue? It seems like there is a consensus found so far.

Sure @zaidansani 
You  can also update the initial post to mention the consensus, for easy reference of others.
