### ISSUE TITLE
Possible bug in javadoc comment of JsonAdaptedPerson class

### ISSUE THREAD

**Issue by Soumyadip-cmd** [nus-cs2103-AY2425S1/forum#491]
![image](https://github.com/user-attachments/assets/2a216cff-0ee5-4526-833a-069a646c3c99)
May I know if the 'Jackson-friendly' in the javadoc comment intentional or if it is supposed to be 'Json-friendly'?

**Comment by AbdulrahmanAlRammah** [comment]
"Jackson is a suite of data-processing tools for Java (and the JVM platform), including the flagship streaming JSON parser / generator library."

If you do shift shift (search all) and type jackson you will see we import classes related to jackson.

**Comment by damithc** [comment]
Good observation. Let's try to figure out if this was intentional or a typo. On a general note, this is a good opportunity to learn how to investigate 'odd' things you encounter while working in a brownfield project.

Things we can do:

* Search the entire code base for other mentions of `Jackson`
* Use Git/GitHub 'blame' feature to see which commit added this line, and check the commit message of that commit to see if it mentions anything about this.
  ![image](https://github.com/user-attachments/assets/73e3e284-5181-4383-9069-21e55d678b2c)

**Comment by Soumyadip-cmd** [comment]
Thank you for your reply @damithc and @AbdulrahmanAlRammah . I see now that it is intentional
