### ISSUE TITLE
Question about parallel paths

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#497]
I am reading through the topics for week 9.
![image](https://github.com/user-attachments/assets/b83e507d-d466-414b-827b-714d4bde19a6)
It is stated that parallel paths should end in the same join node.

What about the following flow?
```java
CompletableFuture<Type> f = CompletableFuture.anyOf(
    CompletableFuture.runAsync(() -> method1()),
    CompletableFuture.runAsync(() -> method2())
).thenApply(_void -> result());
```

This code waits for **one of the two** parallel path to complete, and proceed with the next action.

**Comment by damithc** [comment]
@Feng1231 Good question.

Parallel paths are not the same as asynchronous paths. In the scope of our course, we only use parallel paths. 

When we face a situation in which we want to model a complex situation that is not covered by the notation covered in the course, here are some options we can consider:

* Use the closest matching notation, and use UML _notes_ to provide the missing information
* Instead of using a UML diagram, use an alternative means to communicate e.g., pseudo code, or even actual code
* Leave out the complex part from the diagram, or give a simpler view in the model, if the complex part is not really relevant to the purpose of the diagram (but also mention that the model is a simplified view)

**Comment by Feng1231** [comment]
I see. Thank you prof for the insights!
