### ISSUE TITLE
Clarification on law of demeter

### ISSUE THREAD

**Issue by NorbertLoh** [nus-cs2103-AY2425S1/forum#511]
Hi Prof I would like to clarify my understanding of the law of Demeter.
for example:
```java
class lesson {
    Person person
    public String getPerson() {
        return person;
    }
    
    public String getPersonName() {
        return person.getName().fullname;
    }
}
```

example 1: `lessonExample.getPerson.getName().fullname`
Would this violate as we are accessing full name which is not a direct association of lesson?

example 2: `lesson.getPersonName()`
I am also unsure whether this violates LOD even though we are only calling directly associated object methods.

Thank you!

**Comment by damithc** [comment]
Good question, @NorbertLoh 
Let's wait a while to give others some time to chime in.

**Comment by yadobler** [comment]
I think no2 does not because the interaction with Person is encapsulated within the method (ie it's the lesson's problem to settle with its friend), and any method calling lesson only needs to deal with lesson's `gerPersonName` method without having to go behind the friend (lesson)'s back to talk to person and get the name

No1 would, cos you're talking to your friend (lesson)'s friend (person)

-----

That being said I think in both examples, `getName().fullname` is a bit antipattern. It's not Slapping hard and it's accessing field members is a big nono, especially if FullName might change or depend on object state. 


Actually I think it's also violating the Law of Damither cos "getName" returns what I assume is a `Name` object which contains the field `fullName`.

Best to have Person give the full name itself. Like `Person::getFullName`.

Actually the `getPerson` method itself is misleading, it's really doing a `getPerson().toString()` but I think that's OK because again it's encapsulated within the friend method without exposing the friend to the other friend.

`person.getName().fullname` feels like person is exposing their friend (name) to the other friend (lesson)

----

But it's all design pattern I guess. I don't know if maintaining decoupling outweighs the extra method in Person - I guess it would if that's the only reason why Lesson has to know what `Name` does. If it is already coupled for other reasons then I think the three of them are all good friends with each other and


----

That being said, if a friend of Name and Lesson does a `lesson.getPerson().getName().fullName()` **which will not work BTW because getPerson returns a String not Person**, but assume it returns Person, it will violate SLAP

And I guess if one day you decide this popular mutual friend decides to ditch `Name`, it will need to still be coupled with `Name` because both `Lesson` and `Person` aren't helping it and is forcing it to deal with `Name` directly.

Sad

**Comment by NorbertLoh** [comment]
Yea I agree that accessing object fields directly seems wrong however it was implemented this way in AB3 which made me raise this question.

However, good catch on example 1 not slapping hard!

Thank you!

**Comment by damithc** [comment]
Good discussion 👍 Let's keep this open for a while longer, for the benefit of others. 
Some additional points:

* An example of LoD is discussed in this week's briefing. So, lookout for that as well.
* Why do you think there is a SLAP (as defined in [here](https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/chapters/codeQuality.html#slap-hard)) issue in this code?

**Comment by somethingfishyfishy** [comment]
> It's not Slapping hard and it's accessing field members is a big nono, especially if FullName might change or depend on object state.

I dont think not "SLAP"ping hard is the biggest issue, it is also not relevant in answering whether it violates LOD. Also as prof mentioned, how are you evaluating for SLAP? These are all single line return statements for the methods, unless you're referring to the examples themselves which without the body of the code, there is nothing to reference to evaluating SLAP. 

In answering Norbert's question, one tip to see if you violate LOD is to ask, (as a XXX object) am I accessing my own attributes or am I attempting to access other's attributes or methods?

Let's break down example 1 (example 2 is the same concept of example 1 except the client is doing less work)
> `lessonExample.getPerson().getName().fullname`

- lessonExample.getPerson() // returns a Person object, the object is an attribute stored within the Lesson object (lessonExample)
- .getName() // returns a Name object, thats within the Person object, at this point not violating LOD, depends on what you do after
- .fullname // accessing the attribute of the Name object (exposing information which shouldn't happen), violates LOD

I want to point out that in example 2 -- put yourself in the shoes of a Lesson object and now you're the client interacting with a Person object. In this case you're asking for the attributes from the Person object (and subsequently tearing information out), instead of telling the Person object to provide the information you need.

As Yadobler mentioned, the Person class should have a method that provides what you need (fullname), instead of allowing other classes to reach into the Name attribute and take the information.

How does this look like?

```
class Lesson {
    Person person;
    // constructor and other methods
    String getPersonName() {
        return this.person.getFullName();
    }
}
```

```
class Person {
    Name name;
    // other methods
    String getFullName() {
        return this.name.getFullName();
    }
}
```

```
class Name {
    String fullname;
    // other methods
    String getFullName() {
        return this.fullname;
    }
}
```

In a closing note, the tell-dont-ask principle goes hand-in-hand with LOD, and as much as possible, you should redirect tasks to your attributes instead of plucking information out and doing it yourself.

**Comment by damithc** [comment]
As @somethingfishyfishy mentioned, the original code example is not particularly related to SLAP, as there are no mixing of multiple levels of abstractions.

@NorbertLoh  any further queries about this? If not, you can go ahead close this issue.
