### ISSUE TITLE
tP: Feature Implementation Question

### ISSUE THREAD

**Issue by InfinityTwo** [nus-cs2103-AY2425S1/forum#528]
Hi all, can I check for tP feature implementations, are we allowed to make it such that changing frontend (modifying the UI/UX) is a (big?) feature that we can do for post-MVP milestones?

Edit: Does it also count towards the final effort grade if we do?

**Comment by damithc** [comment]
> Hi all, can I check for tP feature implementations, are we allowed to make it such that changing frontend (modifying the UI/UX) is a (big?) feature that we can do for post-MVP milestones?

@InfinityTwo If the UI change is not essential for the MVP, it can be done after releasing the MVP. However, if one of your MVP features can't be used because the UI hasn't been updated to match, the MVP will not be considered 'delivered', and it is not breadth-first either.


> Edit: Does it also count towards the final effort grade if we do?

Yes, UI enhancements will be counted. Also see the below (from [this page](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-expectations.html)):

![image](https://github.com/user-attachments/assets/4ad12e07-2ed7-431f-b773-70079386fa23)
