### ISSUE TITLE
Will CI failing result in penalisation?

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#531]
Hi, my team is currently preparing for v1.3 and our CI is failing due to our latest PR (we just fixed a function and have not added test cases for it).

We have also consulted the course website, particularly [this](https://nus-cs2103-ay2425s1.github.io/website/admin/appendixC-faq.html#faq-pr-ci-fails-because-codecov-reports-a-drop-in-code-coverage-what-to-do).

Can we check that we won't be penalised for our CI failing in the v1.3 submission, and by extension even during the final submission?

**Comment by damithc** [comment]
@ghos7ie there is no penalty for failing CI occasionally, but do try to keep it passing most of the time, and when it fails, get it fixed as soon as possible.
CI failing due to coverage drop is less problematic but failing due to other issues (e.g., a test is broken, or a checkstyle failure) should be fixed quickly enough. Otherwise we can't verify that you have learned how to leverage CI to your advantage, which is an intended learning outcome.

**Comment by ghos7ie** [comment]
Hi Prof, thanks for the answer. Our CI failing was due to coverage drop :)
