### ISSUE TITLE
Create a merge commit VS fast-forward

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#55]
I am quite confused between the 2 concepts. I briefly understand the concept of fast-forward which just moves the HEAD pointer to the latest change in another branch, provided that there is a linear path to this branch. But, I don't understand how to create a merge commit nor the difference between the 2 concepts. Any help is appreciated, thanks!

**Comment by Incogdino** [comment]
A fast forward merge happens when the master branch (or any other branch) have not changed from the branch you are merging to. In this case, git just moves the master branch to the same commit as the merging branch. 

A merge commit happens when both the master branch and merging branch have different unique commits. Instead of just moving the master branch forward to the merging branch, git will "merge" both branches as a new commit. This new commit will have two parent commits, one from each of the branch. 

Here is an image I found online that illustrates this 
![image](https://github.com/user-attachments/assets/e7168419-24b3-4bda-a8a0-3904ec7a3641)


I guess the only difference here is that a new commit is made whenever a merge is done for merge commits while fast forward will not have a new commit. 

To my knowledge, this is what happens. Hopefully it answers your question. Please correct me if I'm wrong.

**Comment by uniqly** [comment]
I think what @Incogdino has said is pretty much the gist of it. 

One point not that was brought up but not explicitly mentioned by @Incogdino is that git prefers to a do fast-forward merge (if possible) over a regular merge commit when using the `git merge branch_name` command and using the `--no-ff` flag forces git to create a merge commit; if you have two branches which both already have additional commits, `git merge` will create a merge commit as it is not possible to do a create fast-forward merge.

I think the video in the topics section ([Tools -> Git and GitHub -> branch: doing multiple parallel changes](https://nus-cs2103-ay2425s1.github.io/website/schedule/week3/topics.html#tools-git-and-github-branch-doing-multiple-parallel-changes)) is pretty good in explaining how to do both types of merges using SourceTree. If you prefer to use the git CLI you can refer to `CLI` tab in the text sections or you can search for the multiple available videos on this topic on Youtube.

**Comment by rayray39** [comment]
Thanks guys for the help, I have a clearer understanding now!
