### ISSUE TITLE
Equivalence Partitioning

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#560]
Just to check, for the forth example ["F"], why can't "E" or "G" or perhaps "f" be considered a specific boundary to test?

<img width="705" alt="Screenshot 2024-10-23 at 12 39 28 PM" src="https://github.com/user-attachments/assets/f90b3442-2bca-453e-9c89-818866a61c32">

**Comment by damithc** [comment]
Good question @JagdeepSinghNUS 
Let's wait to see what others have any thoughts on a possible explanation..

**Comment by shotnothing** [comment]
I think it depends on the context, but 'E' and 'F' are not really adjacent in any sense other than ascii code (and I don't think it's common to use the ascii code form in a for-loop for example), so I couldn't consider them boundaries.

**Comment by Incogdino** [comment]
In my opinion, there is no clear boundaries specified by the equivalence partition for this case (as well as the one for prime numbers and "A", "D", "X"). I think for one to do boundary value analysis, the equivalence partition needs to have a continuous range of values for us to properly define a boundary. 

Perhaps testing "E", "F" and "G" falls under a different name of testing.

**Comment by jagdeepsh** [comment]
Nice, I now have a better understanding of this, thanks :)

**Comment by damithc** [comment]
Good answer @Incogdino 
@JagdeepSinghNUS Strictly speaking, we can't be 100% sure without further contextual info but it is unlikely `E` and `G` are _adjacent_ to F in a way that the programmer makes an 'off by one' mistake to accept them instead of F (which is the type of errors boundary values catch).
`f` is certainly a good test case, but we can't call it a boundary value.
