### ISSUE TITLE
Clarification regarding TP UML diagrams

### ISSUE THREAD

**Issue by AbdulrahmanAlRammah** [nus-cs2103-AY2425S1/forum#564]
For week 10 tp progress we are expected to modify the UML diagrams in accordance to our changes. The changes I made were allowing multiple deletion and creating a SortCommand that sorts the addressbook. To do these changes I only created new PersonComparator and IndexComparator classes. These classes have nowhere to be placed in the current DG. 

However, it seems we are expected to make a change anyways, so how shall I proceed? In particular, looking at the criteria it is bad to include to much information in the DG, so it maybe inadvisable to create a diagram just for the sake of showing diagram skills. On that note, I also want to ask if the AB3 DG diagrams are considered comprehensive or if there are things to be added (neglecting features added by us).

**Comment by damithc** [comment]
@AbdulrahmanAlRammah While it is recommended to keep documentation minimal yet sufficient in a real project, in a course project it is also important for us to be able to assess if students have learned all skills covered by the course. So, if your coding work doesn't affect diagrams, you can consider adding diagrams for a proposed feature so that you get a chance to show your diagramming skills. 
Also, it may be a sign that your implementation work didn't go deep enough, although this is not always the case.
