### ISSUE TITLE
Browser used for CATcher

### ISSUE THREAD

**Issue by JoanneHing** [nus-cs2103-AY2425S1/forum#568]
<img width="722" alt="Screenshot 2024-10-23 at 11 38 24 PM" src="https://github.com/user-attachments/assets/8ce8e368-6ec0-4aa9-a551-f69d4fb1f2bc">

I am using Arc as my default browser, is Arc a allowed browser to be used? Or do I need to switch to Chrome?

**Comment by damithc** [comment]
@JoanneHing Allowed but use at your own risk, as we have not tested CATcher on Arc.

**Comment by JoanneHing** [comment]
May I ask what would be the possible issue that could happen?

**Comment by damithc** [comment]
> May I ask what would be the possible issue that could happen?

We don't know, because we didn't test :-)
For example, it might not have support for some non-standard functionality that is used by CATcher and present in the listed browsers. Unlikely but can happen. And if you run into some issue (e.g., keeps getting logged out automatically) during the PE which might be unrelated to Arc, you'll still wonder if it is the Arc browser causing that issue, and will have to try another browser to double-check, wasting precious PE time.

**Comment by JoanneHing** [comment]
I see your point here Prof! Thanks for the clarification!
