### ISSUE TITLE
Confused for the suggested project structure in AddressBook-2

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#57]
Hi. According to the A-OOP in week 3, I can get some inspiration of the organization of code from addressbook-level2. 

However, I am quite confused as it is very different from what we have forked for IP.

As shown below, my file structure is currently `src/main/java`
![image](https://github.com/user-attachments/assets/873fb76c-f2e4-4df6-b67f-1f2acea05e1d)
Under java, it contains all the java classess that I have not packaged yet.
One thing I have noted is that there is no `Main.java` file.

In addressbook-level2, however, the file structure is `src/seedu/addressbook`
![image](https://github.com/user-attachments/assets/63564d81-f954-4a72-b6ed-eed29111a01e)

Under addressbook, there are different packages and a `Main.java` file , which is not the case in my file structure.
I was wondering 

1. why there is no `/main/java` folder in the addressbook-level2's file structure? Is the `main/java` folder needed for compiler to compile java files or can I rename it to other names? According to [maven's suggested project structure](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) i found online, there is a `/main/java` folder too. 
2. It seems like the `Main.java` in addressbook-level2 contains the main logic, where in my file structure, `Duck.java` contains the main logic of the application. In the case where I wish to follow addressbook's file structure, do I remove `Duck.java` and move it's code into `Main.java`?

**Comment by damithc** [comment]
@Feng1231 The intention of that instruction was for you to get _inspiration_ from (i.e., get ideas from, not necessarily copy exactly) its _OOP usage_ i.e., the class structure (not the file/folder structure).

The duke folder structure is in the current way so that you can easily adopt the Gradle tool for build automation, which expects the code to be in the `src/main/java` folder. However, this is not a fixed rule -- different projects can use different location as their 'source folder'. Apparently, addressbook-level2 (AB2) uses `src` as its source folder. 

So, there's no need to change your project folder structure or filenames to match AB2 exactly.

**Comment by Feng1231** [comment]
Understood, thank you prof!
