### ISSUE TITLE
Level-7: Clarification on when to write to file

### ISSUE THREAD

**Issue by matchastack** [nus-cs2103-AY2425S1/forum#58]
According to the Level-7 task description, "Save the tasks in the hard disk automatically whenever the task list changes."

May I ask if it is necessary to write to file whenever the user add, mark, unmark, delete a task? I think it is quite inefficient to write to file for every change as I/O operations are slow. Is it ok for my implementation to be such that the tasks are only saved to file when the user exit the program (ie. `"bye"`).

**Comment by damithc** [comment]
@liauzhanyi This is a good point for discussion. I'm glad you raised it.
You all can discuss pros and cons of each each alternative (you listed two, but there are others)  and choose the one you think the best. When making this decision, consider the impact on user experience as well.

**Comment by Incogdino** [comment]
I feel that writing to the file at every change can ensure that if the program terminates for any reason apart from the "bye" command, the previous tasks added are saved locally which can then be retrieved again on launching the program.

**Comment by matchastack** [comment]
@Incogdino I think that is a valid concern. However, considering that a program crashing due to Exceptions is not supposed to be a frequent occurrence, the only other reason I can think of right now where a program terminates without `"bye"` is when the user close the terminal (similar to clicking "X" on a window when the app has a GUI). 

Not sure if there is a better way to save the data, but I am current storing it in a `.txt` file with `','` delimiter. 
ie.
```
T,0,borrow book
D,1,return book,Sunday
E,0,project meeting,Mon 2pm,4pm
...
```

suppose the task list were to get large, and I were to update the file for the 30th item out of 100, there is no way (I don't think so?) to selectively change that particular line other than rewriting all the other tasks again. That would mean not just the writing to file but also looping through `n items` in my `ArrayList` and appending them to string (at least for my implementation).

If we have to account for the unexpected termination of program, I think a `save` command feature might be a way to mitigate such situations, though not a direct solution as it does not solve the issue of "unexpected".

**Comment by RezwanAhmed123** [comment]
Personally while I do think it may be a little slower than normal, I would just do a refresh (rewrite everything on the file from scratch) every time I mark/unmark or delete things from the app. While there are concerns, like it’s slower than other methods, at this stage, I hardly think there’s going to be much lag especially cause in a reminder app such as this, the list would not run into the millions (which seems impractical), at which point only, it would take a very long time to load and unload.

Another benefit of running a refresh would be, catching any corrupted files in between, should the file be tampered with while the app is open.

Moreover, it makes the implementation a lot easier saving you a lot of development time.

Thus, I feel while this may not be the best approach for a different app, for the reasons above I think it would be a good way to implement in this type of app.

**Comment by zaidansani** [comment]
> While there are concerns, like it’s slower than other methods, at this stage, I hardly think there’s going to be much lag especially cause in a reminder app such as this, the list would not run into the millions (which seems impractical), at which point only, it would take a very long time to load and unload.

Agreed. I think with the way Storage is implemented as well, if this needs to be changed, it is not something that is particularly complex, as it would just change when the call to save the file is made.

**Comment by tohhengxing** [comment]
>I think it is quite inefficient to write to file for every change as I/O operations are slow

Unless got few hundred concurrent requests, what are the chances it will actually be inefficient currently? File I/O is already quite efficient (see SQLite).

The value of logging correct atomic transactions seem to outweigh efficiency in this case not only because basically few people are using it, but also the task list is performing the function of book keeping, which is essentially an extremely basic database.

IMO, if you are at the point where speed of I/O operations matter, you can consider offloading that responsibility to a DB solution.

Personally, I just did the minimum to satisfy the requirement.

Edit: Thinking about your question, perhaps a better question to ask is how can i design the code such that I can provide an interface for my code to talk to, such that I don't care about the I/O implementation (algorithm implementation). For that, you can consider some design patterns like Adapter pattern or strategy pattern. But whether or not it is worth the effort to write that into code for a simpler problem like this, is debatable. It depends on your personal objectives.

**Comment by matchastack** [comment]
I see, thanks everyone for your inputs!
