### ISSUE TITLE
Constraints specification in Documentation

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#590]
Usually, all of the constraints to user input are specified in the User Guide so that users can take note.
1. For more programming-wise constraints like **MAX_VALUE** of a parameter, is it necessary to include this in the UG also, given that the message is already specified in the application during usage?
2. In terms of DG, is a part called `Field Specifications` or `Validation Rules` required or the documentation in the source code and note for users are enough?

**Comment by shotnothing** [comment]
I definitely think that `MAX_VALUE` useful information to the user, not just developers, just that it should be phrased in a human-friendly way and not some technical constraint

**Comment by damithc** [comment]
@DennieDan Some relevant info:

![image](https://github.com/user-attachments/assets/42d75ff8-0a07-4dca-87b4-8a6633e796f9)

Similarly, it is fine to document nitty-gritty implementation details in the code rather than the DG, as maintaining duplicate copies of the same information is error-prone and unnecessary work. 

In general, the DG is expected to provide minimal yet sufficient guidance  for developers, serving them in the following ways:
* It complements the code, providing info/perspectives not specified in the code (e.g., rationale for high-level design choices, details of dev ops) or not easy to grasp from the code (e.g., architecture level view, visual models)
* It act as a starting point for developers, before they can dive into the code itself e.g., by providing an architecture-level overview of the system
* It provides a roadmap to developers e.g., pointing out where important information can be found in the code

**Comment by DennieDan** [comment]
> I definitely think that `MAX_VALUE` useful information to the user, not just developers, just that it should be phrased in a human-friendly way and not some technical constraint

Thank you so much for your input!

**Comment by DennieDan** [comment]
> @DennieDan Some relevant info:
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/42d75ff8-0a07-4dca-87b4-8a6633e796f9)
> 
> 
> 
> Similarly, it is fine to document nitty-gritty implementation details in the code rather than the DG, as maintaining duplicate copies of the same information is error-prone and unnecessary work. 
> 
> 
> 
> In general, the DG is expected to provide minimal yet sufficient guidance  for developers, serving them in the following ways:
> 
> * It complements the code, providing info/perspectives not specified in the code (e.g., rationale for high-level design choices, details of dev ops) or not easy to grasp from the code (e.g., architecture level view, visual models)
> 
> * It act as a starting point for developers, before they can dive into the code itself e.g., by providing an architecture-level overview of the system
> 
> * It provides a roadmap to developers e.g., pointing out where important information can be found in the code

I got what you mean. Thanks for your reference to the website, Prof!
