### ISSUE TITLE
How to generate TOC for User Guide?

### ISSUE THREAD

**Issue by ghos7ie** [nus-cs2103-AY2425S1/forum#600]
I am currently trying to update my team's user guide and was hoping to follow some aspects of AB3's user guide.

However, the following code does not print out the TOC.
```md
<!-- * Table of Contents -->
<page-nav-print />
```

Similarly, following the way AB3 [does it](https://github.com/nus-cs2103-AY2425S1/tp/blob/master/docs/UserGuide.md) by using `{:toc}` does not work and will result in the UG page not rendering.

Has anyone managed to automatically generate their TOC?

**Comment by damithc** [comment]
@ghos7ie Are you using MarkBind or Jekyll?

**Comment by ghos7ie** [comment]
Hi @damithc, my group is using MarkBind. Is auto-generation possible? Or do we have to write out the TOC ourselves?

**Comment by damithc** [comment]
@ghos7ie IIRC, `<page-nav-print />` auto-generates a TOC when you print or save as PDF, but it doesn't generate one in the web page (because the web page already has a page navigation menu on the right edge).
You can test that theory by saving the page as a PDF, the way you are supposed to convert UG/DG into PDF files.

**Comment by ghos7ie** [comment]
thanks prof! I didn't realise that was the purpose of that snippet

I also didn't see there's a side toc already automatically generated on the site since my browser was only half sized
