### ISSUE TITLE
Is bad UI considered a bug / feature flaw? 

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#620]
For instance, if the user inputs a really really long text (longer than usual, e.g. for name) and the full text is not shown on the window (i.e. it's shown partially with elipses at the end). Or the text is wrapped around which makes the particular contact shown as longer than the other contacts. Is this considered a bug or feature flaw? Since it does not affect using the app at all, just that the UI may not look good.

**Comment by damithc** [comment]
@annabellekk In [the week 11 Project page](https://nus-cs2103-ay2425s1.github.io/website/schedule/week11/project.html), you can refer to the following panel (expand the panel and search for `Problems caused by very long input values`):

![4502](https://github.com/user-attachments/assets/087f2b80-f712-411a-9ed9-ed28980276dc)

If you are wondering if this is something you can defer to v1.6, you can refer to the following panel (in the same page) to decide if this qualifies as a bug that is allowed to be fixed during the feature freeze.

![86941](https://github.com/user-attachments/assets/a0f946fc-86c4-41b0-bc70-1b1e3a7b5117)

**Comment by annabellekk** [comment]
Thank you prof
