### ISSUE TITLE
Update UG in v1.6

### ISSUE THREAD

**Issue by KiKuasaurus** [nus-cs2103-AY2425S1/forum#621]
Will we be allowed to update the ui of the UG or DG after v1.5, such as making cosmetic improvements for the organisation of the data.

**Comment by damithc** [comment]
@KiKuasaurus Not sure what you meant by 'ui of the UG' (screenshots?). Anyway, what is allowed and not allowed in v1.6 is described in https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html

**Comment by KiKuasaurus** [comment]
I'm trying to ask if we can change the format of the UG in the website in v1.6 such as the styling and alignment of the screenshots. I have looked at the linked page and it does say that UI changes are not allowed but UG/DG changes are. Can i assume that the UI changes mentioned refers to the ui of AB3 and not the website?

**Comment by damithc** [comment]
> Can i assume that the UI changes mentioned refers to the ui of AB3 and not the website?

@KiKuasaurus Yes, UI refers to the UI of the app, not UI screenshots in UG or DG. Anything in the UG or the DG can be changed during v1.6.

Caution: The more you plan to change UG/DG during v1.6, the less useful the PE-D will be to you (because the PE-D bugs will be reported against a UG/DG that will be changed later).

**Comment by KiKuasaurus** [comment]
Thanks prof! The changes will probably be minor cosmetic changes but they do affect the UI of the UG and DG thats why i wanted to confirm it was fine first.
