### ISSUE TITLE
Clarification on what constitutes a bug or feature flaw

### ISSUE THREAD

**Issue by IzN432** [nus-cs2103-AY2425S1/forum#632]
Our app has a sorting feature. Currently, it sorts by ascii value instead of by alphabet. i.e a > B instead of a < B (ignore case). Is this counted as a feature flaw (subject to the feature freeze), or a bug that can be fixed?

**Comment by Runus01** [comment]
The FAQs section under Wk 13's Project section may be helpful. Particularly, Q1 and Q2.

https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html#1-fix-pe-d-bugs

Tldr, you just need to see if the actual behavior differs from the behavior advertised in your user guide. If it differs, you could update the user guide as though it is a documentation bug. (Which is allowed)

Alternatively, if your team believes it is more appropriate to sort it alphabetically instead of by ascii value, you could add this feature fix as an item in the Planned enhancements DG section. Then, if the feature flaw were to be reported during the actual PE, you can successfully argue that it is 'not in scope'.

**Note to us all: If we report any feature flaws that are 'not in scope' (according to DG's Planned enhancements section) we will only earn partial credit.** :"")

**Comment by ghos7ie** [comment]
My group had this sort bug as well, and after reading through the FAQ multiple times, it seemed like fixing the bug is allowed. But reading it again after seeing @Runus01's comment, I think we are not allowed to fix it?

I think the FAQ has been worded rather confusingly, my confusion comes in from the highlighted part below here that seems to contradict what is mentioned at the start of the section.
![image](https://github.com/user-attachments/assets/a0593b55-f661-4441-b892-05d990b406ff)

Does this mean that if my group realised that the sort commands were sorting by ascii but tried to bug fix it to sort by alphabetical order before v1.6, then we are allowed to fix this bug? 
Or does it mean that since we intended to sort by alphabetical order, but it doesn't work as such so we are allowed to fix it?

Perhaps the teaching team can update the Fixing PE-D bugs section to explicitly state what kind of bugs can be fixed, rather than what is not allowed in future iterations of the course. 

I would argue actually that we should be allowed to fix all bugs, minus feature flaws (aka feature does not support the use case well enough/does not support the user's use case at all).

Since we only have approximately 3 days until the final deadline on Tuesday and groups have to first sift through the issues reported, which might take up to a day depending on number of bugs reported. This will force groups to prioritise fixing of bugs or ensuring their UG/DG are in a usable  state, teaching groups about managing the trade offs.

**Comment by damithc** [comment]
(a) If the current sorting order is sub-optimal (i.e., can be better), update the UG to explain the current limitation and list it as a planned enhancement. 
(b) If the current sorting is 'incorrect' (e.g., values are not sorted at all, or sorts in ascending order when the command is for sorting in descending order), it's a bug that can be fixed in v1.6

This case given here is a match for (a).

**Comment by IzN432** [comment]
Thanks for the clarification prof and those that took the time to respond!
