### ISSUE TITLE
Is editing preferences.json and data file a bug that needs to be resolved?

### ISSUE THREAD

**Issue by PeterHW963** [nus-cs2103-AY2425S1/forum#640]
My tP group received a few bugs revolving editing preferences.json, config.json, and our data file causing our app to be inaccessible or stop working. 

For preferences.json and config.json, we never mentioned in our UG nor DG that they can play around with it. While for our data file, we cautioned users to ensure that they know what the correct format and acceptable parameters are, otherwise they should not edit it. 

Are we allowed to reject these bugs?

**Comment by damithc** [comment]
@PeterHW963 To find if this can be rejected if reported in the PE, you can refer to the 'Guidelines for bug triaging' in [this page](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#pe-phase-2-developer-response).

~~When dealing with PE-D bugs, you can apply the following logic. Feel free to ask follow up questions if not clear/unsure.~~

1. ~~**Does it qualify as a 'bug'**, as defined in [the feature freeze FAQ](https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html)? If yes, you may fix it in v1.6
   If not fixed, it can be reported as a bug in PE, and might result in a penalty eventually. I say *might result* because only when the bug density exceeds a certain bar that bugs will be penalised.~~
2. ~~**Else, is it something you think you'll never fix/change** even if you were to continue this project in future? If yes, you can reject it (in PE-D, and in PE). But if the PE tester disagrees and the teaching team agrees with the tester's justification, the bug might result in a penalty.~~
3. ~~**Else, is it something you can fix/correct in a future version** but not important enough to do in v1.5? If so, you can categorise it as 'not in scope'. As before, the tester might disagree. Look for the 'Guidelines for bug triaging' in [this page](https://nus-cs2103-ay2425s1.github.io/website/admin/tp-pe.html#pe-phase-2-developer-response) to find more about `NotInScope` categorisation.~~
4. ~~**Else, it is something you should have fixed/corrected in the current version.** As enhancements  are not allowed during the feature freeze, your only recourse is to list it under 'Planned Enhancements' in the DG so that it becomes immune to PE bug reporting.~~

See https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html for an updated version of this workflow ...

**Comment by damithc** [comment]
See https://nus-cs2103-ay2425s1.github.io/website/schedule/week13/project.html for an updated version of this workflow ...

![image](https://github.com/user-attachments/assets/0005ee70-36ef-4ddb-8df9-2e001f0a2dea)
