### ISSUE TITLE
Does fixing bugs that are not explicitly implied as a bug count as violating feature freeze

### ISSUE THREAD

**Issue by uniqly** [nus-cs2103-AY2425S1/forum#645]
For example, let's say my team created a command `func` and its usage is documented as `func foo/FOO bar/BAR` in the user guide. 

But in the app because of programming oversight, unexpected behaviour occurs when using duplicated parameters or unnecessary parameters (eg: `func foo/FOO1 foo/FOO2 bar/BAR` or `func foo/FOO bar/BAR baz/BAZ`) and it was noted as a bug by testers.

If we were to fix this bug, would it be counted as violating the feature freeze?

**Comment by damithc** [comment]
@uniqly What's the specific 'unexpected behaviour'?

**Comment by uniqly** [comment]
@damithc The app allows the command to continue but it may not what the user intended to input (eg: app only reads the last duplicated parameter but the user intends for the first parameter to be used)

**Comment by damithc** [comment]
This is not strictly incorrect (so, doesn't qualify as a bug). You can document this behaviour in the UG instead. If you wish to change that behaviour, it can be a future enhancement.

Interestingly, sometime back this was used as a deliberate optimisation in AB3 -- because this behaviour allows the user to correct a mistake by typing the parameter again, which is faster (for a fast typist) than moving the cursor back to the previous parameter location and editing it.

**Comment by uniqly** [comment]
Thanks prof
