### ISSUE TITLE
Tester reports "bug" about validation being too strict

### ISSUE THREAD

**Issue by k-hian** [nus-cs2103-AY2425S1/forum#674]
Basically, we have a data field that only accepts alphanumeric and dashes, and a tester reported that the condition is too strict. Based on the feature freeze, we know we are not allowed to fix this, but should we reject this (for being a suggestion) or accept it as a planned enhancement?

**Comment by damithc** [comment]
@k-hian
1. Unlike the PE, it doesn't matter what you do with the PE-D bug report itself (i.e., we do not check/track your response to them). So, you can respond to them in any way you see fit.
1. Now that you are aware of this issue (thanks to the said PE-D bug report), you need to decide what's the best approach to tackle this in v1.6 so that any potential penalty of this can be minimised/avoided. While it's good to discuss it here, it's up to your team to decide. If a PE tester reports it as a bug later, you'll need to provide your justification and try to convince the tester to agree with your decision.
