### ISSUE TITLE
Is specifying csv file format considered as including UI details?

### ISSUE THREAD

**Issue by Incogdino** [nus-cs2103-AY2425S1/forum#737]
**Use case: UC10 - Import contacts from CSV file**

Our current use case header specifies that the user imports information from a csv file. Would this be considered as specifying Ui details?

Also, in one of our use cases, we mentioned that the contact details will be exported to a csv file. Would this also violate the part on specifying UI details?

**Comment by damithc** [comment]
@Incogdino which part seems like a UI detail? the `csv` part?

**Comment by Incogdino** [comment]
> @Incogdino which part seems like a UI detail? the `csv` part?

![image](https://github.com/user-attachments/assets/3faa3ccd-e63b-46aa-acfd-72c36c1f1332)
![image](https://github.com/user-attachments/assets/72b22df3-aa5b-4ec6-8585-62908729fd45)

For instance, we specified that the import and export format are in csv in our code but not too sure if it should be included in the use cases.

**Comment by damithc** [comment]
When we advise against including UI details in a use case, we are thinking of actions involving specific UI elements such as clicking a button or selecting from a drop-down or typing a specific command. I don't think it applies to mentioning a specific file format. Of course you can generalise this use case further by using a generic term such as 'export format' instead of a specific format, especially if you intend to support multiple formats.

**Comment by Incogdino** [comment]
Okay got it! Thank you prof!
