### ISSUE TITLE
Which level of severity can this be?

### ISSUE THREAD

**Issue by huangjiaxi1111** [nus-cs2103-AY2425S1/forum#752]
If the jar file name does not match the Quick Start section in UG, does it mean that if the user has no idea what `java -jar xxx.jar` means (i.e. no idea that he should change the name of the jar file in the command) cannot use the app at all? Can it be a high severity bug?

**Comment by damithc** [comment]
@huangjiaxi1111 If this is an issue in your project, you are free to update the jar name in your GitHub release to match the name given in the UG. We allow this because there was another name we prescribed for the jar uploaded to Canvas, and some teams used the same name for the jar file they uploaded to the release, without realising that it doesn't match the UG.

Also, now you see why we didn't want to give a specific jar file name in the [AB3 UG](https://se-education.org/addressbook-level3/UserGuide.html). That way, it stays immune to this kind of problems.

**Comment by huangjiaxi1111** [comment]
Ok thank you prof!
