### ISSUE TITLE
Clarification on Documentation Bugs: Can Documentation bugs have severity- High? 

### ISSUE THREAD

**Issue by emmannyyy** [nus-cs2103-AY2425S1/forum#783]
Based on the course website, the general guidelines on severity is listed as follows: 

![image](https://github.com/user-attachments/assets/63029d8f-9b3f-421a-be99-51ca6de3de5d)

I am wondering if the Developer Guide/ User guide having bugs can be ranked as "severity.High". 

In particular, if a use-case was suggested in the DG, but was never at all implemented in the product, therefore making it completely unusable for all developers who wish to test that function, would it be a valid "severity.High" bug? 

My confusion lies in the fact that the product still works for all other features, and is 'usable'. However, none of the functionality claimed in a section of the DG has been implemented, and would thus be 'unusable' for all users. Would this be a valid 'high'?

In the same vein, referring to the PE prep quiz: 
![image](https://github.com/user-attachments/assets/45e4bda9-3b34-4c0d-9f38-274e82f91355)

In this example, the bug's severity was listed as 'high', but technically is still 'usable' for all users. They just need to restart the app. However, it does indeed cause a 'major inconvenience' for most users.

**Comment by damithc** [comment]
In the `severity.High` description, the world 'unusable' doesn't mean literally not possible to use in any way -- rather, the problem is serious enough that potential users would claim it as 'unusable' and wouldn't want to use it.

That said, a good example of a high severity UG bug is if an essential feature (e.g., edit contact) is not explained properly in the UG.

**Comment by emmannyyy** [comment]
I see. Thanks Prof @damithc ! That clears my doubts.

**Comment by yadobler** [comment]
> In the `severity.High` description, the world 'unusable' doesn't mean literally not possible to use in any way -- rather, the problem is serious enough that potential users would claim it as 'unusable' and wouldn't want to use it.

What if the UG pdf was incorrectly exported, rendering all links nonworking and inhibiting both the copying of commands, as well as the searching of commands (ie the entire pdf is image-based)?

---

Since this is not about the content of the UG but the "formatting" of the UG itself (ie one argument is that the UG pdf is not going to be used and that the website is sufficient for users), do we judge this as a "Documentation Bug" or is it a "Feature Flaw" and is it considered high severity?

**Comment by damithc** [comment]
> Since this is not about the content of the UG but the "formatting" of the UG itself (ie one argument is that the UG pdf is not going to be used and that the website is sufficient for users), do we judge this as a "Documentation Bug" or is it a "Feature Flaw" and is it considered high severity?

As far as the PE is concerned, the PDF is the only version of the UG/DG. The existence of a web version should not matter. 
The severity should be based on how much difficulty it causes to someone using the pdf version of the UG/DG.
Formatting/rendering problems in the PDF are documentation bugs.

**Comment by yadobler** [comment]
@damithc makes sense. Thank you for clarification.

CC: @martout2002 this might be relevant to you (via issue 2891 and issue 756). Do look at both issues and weigh your options. All the best
