### ISSUE TITLE
Clarification on severity of incorrect jar file name

### ISSUE THREAD

**Issue by xqtann** [nus-cs2103-AY2425S1/forum#794]
The jar file name stated for launching our app (`java -jar "NUStates.jar"`) in our DG's manual testing section is different from the actual jar file name given to the tester during PE, which was `"CS2103T-F10-3-NUStates.jar"`.

I am wondering if this should be considered a major inconvenience to users, a minor documentation bug, or would that be a response.NotInScope, since the renaming of the jar file name due to the PE test was not made known?

**Comment by damithc** [comment]
@xqtann When writing the DG, you had no way of knowing how the PE jar file will be named. So, the tester can't expect the DG to state the PE jar file name correctly. However, the tester can expect the jar file to match the name of the jar file you put in the GitHub release. 

A side note: you could have just referred the reader to follow the UG on how to run the jar file, rather than duplicate the info in two documents.
