### ISSUE TITLE
More testers on our app than what is supposed to be allocated

### ISSUE THREAD

**Issue by taggyhan** [nus-cs2103-AY2425S1/forum#810]
Hi Prof,

We have received more bug reports on the app than the standard allocation ( 5 x 7 = 35 bugs) --> meaning more testers were allocated to our app.

My Team would like to clarify if this could be taken into consideration during grading? Despite having more testers and henceforth a higher number of bug defense reports to prepare, we still face the same time constraints for defence as other teams.

We would appreciate your understanding of this situation.

**Comment by damithc** [comment]
@taggyhan 
This happens when a student could not test the product they were initially allocated, and is given a second product to test. This results the second product having an extra tester.
To be fair to that team, we ignore the bugs reported by that extra tester when grading the testing aspect the product. However, the team still needs to process all the bugs received, and we can't give them extra time for that, unfortunately. We expect most of the bugs reported by the extra tester are already reported by the other testers, minimising the extra time needed to process them.

**Comment by taggyhan** [comment]
@damithc 
Hi Prof,

We understand and thank you for the concise and prompt response
