### ISSUE TITLE
Packages and their uses

### ISSUE THREAD

**Issue by daronoh** [nus-cs2103-AY2425S1/forum#85]
My understanding is that you should create packages for _types_ that are related to each other.
In my iP, i have an abstract class, and 3 classes that extend this abstract class. I believe this classifies as being related, and would like to bundle them together in the same class. However, following the convention that files in the same package have to be of the same type, does this approach break that rule?
I also have 2 exceptions, and would like to bundle them together in an "exceptions" package.

Is this the right way to handle how I think about packages? 

also, does every file need to be in a package? what about my main executable (e.g Duke) ? when I tried to put that into a "main" package, i got the following error:
"Class DGPT, referenced in file EXPECTED.TXT, will not be accessible from module ip  
Class DGPT, referenced in file README.md, will not be accessible from module ip  
Class DGPT, referenced in file runtest.bat, will not be accessible from module ip"

is the error coming from the fact that my file's directory has now changed, and my files have to adjust accordingly?

**Comment by Johnwz123** [comment]
I believe you're right that related classes should be grouped into the same package. In your case, if you have an abstract class and three classes that extend it, it indeed does makes sense to bundle them together in one package since they share a common purpose or functionality. Creating a separate "exceptions" package for your exception classes is also another good way to organise your code.


> following the convention that files in the same package have to be of the same type

Regarding the above, I believe the convention that files in the same package have to be of the same "type" is more about maintaining logical cohesion rather than enforcing a strict rule so I would think that both your suggested ways of packaging your files would be acceptable so long as it makes logical sense.

For your 2nd question, I don't think every file needs to be in a package, but it's generally good practice to place all your classes, including your main executable (e.g. "Duke"), in packages to avoid naming conflicts and to better organize your code.

Regarding the error you got, yes I believe you are right that the error you're seeing is related to the change in the directory structure.. It seems like it happened because the references to your main class in other files (like `EXPECTED.TXT`, `README.md`, `runtest.bat`) would be outdated after moving it and need to be updated to reflect the new package structure. For example, if your class was previously referenced as `DGPT`, it would now need to be referenced as `main.DGPT` (if you put it in a package named `main`).

**Comment by aditig0305** [comment]
> also, does every file need to be in a package? what about my main executable (e.g Duke) ?

I think according to the Java coding standard, every class needs to be in a package.

https://se-education.org/guides/conventions/java/intermediate.html#:~:text=Put%20every%20class%20in%20a%20package.
