### ISSUE TITLE
Final exam practice 1 Design Fundamentals question

### ISSUE THREAD

**Issue by tayxuenye** [nus-cs2103-AY2425S1/forum#856]
![image](https://github.com/user-attachments/assets/12466fab-e0f4-48da-b680-2fd87e150109)
Why can't the first option be the answer? Are we not supposed to try to achieve a single layer of abstraction using SLAP?

**Comment by ITZXITZX** [comment]
Hello, I think that based on the textbook, abstraction should help to show details that are relevant to the current perspective or the task at hand need to be considered. This involves concealing the implementation of methods so that it is simple for us understanding the method at a high enough level of abstraction.

For example, a `process()` method may involve adding and saving. We do not need to put the entire implementation of `add()` or `save()` in the same method, `process()`.

![image](https://github.com/user-attachments/assets/95f7f457-e5db-4a8d-a120-3665b1278d35)

**Comment by tayxuenye** [comment]
Hi, thanks for your reply. I can understand what abstraction is. I just think "We can even use multiple levels of abstraction." sounds weird because we are encouraged to use single level of abstraction (SLAP).

**Comment by emmannyyy** [comment]
Not 100% sure but I believe that SLAP is a guideline to improve code quality. 

Abstraction can be done on many layers. I.e: A class is an abstraction of data and behaviour. Within behaviours (i.e.: certain functions) like `calculateTotal()`, there may be some sub-steps such as `calculateStepOne()` and `calculateStepTwo()`, and so there can be multiple layers of 'abstraction'. The textbook mentions that we are encouraged to identify a suitable layer of abstraction (that fits a particular context), and then suppress the more complex details to improve understandability of the code. 

However, when implementing the abstraction in code, the `SLAP` principle pushes us to avoid deeply nested code, making it difficult for other developers to understand. We should only have a single layer of abstraction per code block, in order to increase its readability. However, within a single class file, we would have multiple layers of abstraction, but each code block only has **1 layer of abstraction**.

**Comment by tayxuenye** [comment]
Thank you

**Comment by damithc** [comment]
Good discussion, all. 
To add, SLAP is about the abstraction level in _one_ function/method. It advocates limiting the code of one method to one level of abstraction, and staying at the highest level of abstraction possible. This usually requires lower level details to be extracted out as separate methods, and as result, different methods will now be at different levels of abstraction (i.e., those extracted out methods are at a lower level of abstraction than the original method). So, SLAP actually results in different methods being defined at different levels of abstraction.
