### ISSUE TITLE
Clarification on LSP

### ISSUE THREAD

**Issue by vinceg4** [nus-cs2103-AY2425S1/forum#868]
Given this scenario:
<img width="395" alt="image" src="https://github.com/user-attachments/assets/0fbdeb5e-618a-4bd4-81b6-c82a4a9aad3e">

Suppose there is code in `Admin` class that assumes negative percent values. Am i right to say that this code will violate LSP because we can no longer sub `Admin` for `Staff`?

**Comment by emmannyyy** [comment]
According to Wikipedia, the LSP states the following: 
`Let φ(x) be a property provable about objects x of type T. Then φ(y) should also be true for objects y of type S where S is a subtype of T `

Based on your supposition, if the `Admin` class assumes negative per cent values (and hence cannot work with positive values), then I believe this would violate the LSP. This is because φ in this example can refer to any function/behaviour that can be applied to the Staff class. Thus, if the admin class produces wrong results due to only having negative percent values, it does not satisfy the LSP. Essentially, the `admin` class cannot be substituted for the `staff` class, since it would result in the wrong values. 

However, if `Admin` class has the ability to handle **both positive and negative** values as the example in the textbook gives, it can be substituted in place of the staff class, hence not violating the LSP.

**Comment by vinceg4** [comment]
Thank you! @emmannyyy

**Comment by damithc** [comment]
Yup, good answer @emmannyyy
