### ISSUE TITLE
Question about [p3.05]

### ISSUE THREAD

**Issue by xqtann** [nus-cs2103-AY2425S1/forum#870]
Why is it that C or E is not the correct answer? It seems to me that B, C, E are all correct, and among them, C is the most specific one.
The only difference between options C/E and option B is that options C/E has the `update(int)`. 
I thought that since from the given code, `ProgressWatcher` implements `Watcher`, the `update(int)` can be in both classes as shown in one of the examples in the CS2103T website.

![image](https://github.com/user-attachments/assets/57013946-c768-465d-8c12-ab9a71b0f220)

From the CS2103T website:

![image](https://github.com/user-attachments/assets/5c4d292f-698a-4564-85cd-03db6b162f23)

**Comment by emmannyyy** [comment]
Not 100% sure, but I suspect the reason that C and E aren't the answer is because the method should also be annotated as `{abstract}`. 

Got this wrong as well sigh. I believe it was stated that the method had no concrete/default implementation yet, hence that was a clue that it was abstract. 

This was illustrated in the textbook as follows: 
![image](https://github.com/user-attachments/assets/1bbfa919-3943-4ee4-820c-e18a8d1490cd)

**Comment by damithc** [comment]
@xqtann To clarify, ProgressWatcher doesn't contain an `update()` method.
<img width="380" alt="image" src="https://github.com/user-attachments/assets/8cc9576f-a42e-48b0-a719-6a4ea1f2aa56">

Therefore, there should not be an `update()` method inside the `ProgressWatcher` class box. This rules out C and E. There should not be a `update() {abstract}` inside it either.
