### ISSUE TITLE
Clarification on the return types of overloaded and overridden methods

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#872]
Hi, I'm a bit confused by the descriptions of overloading and overriding in the textbook. In one section, it says that overloaded methods have the same name but different type signatures (but return type is not part of the type signature). Then in another section, it says overloaded methods can have possibly different return types. 
<img width="644" alt="Screenshot 2024-11-22 at 4 07 18 PM" src="https://github.com/user-attachments/assets/0aaee8da-6d50-42ad-ace0-dfa66125d3c5">
<img width="639" alt="Screenshot 2024-11-22 at 4 06 41 PM" src="https://github.com/user-attachments/assets/3410650c-a10f-48c2-87dc-dfa707b2bf76">

On the other hand, for overridden methods, one section says it has the same or a subtype of the original return type, but the other section says overridden methods have the same return types. 
<img width="644" alt="Screenshot 2024-11-22 at 4 07 28 PM" src="https://github.com/user-attachments/assets/6e93f467-fa30-453b-88d0-55d2e2ef919f">
<img width="643" alt="Screenshot 2024-11-22 at 4 06 52 PM" src="https://github.com/user-attachments/assets/c70d973c-2f2b-433a-a2b1-b09f26e021d5">

**Comment by emmannyyy** [comment]
For **overloaded methods**, yes the methods can have the same name but parameter types(hence different method signature). The return types can be different. I like to think of overloading as variation of a method that does a similar thing on different parameters. 
e.g: `int multiply(int num)` and `double multiply(double num)`. Both of these are overloaded methods that multiply the given `num`, but work on different types, and hence have different return types. 

On the other hand, for **overriden methods**, they are meant to change the behaviour of a function that was inherited from a base class. This enables for polymorphism to occur. The return type for the derived class can be a subtype of the return type for the base class. I think we probably did something super similar in CS2030. 

e.g: Consider `Cat extends Animal`. Assume that the Animal class has a method called `MakeNoise()` that returns an `AnimalNoise` object. By `@overriding` the `MakeNoise()` function in the `Cat` class, a `CatNoise` (subtype of AnimalNoise) can be returned.

**Comment by yadobler** [comment]
Also, overloading occurs within the class, and you can think of it as "one name, different flavours". You can say that the same name is _overloaded_ with different possible input variables. **different signatures**

Overriding is "hiding" the inherited function and putting a brand new function _over_ it. You can say that it _overrides_ the parent function. **same signature**.

---

If you dig deeper, Overriding is processed ~~compile time (javac)~~ runtime (jvm) by using the new function instead of copying the parent function, which allows the object to run its own version of the method while still being able to take the place of the superclass instance.

Overloading is done in ~~runtime (jvm)~~ compile time (javac) where ~~jvm~~ javac does some weird stuff to decides to widen the scope or unbox the passed variable, Lowkey like on-the-spot overriding but that's not impt. (unfortunately it's not syntatic sugar like other languages that does function mangling, where overloading is secretly having two different functions that the compiler will resolve for you)

**Comment by annabellekk** [comment]
Thank you!

**Comment by damithc** [comment]
@emmannyyy @yadobler Thanks for the correct explanations.

@annabellekk It should read as `same (or a subtype of the) return type` in both places.

**Comment by somethingfishyfishy** [comment]
@yadobler 
> Overriding is processed compile time (javac) by using the new function instead of copying the parent function. Overloading is done in runtime (jvm)

It is the other way round, but the idea is right.
Overriding is done at run time, overloading is done at compile time

**Comment by yadobler** [comment]
@somethingfishyfishy good catch!

My bad. Yes it's the other way. Overriding is runtime (jvm) since the funky subclass superclass thingies aren't known until runtime

Overloading is compiletime (javac) where the method is appropriately modified to match the signature in one of many ways supported by javac
