### ISSUE TITLE
Practice Exam 1 Q6 (object/class diagrams)

### ISSUE THREAD

**Issue by rayray39** [nus-cs2103-AY2425S1/forum#873]
why is the last option not valid? Thanks!

![practice exam 1 q6](https://github.com/user-attachments/assets/a546f80b-63bd-4151-a121-c9161336f111)

**Comment by Incogdino** [comment]
I think it specifies a 1 multiplicity for the Door class so it must be present in the given UML diagram. Which is not the case here and thus it is not valid.

Unless the multiplicity is 0..1, then I guess it is correct.

**Comment by JoanneHing** [comment]
Same insight with @Incogdino , the multiplicity of `1` between `Table` and `Door` means that if there is a `Table` object, it must be associated with one and only one `Door` object. Since the object diagram is not having any `Door` instances connecting to `Table`, it doesn't match the multiplicity stated. Hence not a valid match.

**Comment by jagdeepsh** [comment]
I also agree with the above answers, perhaps a visual explanation might help too. If you refer to the textbook, they have a list of common multiplicity, attached below for reference as the photo. If your multiplicity is `1`, it means it is `compulsory`, and it must be linked to the object at `all times`. The photo below is a handy guide when it comes to referencing multiplicity.

<img width="675" alt="Screenshot 2024-11-24 at 9 47 44 AM" src="https://github.com/user-attachments/assets/95c8ae0a-2a91-4db5-a13b-0c59da50af6c">

**Comment by damithc** [comment]
Good answers @Incogdino @just @JagdeepSinghNUS
