### ISSUE TITLE
Question on Navigability

### ISSUE THREAD

**Issue by jagdeepsh** [nus-cs2103-AY2425S1/forum#882]
Just to check, for this question here, the reason why `b` is not the right answer is because of the highlighted part of the question where they are referencing to that particular association? Cause the second photo shows the textbook stating an example that looks exactly the same but with bi-directional navigability (2nd photo). Wanted to confirm if the reason this was wrong is because the question is referencing specifically to the yellow highlighted part.

Canvas Question:
<img width="979" alt="Screenshot 2024-11-23 at 4 48 43 PM" src="https://github.com/user-attachments/assets/5c6133ce-a5d8-421a-bbfc-d7e3247a6590">

Textbook reference:
<img width="667" alt="Screenshot 2024-11-23 at 4 49 00 PM" src="https://github.com/user-attachments/assets/f980b07d-3318-4e94-b81b-a924c6d862a6">

**Comment by Wxy2003-xy** [comment]
I think there isn't navigability from bot to mat in this qn

**Comment by uniqly** [comment]
In the code there are two different associations from `Mat` to `Bot`. The first is a unidirectional association `Mat ---> "helpers 0..5" Bot` and the second is a bidirectional association `Mat "partner" <---> "partner" Bot`. Since the question is asking specifically about the first association, we cannot choose option B to represent that.

Note: Just because the two classes have references to each other, that they have a bidirectional association ([see textbook](https://nus-cs2103-ay2425s1.github.io/website/se-book-adapted/chapters/oop.html#navigability))

![image](https://github.com/user-attachments/assets/bff19da7-cb35-46fa-9e67-082e62461266)

**Comment by jagdeepsh** [comment]
I see, I understand the idea now, thanks for clarifying.

**Comment by damithc** [comment]
Good answer @uniqly 👍
