### ISSUE TITLE
Practice paper part 3 [p3.06] UML: CD: code to CD

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#890]
For this question, why is the direction of navigability from a1 and a2 to u instead of the other way around? Is the direction from Activity to UiWidget because of how the question is phrased? (i.e. a1 and a2, both being **watched by** a UiWidget object u). Initially I thought since u watches a1 and a2, the navigability should be from u to a1 and a2. And thus I chose answer C. 
<img width="767" alt="Screenshot 2024-11-23 at 11 03 25 PM" src="https://github.com/user-attachments/assets/150fcf0e-a234-485c-8a93-63934f1a3fbb">
<img width="946" alt="Screenshot 2024-11-23 at 11 04 08 PM" src="https://github.com/user-attachments/assets/809357b1-df23-4edf-baff-67cf6d19e309">

**Comment by AbdulrahmanAlRammah** [comment]
If you follow the diagram UI widget extends the abstract class progresswatcher which implements the watcher interface. The activity has references to the watcher. Since UI widget is a watcher, the activity will have a reference to it and not the other way around. There is no way to navigate from the UI widget to the activities because it doesn't contain references to activities. The activity does have a reference to UI widget because it has a list of watchers (and UI widget is a watcher). The question phrasing is likely intentionally trying to throw you off.

**Comment by emmannyyy** [comment]
![image](https://github.com/user-attachments/assets/75f38e23-a3bd-48c0-9ed9-6511811aa8ac)


I think the code indicates that each `Activity` object has a reference to the `Watcher`s, and hence the navigability should be from activity to the watcher. 

Also, I believe the code still works. After each `Activity` executes, it calls the `update()` method that is implemented by `UiWidget` objects, allowing for the observable-observer pattern to still work.

**Comment by annabellekk** [comment]
Got it, thanks!!

**Comment by damithc** [comment]
Good answers @emmannyyy @AbdulrahmanAlRammah 

Yes, the navigability is determined by the code, not how the question is phrased.
