### ISSUE TITLE
Practice exam part 3 [p3.07] UML: CD: code to SD

### ISSUE THREAD

**Issue by nws321** [nus-cs2103-AY2425S1/forum#892]
For this question, why is the activation bar of option A not starting at c since it just got instantiated?
<img width="824" alt="Screenshot 2024-11-23 at 11 53 10 PM" src="https://github.com/user-attachments/assets/ea20cbbd-3cfd-4e76-b4a4-b98f477d2d34">

**Comment by AbdulrahmanAlRammah** [comment]
The activation bar has been omitted in the drawing. It is not a requirement to show the activation bar. If they were to show it, it would start at c. However, it is not required so they did not show it. This question is trying to check that you know S must exist before C since s is used to create c.

**Comment by damithc** [comment]
@AbdulrahmanAlRammah's explanation is correct.
