### ISSUE TITLE
Practice paper part 3 [p3.15] domain modelling

### ISSUE THREAD

**Issue by annabellekk** [nus-cs2103-AY2425S1/forum#893]
Hello, for this question, I get why CCDs are more suitable than class diagrams for domain modelling. But I don't understand why sequence diagram is a suitable tool for domain modelling? Since from my understanding, sequence diagrams involve the more technical aspects, like method calls between objects and classes, and they model the logic of the program, and thus I would think that it is less suitable for domain modelling than class diagrams?  
<img width="765" alt="Screenshot 2024-11-24 at 9 39 01 AM" src="https://github.com/user-attachments/assets/41a2ec8b-8953-4cc7-8f0a-681436e3a906">

**Comment by Incogdino** [comment]
I was curious about this too. I found an almost identical question from the previous semester [here](https://github.com/nus-cs2103-AY2223S2/forum/issues/417#issuecomment-1521345764)

I guess what this question was testing was just for us to identify that class diagrams are not suitable for domain modelling?

**Comment by cth06-Github** [comment]
Here's what I think: <br>

I think the key idea is that any diagram that is modelling a solution should not be used. Because we want to model a **problem** (domain modelling), not a solution. Class diagrams are meant to model after solutions. Why sequence diagrams can model a problem -- 
![image](https://github.com/user-attachments/assets/d3348356-8b6d-411b-88a9-36fb5ec896d5)
^obtained from https://www.geeksforgeeks.org/unified-modeling-language-uml-sequence-diagrams/

I think sequence diagram can be used to see how things interact as time passed, which can be used to model a problem. <br>

Why class diagram can only(?) model after solutions -- because class diagram contains methods(?) (I think that's the reason, but can't be 100% confident). When we model a problem, there is no such concept as a method/function in that correspond in real life I would think. Attributes still make sense perhaps considering how the snake and ladder modelling is done via conceptual class diagram in the textbook. I think that is also the reason why one of the key difference in Conceptual class diagrams (CCDs) is that there are no methods in CCDs.

**Comment by damithc** [comment]
As @cth06-Github said, sequence diagrams can be used for domain modelling as well, to model interactions between entities in the domain. But there is no point using class diagrams for domain modelling, as there is already a better alternative for modelling class structure in the domain (i.e., CCDs)

The question is missing the following sentence: `Which of the following five will you omit?`

**Comment by annabellekk** [comment]
Noted, thank you!
