### ISSUE TITLE
Question about association 

### ISSUE THREAD

**Issue by Feng1231** [nus-cs2103-AY2425S1/forum#896]
In this diagram, I believe that it is quite clear that there should be a bidirectional association r/s btw action and task. 
However, why is it represented by two unidirectional arrows (one from task to repeatable, one from action to task)? I thought representing it using two unidirectional arrows in this case is not correct.
![image](https://github.com/user-attachments/assets/e1db48b2-a2a7-4c8d-817e-3ce42d05f924)

From course material:
![image](https://github.com/user-attachments/assets/ff47cfb8-c9f4-4b98-973c-2306ca10dce3)

**Comment by cth06-Github** [comment]
<img width="485" alt="image" src="https://github.com/user-attachments/assets/43ea5b36-6631-4070-9b0b-66da55a78bde">

I think the reason is because there is no (direct) association from `Task` to `Action`. From the image I screenshot, the code `Repeatable owner` in `Task` class indicates that there is an association from `Task` to `Repeatable`, thus there is an arrow drawn from `Task` to `Repeatable` in the class diagram. No where else in the code for `Task` class suggests that there is an association from `Task` to `Action`. <br>

We can infer that there is an association from `Action` to `Task` due to the code `List<Task> tasks` in the `Action` class.

**Comment by damithc** [comment]
@cth06-Github's explanation is correct 👍
