### ISSUE TITLE
Is it possible to omit the certain attribute values in Object diagram

### ISSUE THREAD

**Issue by DennieDan** [nus-cs2103-AY2425S1/forum#899]
![image](https://github.com/user-attachments/assets/005cb2f2-998b-46b9-ae89-418ce6e8c2e6)
As per the textbook, 
> _Attributes_ compartment can be omitted

I am wondering when it is not omitted, is it still correct if the Object diagram doesn't show certain values?

Let's take the **Additional practice questions for part 2** as an example:
```java
class Handout extends Document { 
    public List<Brochure> referenced; 
    private List<Section> sections; 
    protected boolean isFull; 
    private int page = 0; 
    String heading; 
    // ...
 }
```

![image](https://github.com/user-attachments/assets/76f43450-24ef-4416-aa53-51b6ca1195fc)
![image](https://github.com/user-attachments/assets/31838501-d51d-46f1-a2b1-ec2a88665524)
Is this compliant with the code? (The `Handout` object doesn't show the values of `isFull = false` and `page = 0`)

**Comment by cth06-Github** [comment]
To be honest, I'm not very sure. I wanted to say it should be fine to omit some of the attributes because it depends on what we want to highlight to the readers. Though it's quite interesting why the particular use of word "compartment". <br>
It is interesting to note that for class diagrams, the textbook explicitly stated that some of the attributes can be omitted:
> The 'Operations' compartment and/or the 'Attributes' compartment may be omitted if such details are not important for the task at hand. **Similarly, some attributes/operations can be omitted if not relevant to the purpose of the diagram**

I don't see why the object diagram should be any different from the class diagram. So perhaps it is okay to only show some of the attributes for object diagrams. Another way to think about it is perhaps to think about how we are always told that if the diagram don't say anything, we can't assume anything. Using the context of the question, including `heading` attribute in the object diagram will tell the readers that the object has a heading attribute, and has the value "Intro". Is that statement correct? Even though the statement made no mention to `isFull` and `page`, that perhaps does not matter because the statement, in itself, is true. So based on that, perhaps omission of some attributes in object diagrams is still acceptable.

**Comment by damithc** [comment]
> ![image](https://private-user-images.githubusercontent.com/110723295/389268429-31838501-d51d-46f1-a2b1-ec2a88665524.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDk1OTAsIm5iZiI6MTczMjUwOTI5MCwicGF0aCI6Ii8xMTA3MjMyOTUvMzg5MjY4NDI5LTMxODM4NTAxLWQ1MWQtNDZmMS1hMmIxLWVjMmE4ODY2NTUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNVQwNDM0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjMxYzM0M2ZmNzE1NDlhYzA5ZDNjYzRkMTI1N2IyZDA1ZGJhM2E0NWEzM2ExYmJlMDhiMzgwOWQyNDgxZWQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PlLQkQYe90KD1eA_P54n_A28CAnBNyGodsAyO9g-QC8)
> Is this compliant with the code? (The `Handout` object doesn't show the values of `isFull = false` and `page = 0`)

@DennieDan Yes, it is fine to omit less important attributes in an object diagram. In this case, it is fine to omit `isFull = false` and `page = 0` as their value is either unknown or they retain the default value.

**Comment by DennieDan** [comment]
@cth06-Github thank you so much for your detailed explanation
