### ISSUE TITLE
Clarification on Object Diagram

### ISSUE THREAD

**Issue by ruiming97** [nus-cs2103-AY2425S1/forum#900]
Hi! I understand that an object diagram typically does not include multiplicity, methods and class-level attributes. Are there other elements that should also be excluded? Specifically, should object diagrams avoid showing relationships like composition, aggregation, inheritance, or interface implementation? Thanks in advance!

**Comment by CYX22222003** [comment]
I think inheritance and interface implementation should be ignored as the object diagram will always show an object of parent class or child class but not both. But we can still show aggregation and composition as they can be legitimate relationship between instances.

**Comment by cth06-Github** [comment]
I agree with @CYX22222003 

To add on, interface cannot be instantiated, so it's not possible to have an interface object, thus there won't be an interface in object diagram.
From #878, Prof commented that for the part b question which requires drawing an object diagram, the composition is missing. This to me suggests that showing composition, (and by extension, aggregation) can be drawn for object diagram.

Message edited: dependencies should not be shown in object diagrams too.

**Comment by ruiming97** [comment]
@CYX22222003 @cth06-Github Thanks for the inputs! I understand that we should only show either the object's parent class or child class but not both. However, in the case that there are two objects, one is of the parent class and another of the children class, do we need to show inheritance here?

**Comment by ruiming97** [comment]
@cth06-Github I just realise you mentioned that extension can be drawn just like composition and aggregation, which addresses my previous concern, thanks again!

**Comment by ruiming97** [comment]
@cth06-Github I note that you say there won't be an interface object in the object diagram as it's impossible to have an interface object. However, we are allowed to use the interface type as the reference type of an object right? For example, if class A implements interface B, and we have an object of type A, it's valid to do `a:B` even though B is an interface. Am I correct?

**Comment by cth06-Github** [comment]
> However, in the case that there are two objects, one is of the parent class and another of the children class, do we need to show inheritance here?

It will be very strange to show inheritance. For example, class B inherits class A. I have object A `objA` of class A and object B `objB` of class B. If we draw like this:
![image](https://github.com/user-attachments/assets/82996cc5-fdfc-4e68-af3c-66d56937cdf7)

While it does ensure that every object is shown only once, I think conceptually wise, it feels weird, as if `objB` is related to `objA` when `objB` and `objA` is not related in any way except their _class_. So I don't think it is correct to draw like this. Composition and aggregation relationship in objects still make sense I think. <br>

> I note that you say there won't be an interface object in the object diagram as it's impossible to have an interface object. However, we are allowed to use the interface type as the reference type of an object right? For example, if class A implements interface B, and we have an object of type A, it's valid to do a:B even though B is an interface. Am I correct?

Good question, I never thought about it. I wanted to say I don't see why not, i.e. I think it can be correct because any implementation has a `is-a` relationship. So object A is an A, and object A is a B are both valid and therefore a:B can be correct, if argued that way. However, I also note in the textbook that:

> objectName:ClassName is meant to say 'an instance of ClassName identified as objectName'.

So according to that, if we write a:B, it is saying that an instance of `interface B` identified as `a`. An interface cannot be instantiated so saying that there are instances of an interface is not correct, therefore writing as a:B is not correct when argued this way. <br>

These are my thoughts, I am more inclined to go with the latter because in the text book, generic notation for object diagrams is described as `instance:Class` -- there seems to be an emphasis that it is a **class**.

If others and prof @damithc  can chime in, that will be great as well.

**Comment by damithc** [comment]
Good discussion @ruiming97 @CYX22222003 @cth06-Github 

**Inheritance should not be shown in object diagrams.** First, an object should be shown as parent class or child class, not both. As @cth06-Github said, even if there are two separate objects (one of parent class and one of child class), there is no inheritance relationship between those two objects. The inheritance relationship exists between classes, not objects.

**However, you may show an object as of an interface type**, if the exact concrete class doesn't matter to the purpose of the diagram. While an interface cannot be instantiated, you can treat an object as an 'instance of' an interface. Same applies to abstract classes.

**Comment by ruiming97** [comment]
@cth06-Github @damithc Thanks for the inputs and clarification! I will close this issue now
