### ISSUE TITLE
Clarification on Default Visibility in Java

### ISSUE THREAD

**Issue by ruiming97** [nus-cs2103-AY2425S1/forum#904]
Practice Paper Question:
<img width="973" alt="image" src="https://github.com/user-attachments/assets/d8f736b1-e8a1-42ba-b4f6-6d0215d27ea0">
Answer given:
<img width="909" alt="image" src="https://github.com/user-attachments/assets/e6a211b6-e4fd-48c1-8131-6a65576df131">

Based on the given answer, I understand that the default visibility of a class method is `package-protected`. Therefore, in the `Activity` class diagram, the method visibilities are shown as `~`. However, for interfaces, I understand that methods are automatically declared as `public abstract`.

This leads me to question whether it is necessary to explicitly mark methods in an interface as abstract (e.g., by using `{}` or _italics_), or if doing so is unnecessary. Does the label of interface `<<interface>>` implicitly mark all its methods to be abstract?

Adding on, I note that the overridden method `update(int)` in `UIWidget` is marked as public even though it's actual method signature is not shown, can I assume that for a class that implements an interface, the overridden methods will always be public? 

Appreciate any clarification on this matter.

**Comment by MAOXIONGKAI** [comment]
1. `This leads me to question whether it is necessary to explicitly mark methods in an interface as abstract (e.g., by using {} or italics), or if doing so is unnecessary. Does the label of interface <<interface>> implicitly mark all its methods to be abstract?`
This is a very good question, actually I am wondering the same but I guess it is safe to assume the answer to be yes. The reason why I am wondering the answer of this is because it is actually possible to be have concrete implementation in an interface, through the use of default keyword, which specifies the default behaviour of a given method signature if a class implements the interface but does not provide its own implementation. But I vaguely remember that such practice is not recommended, not sure if it is because of the presence of abstract class, but I will go and find out about this. If this is true, then I think can just assume `<<interface>>` discriminator implies all methods to be abstract.
2. `Adding on, I note that the overridden method update(int) in UIWidget is marked as public even though it's actual method signature is not shown, can I assume that for a class that implements an interface, the overridden methods will always be public?`
Note that a overriding method in Java can only have access modifier that is equally or more general than the access modifier of the original method. As you have already mentioned, methods in interface are implicitly public by default, hence any overriding methods in classes that implement this interface would have the access modifier to be public, therefore it is true that the overriden methods will always be public.

Hope this helps, and hopes someone can help me clarify on first part as well. I will try my best to figure out an answer and reply over here as well, thank you very much!

**Comment by MAOXIONGKAI** [comment]
Ok, I have clarified a bit on the first point in my own explanation above, it seems like default keyword in interface is actually an approach to deal with legacy code and an easy fix to allow for extension of interface functionalities without breaking the existing code. Basically, before Java 8, interface is really only consists of abstract methods, but as the current codebase extends for future Java version, it is realized that adding new method signature to the interface requires all the existing classes that implement this interface to include their own implementation of this method respective, which is very time consuming and labor intensive. Therefore, they use default keyword to provide concrete implementation of the method to provide flexibility for the implementing class, which allows them to **not** provide their own implementation for a certain method in the interface. Similarly, interface also allows static methods for a similar reason as above.

However, that being said, it seems like such issue can be common in modern day software as well(interfaces of existing system may need to be extended with new methods without forcing existing classes to provide their own implementation). I understand that static method in interface can still be easy to annotate and differentiate, just by underlining them. But for default method, I can't find any info in UML Diagrams about this, probably because this is a Java language design choice and not a general info that needs to be described by UML, but I am also curious if there's a way to properly annotate default method in interface using UML.

Hi Prof @damithc, is there anything to work around this issue in UML? Thank you very much!

**Comment by ruiming97** [comment]
@MAOXIONGKAI Thanks a lot for the helpful insights! Appreciate the time taken on this :) I will leave this issue open until your query has been fully addressed

**Comment by zaidansani** [comment]
Hmm, with regards to the first question, don't we already indicate `~` (package-private) visibility for all methods/fields without explicit access modifiers? Going by that logic, we should be indicating that the methods are all by default `abstract` and `public` for interfaces.

**Comment by damithc** [comment]
`<<interface>>` already implies everything is abstract. There no need to (you should not) add `{abstract}` to every method in the interface.

**Comment by ruiming97** [comment]
Thanks everyone for the inputs! I will close the issue now
