### ISSUE TITLE
What's the Design Pattern for AY18/19 Sem 1 Question 1b

### ISSUE THREAD

**Issue by cth06-Github** [nus-cs2103-AY2425S1/forum#918]
I was doing Q1 of AY18/19 Sem 1 Part 2 (see picture below), and the relevant class diagram for that was explained in one of the videos going through drawing class diagrams in [Week 8 Topics](https://nus-cs2103-ay2425s1.github.io/website/schedule/week8/topics.html) (specifically, "Drawing class/object diagrams (intermediate) - `Action`, `Task`, `History`") (it's the same question used). Using that class diagram as the basis, I tried to answer 1b), which asked what design pattern it is.
![image](https://github.com/user-attachments/assets/6b284c64-bd90-4a36-9604-12b97fc03782)

I felt that there are 2 design patterns here: Command pattern and Observer pattern. The image showed how I saw the similarity for both patterns. However, question 1b felt like we can only choose _1_ pattern. I was wondering if my analysis went wrong, or that if there are really 2 design patterns, is there one that is more prominent than the other? (Which I don't see it now). Or it will be ok to just state any of the correct design patterns?

**Comment by emmannyyy** [comment]
I think the `Command` pattern is used, and I have the same idea as you for that. 


However, I don't really think the `Observer` pattern applies here. Referring to your annotation below: 
![image](https://github.com/user-attachments/assets/b1def8f8-aceb-4976-bb4c-c118edcb2bed)
In the textbook, I believe `StudentListUi` and `StudentStatsUi` are both concrete observers, and the one being observed is the `StudentList`. Then, all concrete observers must implement the `Observer` interface. 

In the context of the question, however, it seems that `ActionX` and `ActionY` are not the observers but rather the ones being observed. They are observed by only 1 class, which is the `History` class. 

Since this `History` class did not observe the Actions `ActionX` and `ActionY` by implementing an interface, I believe this doesn't closely match the observer pattern anymore. (`History` only manages to keep track of `ActionX` and `ActionY` via directly having a list of `Repeatables`). 

Generally, if there was an interface which would have allowed multiple classes that implemented it to keep track of the `Action` objects, then perhaps I would be inclined to agree.

**Comment by jagdeepsh** [comment]
Here is my take on this, I think it is just command pattern, but not for the reason mentioned above. Mainly because of the fact that History does not have any notification method or any way to notify the obervers. Referencing the attached image below in the textbook, keywords here are `interested in being notified`. History Class does not have that.

<img width="728" alt="Screenshot 2024-11-26 at 9 00 23 AM" src="https://github.com/user-attachments/assets/bf912047-4f08-4cde-9099-d693a605917a">

@emmannyyy In regards to your response, regarding the paragraph:
> Since this History class did not observe the Actions ActionX and ActionY by implementing an interface, I believe this doesn't closely match the observer pattern anymore. (History only manages to keep track of ActionX and ActionY via directly having a list of Repeatables).

In the part where you mentioned because it did not implement an interface, I don't think that is a requirement for observer, cause if you notice in the reference image from the textbook, StudentList also did not implement the Obersever, rather it is just associated with it for its `addUi()` method. So technically it does not need to implement the interface, however, I also don't think it is considered observer for the point I mentioned above. Hope this helps :)

**Comment by cth06-Github** [comment]
Thank you @emmannyyy and @JagdeepSinghNUS for your inputs. <br>

I feel that @JagdeepSinghNUS made a very good point, though if that's the case does it mean the solution for tutorial 11 exercise 3 is incomplete because there is a missing `notifyWatcher()` method in the `<<Observable>> Process` class?
<img width="674" alt="image" src="https://github.com/user-attachments/assets/52b9fa99-ef22-48a6-a93d-35e3d27e7615">

(to use the full solution instead of the partial solution as above, and incorporating `notifyWatcher()` that seems to be missing):
![image](https://github.com/user-attachments/assets/49f9ddd5-582c-47fc-80fe-3babaeaafa48)


@damithc Prof, may I ask if you have any inputs for this?

**Comment by damithc** [comment]
To quickly answer some of the questions raised:
* The expected answer is Command pattern.
*  It seems `History` is keeping track of past actions, in case they need to be repeated later (this is way to implement undo/redo). In this context, there are no observers wanting to get notified when an observed object change, without observed objects being dependent on observers. Hence, no observer pattern, and no need for it either.
* `-notify...()` method is omitted in the tutorial question because it is a private method (less important to show). But if we were to show it, it should not appear in the facade class, as the facade class does not perform logic/work (it is just an intermediary only). The `notifyWatchers` method will appear only in the `Process` class.

Let me know if I missed any question.

**Comment by emmannyyy** [comment]
Hey thanks for your comment @JagdeepSinghNUS 

Quoting your response below: 
> In the part where you mentioned because it did not implement an interface, I don't think that is a requirement for observer, cause if you notice in the reference image from the textbook,  StudentList also did not implement the Observer, rather it is just associated with it for its `addUi()` method. So technically it does not need to implement the interface, however, I also don't think it is considered observer for the point I mentioned above. Hope this helps :)

Regarding this, I believe that `StudentList` does not implement the Observer interface because it is **not an observer, but rather the entity that is being observed**. From my understanding, the observers are `StudentListUi` and `StudentStatsUi`. 

Given the pattern in the textbook, only `Observer` objects need to implement the `Observer` interface. 

Observerables don't need to implement an interface, only observers do. However, observables must have an implemented method to add observer objects, and a corresponding `notifyObservers()` method.

**Comment by cth06-Github** [comment]
Thank you Prof and everyone, will be closing this issue.
