### ISSUE TITLE
Difference between gitk graphic and course website graphic

### ISSUE THREAD

**Issue by Andrew22Teoh** [nus-cs2103-AY2425S1/forum#97]
Hello, I'm currently working on W3.1b RCS: Branching. In the course instructions (step 9), the branch graphic shown is as shown below:
<img width="432" alt="image" src="https://github.com/user-attachments/assets/f2cd71db-023d-4654-9211-501700a35cfa">

However, when I check the branch graphic with gitk, I get the graphic as shown below. 
![telegram-cloud-photo-size-5-6228593248499253627-x](https://github.com/user-attachments/assets/86b625ea-a3cc-4ac9-8a1c-4e4c35adeef4)

I'm not sure if this reflects a problem, or is just a difference between how Sourcetree and gitk represents the branches. For reference, I'm using git on the CLI. Does anyone else working with the CLI have this same discrepancy, or have I done something wrong somewhere?

**Comment by yanhwee** [comment]
I see that some of your commit messages do not follow what’s in the guide, so I presume that’s not the problem. Rather I infer that the problem lies in the structure of the branch. Perhaps you could try using Sourcetree to visualise the structure and confirm that this is just how the branch structure looks like in your repository? Alternatively, a third option, you can also visualise the git branches on the CLI via `git log --all --decorate --oneline --graph`. I hope this helps!

**Comment by damithc** [comment]
@yanhwee's commit graph, on Sourcetree and gitk

![image](https://github.com/user-attachments/assets/c0a92001-b1f9-4649-ab0b-a54de4ccc021)

![image](https://github.com/user-attachments/assets/c095062c-4505-4993-b129-0bd96494bcd5)

So yes, the two tools show the graph differently, and Sourcetree's one looks nicer.
Also note that sometimes both can differ from the mental picture we have of how it _should_ appear.

**Comment by Andrew22Teoh** [comment]
Thank you both for the responses!
I used Sourcetree to scan for the repository and look at the branch structure there, which gave me this graphic below:
<img width="586" alt="image" src="https://github.com/user-attachments/assets/be4ef71f-be71-484d-8ce1-66c40019f696">

I'm pretty sure that this is functionally identical to the provided graphic in the instructions, so this should be as expected!
